-- VHDL Entity mil1553_tb.Mil1553_RT_tester.interface
--
-- Created:
--          by - jean.UNKNOWN (DESKTOP-6AOI8L3)
--          at - 08:27:38 12/04/2022
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY Mil1553_RT_tester IS
   PORT( 
      DataOut          : IN     std_logic_vector (15 DOWNTO 0);
      DataValid        : IN     std_logic;
      Intr             : IN     std_logic;
      OutEn            : IN     std_logic;
      OutN             : IN     std_logic;
      OutP             : IN     std_logic;
      ServiceReqVector : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest   : IN     std_logic;
      Strobe           : IN     std_logic;
      SubsystemFlag    : IN     std_logic;
      Addr             : OUT    std_logic_vector (15 DOWNTO 0);
      Cs               : OUT    std_logic;
      DataIn           : OUT    std_logic_vector (15 DOWNTO 0);
      InN              : OUT    std_logic;
      InP              : OUT    std_logic;
      Rd               : OUT    std_logic;
      Wr               : OUT    std_logic;
      MyRtAddr         : BUFFER std_logic_vector (4 DOWNTO 0);
      clk              : BUFFER std_logic;
      nReset           : BUFFER std_logic
   );

-- Declarations

END Mil1553_RT_tester ;

--
-- VHDL Architecture mil1553_tb.Mil1553_RT_tester.struct
--
-- Created:
--          by - jean.UNKNOWN (DESKTOP-6AOI8L3)
--          at - 08:27:38 12/04/2022
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

LIBRARY barij_lib;
LIBRARY mil1553_lib;

ARCHITECTURE struct OF Mil1553_RT_tester IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL BC_Cs       : std_logic;
   SIGNAL MyBCAddr    : std_logic_vector(4 DOWNTO 0);
   SIGNAL cpu_Addr    : std_logic_vector(0 TO 15);
   SIGNAL cpu_DataIn  : std_logic_vector(15 DOWNTO 0);
   SIGNAL cpu_DataOut : std_logic_vector(15 DOWNTO 0);
   SIGNAL cpu_Rd      : std_logic;
   SIGNAL cpu_Wr      : std_logic;


   -- Component Declarations
   COMPONENT clock_source
   GENERIC (
      PhaseDelay   : delay_length := 20 ns;
      ClockPeriod  : delay_length := 40 ns;
      gJitterOn    : boolean      := true;
      gJitterDelay : real         := 7.0;
      gJitter_ps   : real         := 10.0
   );
   PORT (
      clk : BUFFER std_logic 
   );
   END COMPONENT;
   COMPONENT cpu_commands
   GENERIC (
      gCpuCommands3 : string := "bus.txt";
      gCpuLog3      : string := "log.txt"
   );
   PORT (
      cpu_DataOut : IN     std_logic_vector (15 DOWNTO 0);
      cpu_Addr    : OUT    std_logic_vector (0 TO 15);
      cpu_DataIn  : OUT    std_logic_vector (15 DOWNTO 0);
      cpu_Rd      : OUT    std_logic ;
      cpu_Wr      : OUT    std_logic ;
      clk         : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT power_on_reset
   GENERIC (
      DelayLength : integer := 10
   );
   PORT (
      Clk    : IN     std_logic ;
      nReset : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT Mil1553
   PORT (
      Addr             : IN     std_logic_vector (15 DOWNTO 0);
      Cs               : IN     std_logic;
      DataIn           : IN     std_logic_vector (15 DOWNTO 0);
      InN              : IN     std_logic;
      InP              : IN     std_logic;
      MyRtAddr         : IN     std_logic_vector (4 DOWNTO 0);
      Rd               : IN     std_logic;
      ServiceReqVector : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest   : IN     std_logic;
      SubsystemFlag    : IN     std_logic;
      Wr               : IN     std_logic;
      clk              : IN     std_logic;
      nResetIn         : IN     std_logic;
      DataOut          : OUT    std_logic_vector (15 DOWNTO 0);
      DataValid        : OUT    std_logic;
      Intr             : OUT    std_logic;
      OutEn            : OUT    std_logic;
      OutN             : OUT    std_logic;
      OutP             : OUT    std_logic;
      Strobe           : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : clock_source USE ENTITY barij_lib.clock_source;
   FOR ALL : cpu_commands USE ENTITY barij_lib.cpu_commands;
   FOR ALL : Mil1553 USE ENTITY mil1553_lib.Mil1553;
   FOR ALL : power_on_reset USE ENTITY barij_lib.power_on_reset;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 2 eb2
   Cs <= '1'; 
   BC_Cs <= '1';  
   MyRtAddr   <= "10111";    
   MyBCAddr  <= "11110";                       


   -- Instance port mappings.
   U_1 : clock_source
      GENERIC MAP (
         PhaseDelay   => 2 ns,
         ClockPeriod  => 5 ns,
         gJitterOn    => false,
         gJitterDelay => 7.0,
         gJitter_ps   => 10.0
      )
      PORT MAP (
         clk => clk
      );
   BC_cpu_commands : cpu_commands
      GENERIC MAP (
         gCpuCommands3 => "BC_mil1553_cmds.txt",
         gCpuLog3      => "BC_mil1553_log.txt"
      )
      PORT MAP (
         cpu_DataOut => cpu_DataOut,
         cpu_Addr    => cpu_Addr,
         cpu_DataIn  => cpu_DataIn,
         cpu_Rd      => cpu_Rd,
         cpu_Wr      => cpu_Wr,
         clk         => clk
      );
   RT_cpu_commands : cpu_commands
      GENERIC MAP (
         gCpuCommands3 => "RT_mil1553_cmds.txt",
         gCpuLog3      => "RT_mil1553_log.txt"
      )
      PORT MAP (
         cpu_DataOut => DataOut,
         cpu_Addr    => Addr,
         cpu_DataIn  => DataIn,
         cpu_Rd      => Rd,
         cpu_Wr      => Wr,
         clk         => clk
      );
   U_2 : power_on_reset
      GENERIC MAP (
         DelayLength => 10
      )
      PORT MAP (
         Clk    => clk,
         nReset => nReset
      );
   BC : Mil1553
      PORT MAP (
         Addr             => cpu_Addr,
         Cs               => BC_Cs,
         DataIn           => cpu_DataIn,
         InN              => OutN,
         InP              => OutP,
         MyRtAddr         => MyBCAddr,
         Rd               => cpu_Rd,
         ServiceReqVector => ServiceReqVector,
         ServiceRequest   => ServiceRequest,
         SubsystemFlag    => SubsystemFlag,
         Wr               => cpu_Wr,
         clk              => clk,
         nResetIn         => nReset,
         DataOut          => cpu_DataOut,
         DataValid        => OPEN,
         Intr             => OPEN,
         OutEn            => OPEN,
         OutN             => InN,
         OutP             => InP,
         Strobe           => OPEN
      );

END struct;
