-- VHDL Entity mil1553_tb.Mil1553_RT_tb.symbol
--
-- Created:
--          by - jean.UNKNOWN (DESKTOP-6AOI8L3)
--          at - 08:37:06 18/07/2021
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--


ENTITY Mil1553_RT_tb IS
-- Declarations

END Mil1553_RT_tb ;

--
-- VHDL Architecture mil1553_tb.Mil1553_RT_tb.struct
--
-- Created:
--          by - jean.UNKNOWN (DESKTOP-6AOI8L3)
--          at - 08:25:50 12/04/2022
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

LIBRARY mil1553_lib;
LIBRARY mil1553_tb;

ARCHITECTURE struct OF Mil1553_RT_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Addr             : std_logic_vector(15 DOWNTO 0);
   SIGNAL Cs               : std_logic;
   SIGNAL DataIn           : std_logic_vector(15 DOWNTO 0);
   SIGNAL DataOut          : std_logic_vector(15 DOWNTO 0);
   SIGNAL DataValid        : std_logic;
   SIGNAL InN              : std_logic;
   SIGNAL InP              : std_logic;
   SIGNAL Intr             : std_logic;
   SIGNAL MyRtAddr         : std_logic_vector(4 DOWNTO 0);
   SIGNAL OutEn            : std_logic;
   SIGNAL OutN             : std_logic;
   SIGNAL OutP             : std_logic;
   SIGNAL Rd               : std_logic;
   SIGNAL ServiceReqVector : std_logic_vector(15 DOWNTO 0);
   SIGNAL ServiceRequest   : std_logic;
   SIGNAL Strobe           : std_logic;
   SIGNAL SubsystemFlag    : std_logic;
   SIGNAL Wr               : std_logic;
   SIGNAL clk              : std_logic;
   SIGNAL nReset           : std_logic;


   -- Component Declarations
   COMPONENT Mil1553
   PORT (
      Addr             : IN     std_logic_vector (15 DOWNTO 0);
      Cs               : IN     std_logic;
      DataIn           : IN     std_logic_vector (15 DOWNTO 0);
      InN              : IN     std_logic;
      InP              : IN     std_logic;
      MyRtAddr         : IN     std_logic_vector (4 DOWNTO 0);
      Rd               : IN     std_logic;
      ServiceReqVector : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest   : IN     std_logic;
      SubsystemFlag    : IN     std_logic;
      Wr               : IN     std_logic;
      clk              : IN     std_logic;
      nResetIn         : IN     std_logic;
      DataOut          : OUT    std_logic_vector (15 DOWNTO 0);
      DataValid        : OUT    std_logic;
      Intr             : OUT    std_logic;
      OutEn            : OUT    std_logic;
      OutN             : OUT    std_logic;
      OutP             : OUT    std_logic;
      Strobe           : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT Mil1553_RT_tester
   PORT (
      DataOut          : IN     std_logic_vector (15 DOWNTO 0);
      DataValid        : IN     std_logic ;
      Intr             : IN     std_logic ;
      OutEn            : IN     std_logic ;
      OutN             : IN     std_logic ;
      OutP             : IN     std_logic ;
      ServiceReqVector : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest   : IN     std_logic ;
      Strobe           : IN     std_logic ;
      SubsystemFlag    : IN     std_logic ;
      Addr             : OUT    std_logic_vector (15 DOWNTO 0);
      Cs               : OUT    std_logic ;
      DataIn           : OUT    std_logic_vector (15 DOWNTO 0);
      InN              : OUT    std_logic ;
      InP              : OUT    std_logic ;
      Rd               : OUT    std_logic ;
      Wr               : OUT    std_logic ;
      MyRtAddr         : BUFFER std_logic_vector (4 DOWNTO 0);
      clk              : BUFFER std_logic ;
      nReset           : BUFFER std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : Mil1553 USE ENTITY mil1553_lib.Mil1553;
   FOR ALL : Mil1553_RT_tester USE ENTITY mil1553_tb.Mil1553_RT_tester;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1            
   SubsystemFlag <= '0';
   ServiceReqVector <= X"AAAA";
   ServiceRequest <= '0';                            


   -- Instance port mappings.
   U_0 : Mil1553
      PORT MAP (
         Addr             => Addr,
         Cs               => Cs,
         DataIn           => DataIn,
         InN              => InN,
         InP              => InP,
         MyRtAddr         => MyRtAddr,
         Rd               => Rd,
         ServiceReqVector => ServiceReqVector,
         ServiceRequest   => ServiceRequest,
         SubsystemFlag    => SubsystemFlag,
         Wr               => Wr,
         clk              => clk,
         nResetIn         => nReset,
         DataOut          => DataOut,
         DataValid        => DataValid,
         Intr             => Intr,
         OutEn            => OutEn,
         OutN             => OutN,
         OutP             => OutP,
         Strobe           => Strobe
      );
   U_1 : Mil1553_RT_tester
      PORT MAP (
         DataOut          => DataOut,
         DataValid        => DataValid,
         Intr             => Intr,
         OutEn            => OutEn,
         OutN             => OutN,
         OutP             => OutP,
         ServiceReqVector => ServiceReqVector,
         ServiceRequest   => ServiceRequest,
         Strobe           => Strobe,
         SubsystemFlag    => SubsystemFlag,
         Addr             => Addr,
         Cs               => Cs,
         DataIn           => DataIn,
         InN              => InN,
         InP              => InP,
         Rd               => Rd,
         Wr               => Wr,
         MyRtAddr         => MyRtAddr,
         clk              => clk,
         nReset           => nReset
      );

END struct;
