	nios_conv_usb_1553 u0 (
		.clk_clk                      (<connected-to-clk_clk>),                      //              clk.clk
		.clk_50_clk                   (<connected-to-clk_50_clk>),                   //           clk_50.clk
		.conv_registers_waitrequest   (<connected-to-conv_registers_waitrequest>),   //   conv_registers.waitrequest
		.conv_registers_readdata      (<connected-to-conv_registers_readdata>),      //                 .readdata
		.conv_registers_readdatavalid (<connected-to-conv_registers_readdatavalid>), //                 .readdatavalid
		.conv_registers_burstcount    (<connected-to-conv_registers_burstcount>),    //                 .burstcount
		.conv_registers_writedata     (<connected-to-conv_registers_writedata>),     //                 .writedata
		.conv_registers_address       (<connected-to-conv_registers_address>),       //                 .address
		.conv_registers_write         (<connected-to-conv_registers_write>),         //                 .write
		.conv_registers_read          (<connected-to-conv_registers_read>),          //                 .read
		.conv_registers_byteenable    (<connected-to-conv_registers_byteenable>),    //                 .byteenable
		.conv_registers_debugaccess   (<connected-to-conv_registers_debugaccess>),   //                 .debugaccess
		.discrete_inputs_export       (<connected-to-discrete_inputs_export>),       //  discrete_inputs.export
		.discrete_outputs_export      (<connected-to-discrete_outputs_export>),      // discrete_outputs.export
		.irq_export                   (<connected-to-irq_export>),                   //              irq.export
		.mil1553_waitrequest          (<connected-to-mil1553_waitrequest>),          //          mil1553.waitrequest
		.mil1553_readdata             (<connected-to-mil1553_readdata>),             //                 .readdata
		.mil1553_readdatavalid        (<connected-to-mil1553_readdatavalid>),        //                 .readdatavalid
		.mil1553_burstcount           (<connected-to-mil1553_burstcount>),           //                 .burstcount
		.mil1553_writedata            (<connected-to-mil1553_writedata>),            //                 .writedata
		.mil1553_address              (<connected-to-mil1553_address>),              //                 .address
		.mil1553_write                (<connected-to-mil1553_write>),                //                 .write
		.mil1553_read                 (<connected-to-mil1553_read>),                 //                 .read
		.mil1553_byteenable           (<connected-to-mil1553_byteenable>),           //                 .byteenable
		.mil1553_debugaccess          (<connected-to-mil1553_debugaccess>),          //                 .debugaccess
		.reset_reset_n                (<connected-to-reset_reset_n>),                //            reset.reset_n
		.reset_50_reset_n             (<connected-to-reset_50_reset_n>),             //         reset_50.reset_n
		.uart1_waitrequest            (<connected-to-uart1_waitrequest>),            //            uart1.waitrequest
		.uart1_readdata               (<connected-to-uart1_readdata>),               //                 .readdata
		.uart1_readdatavalid          (<connected-to-uart1_readdatavalid>),          //                 .readdatavalid
		.uart1_burstcount             (<connected-to-uart1_burstcount>),             //                 .burstcount
		.uart1_writedata              (<connected-to-uart1_writedata>),              //                 .writedata
		.uart1_address                (<connected-to-uart1_address>),                //                 .address
		.uart1_write                  (<connected-to-uart1_write>),                  //                 .write
		.uart1_read                   (<connected-to-uart1_read>),                   //                 .read
		.uart1_byteenable             (<connected-to-uart1_byteenable>),             //                 .byteenable
		.uart1_debugaccess            (<connected-to-uart1_debugaccess>),            //                 .debugaccess
		.uart2_waitrequest            (<connected-to-uart2_waitrequest>),            //            uart2.waitrequest
		.uart2_readdata               (<connected-to-uart2_readdata>),               //                 .readdata
		.uart2_readdatavalid          (<connected-to-uart2_readdatavalid>),          //                 .readdatavalid
		.uart2_burstcount             (<connected-to-uart2_burstcount>),             //                 .burstcount
		.uart2_writedata              (<connected-to-uart2_writedata>),              //                 .writedata
		.uart2_address                (<connected-to-uart2_address>),                //                 .address
		.uart2_write                  (<connected-to-uart2_write>),                  //                 .write
		.uart2_read                   (<connected-to-uart2_read>),                   //                 .read
		.uart2_byteenable             (<connected-to-uart2_byteenable>),             //                 .byteenable
		.uart2_debugaccess            (<connected-to-uart2_debugaccess>)             //                 .debugaccess
	);

