-- VHDL Entity mil1553_lib.man_dec_fsm.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (jeansmithE313)
--          at - 19:29:54 20/09/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY man_dec_fsm IS
   GENERIC( 
      gBitFreq1    : natural := 100000000;
      gClkInFreq1  : natural := 100000000;
      gOverSample1 : natural := 4
   );
   PORT( 
      Clk          : IN     std_logic;
      ERP_tmr      : IN     std_logic;
      NegEdge      : IN     std_logic;
      PosEdge      : IN     std_logic;
      SyncOutN     : IN     std_logic;
      SyncOutP     : IN     std_logic;
      TxWord       : IN     std_logic_vector (16 DOWNTO 0);
      nReset       : IN     std_logic;
      CmdEdge      : OUT    std_logic;
      Cmd_nData    : OUT    std_logic;
      DecoderErr   : OUT    std_logic;
      EarlyReplyRx : OUT    std_logic;
      Err_Noise    : OUT    integer;
      NewWord      : OUT    std_logic;
      OutWord      : OUT    std_logic_vector (15 DOWNTO 0);
      SyncNegEdge  : OUT    std_logic;
      SyncPosEdge  : OUT    std_logic
   );

-- Declarations

END man_dec_fsm ;

--
-- VHDL Architecture mil1553_lib.man_dec_fsm.fsm
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 21:27:45 02/16/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
 
ARCHITECTURE fsm OF man_dec_fsm IS

   -- Architecture Declarations
   constant PreLoad : integer := (gClkInFreq1 / gBitFreq1)/2-1;
   constant SyncPreLoad : integer := 165;
   constant CmdSyncHighPreLoad : integer := 240;
   constant SamplePreLoad : integer := 65;
   constant SamplePreLoadHalf : integer := 50;
   signal ShiftReg : std_logic_vector(5 downto 0);
   signal Count : integer range 0 to SyncPreload;
   signal BitCount : integer range 0 to 19;
   signal HalfBitCount : integer range 0 to 79;
   signal SampleCount : integer range 0 to CmdSyncHighPreLoad;
   signal DataWord : std_logic_vector(16 downto 0);
   signal DataWordN : std_logic_vector(79 downto 0);
   signal CalcParity : std_logic;
   signal RxParity : std_logic;
   signal ExpParity : std_logic;
   signal ParityErrCnt : integer range 0 to 65535;
      procedure IncrErrCnt(signal Counter : inout integer range 0 to 65535)is
      begin
        if (Counter < 65535) then
          Counter <= Counter + 1;
        end if;  
      end procedure;

   TYPE STATE_TYPE IS (
      sBusIdle,
      sCheckCmdSyncLow,
      sGet0Low,
      sGet0High,
      sCheckParityLow,
      sCheckCmdSyncHigh,
      sGet1High,
      sGet1Low,
      sCheckDatSyncLow,
      sCheckDatSyncHigh,
      sCheckParityHigh,
      sParErr1,
      sTimeout
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;
   -- pragma synthesis_off
   SIGNAL hds_next,hds_current,hds_clock: INTEGER;
   -- pragma synthesis_on

   -- Declare any pre-registered internal signals
   SIGNAL CmdEdge_cld : std_logic ;
   SIGNAL Cmd_nData_cld : std_logic ;
   SIGNAL DecoderErr_cld : std_logic ;
   SIGNAL EarlyReplyRx_cld : std_logic ;
   SIGNAL NewWord_cld : std_logic ;
   SIGNAL OutWord_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL SyncNegEdge_cld : std_logic ;
   SIGNAL SyncPosEdge_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      Clk,
      nReset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (nReset = '0') THEN
         current_state <= sBusIdle;
         -- Default Reset Values
         CmdEdge_cld <= '0';
         Cmd_nData_cld <= '0';
         DecoderErr_cld <= '0';
         EarlyReplyRx_cld <= '0';
         NewWord_cld <= '0';
         OutWord_cld <= (others => '1');
         SyncNegEdge_cld <= '0';
         SyncPosEdge_cld <= '0';
         BitCount <= 0;
         CalcParity <= '1';
         Count <= 0;
         DataWord <= (others => '0');
         DataWordN <= (others => '0');
         ExpParity <= '0';
         HalfBitCount <= 0;
         RxParity <= '0';
         SampleCount <= 0;
         ShiftReg <= (others => '0');
         -- pragma synthesis_off
         hds_current <= 0;
         -- pragma synthesis_on
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         current_state <= next_state;
         -- pragma synthesis_off
         hds_current <= hds_next;
         hds_clock <= -1;
         hds_clock <= 0;
         -- pragma synthesis_on
         -- Default Assignment To Internals
         CmdEdge_cld <= '0';
         DecoderErr_cld <= '0';
         NewWord_cld <= '0';
         SyncNegEdge_cld <= '0';
         SyncPosEdge_cld <= '0';

         -- Combined Actions
         CASE current_state IS
            WHEN sBusIdle => 
               EarlyReplyRx_cld <= '0';
               IF (PosEdge = '1') THEN 
                  SampleCount <= CmdSyncHighPreLoad;
                  if (ERP_tmr = '0') then
                    EarlyReplyRx_cld <= '1';
                  end if;
               END IF;
            WHEN sCheckCmdSyncLow => 
               IF (PosEdge = '1') THEN 
                  SampleCount <= SamplePreload;
                  BitCount <= 15;
                  CalcParity <= '0';
               ELSIF (SampleCount = 0) THEN 
                  SampleCount <= SamplePreload;
                  BitCount <= 15;
                  CalcParity <= '1';
               ELSIF (SampleCount > 0) THEN 
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sGet0Low => 
               IF (PosEdge = '1') THEN 
                  SampleCount <= SamplePreload;
               ELSIF (SampleCount = 0) THEN 
                  if (Cmd_nData_cld = '0') then
                   DecoderErr_cld <= '1';
                  end if;
               ELSE
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sGet0High => 
               IF (NegEdge = '1' and SampleCount > 40) THEN 
                  if (Cmd_nData_cld = '0') then
                   DecoderErr_cld <= '1';
                  end if;
               ELSIF (BitCount = 0 and NegEdge = '1') THEN 
                  SampleCount <= SamplePreLoad;
                  OutWord_cld(BitCount) <= '0';
                  RxParity <= '0';
                  DecoderErr_cld <= '0';
               ELSIF (NegEdge = '1') THEN 
                  SampleCount <= SamplePreload;
                  OutWord_cld(BitCount) <= '0';
                  BitCount <= BitCount -1;
               ELSIF (BitCount = 0 and SampleCount = 0) THEN 
                  SampleCount <= SamplePreLoad;
                  OutWord_cld(BitCount) <= '0';
                  RxParity <= '1';
                  DecoderErr_cld <= '0';
               ELSIF (SampleCount = 0) THEN 
                  SampleCount <= SamplePreload -15;
                  OutWord_cld(BitCount) <= '0';
                  BitCount <= BitCount -1;
                  CalcParity <= not CalcParity;
               ELSE
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sCheckParityLow => 
               IF (PosEdge = '1' and RxParity = '0') THEN 
                  SampleCount <= SamplePreload;
                  DecoderErr_cld <= '0';
               ELSIF (CalcParity = RxParity and SampleCount = 0 and SyncOutP = '0' and RxParity = '1') THEN 
                  NewWord_cld <= '1';
                  SampleCount <= SyncPreload;
               ELSIF (CalcParity = RxParity and SampleCount = 0 and SyncOutP = '1') THEN 
                  NewWord_cld <= '1';
                  SampleCount <= CmdSyncHighPreLoad;
               ELSIF (SampleCount = 0) THEN 
                  if (CalcParity /= RxParity) then
                    IncrErrCnt(ParityErrCnt);
                    if (Cmd_nData_cld = '0') then
                      DecoderErr_cld <= '1';
                    end if;
                  end if;
               ELSE
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sCheckCmdSyncHigh => 
               IF (NegEdge = '1' and SampleCount > 121) THEN 
                  SampleCount <= SyncPreLoad;
               ELSIF (SampleCount = 0) THEN 
                  DecoderErr_cld <= '1';
                  SampleCount <= SyncPreLoad;
               ELSIF (NegEdge = '1') THEN 
                  SampleCount <= SyncPreLoad;
                  Cmd_nData_cld <= '1';
                  CmdEdge_cld <= '1';
                  SyncNegEdge_cld <= '1';
               ELSIF (SampleCount > 0) THEN 
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sGet1High => 
               IF (NegEdge = '1' and SampleCount > 45) THEN 
                  if (Cmd_nData_cld = '0') then
                   DecoderErr_cld <= '1';
                  end if;
               ELSIF (NegEdge = '1') THEN 
                  SampleCount <= SamplePreload;
               ELSIF (SampleCount = 0) THEN 
                  if (Cmd_nData_cld = '0') then
                   DecoderErr_cld <= '1';
                  end if;
               ELSE
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sGet1Low => 
               IF (BitCount = 0 and PosEdge = '1') THEN 
                  SampleCount <= SamplePreLoad;
                  OutWord_cld(BitCount) <= '1';
                  RxParity <= '1';
                  DecoderErr_cld <= '0';
               ELSIF (BitCount = 0 and SampleCount = 0) THEN 
                  SampleCount <= SamplePreload;
                  OutWord_cld(BitCount) <= '1';
                  RxParity <= '0';
                  DecoderErr_cld <= '0';
               ELSIF (PosEdge = '1') THEN 
                  SampleCount <= SamplePreload;
                  OutWord_cld(BitCount) <= '1';
                  CalcParity <=not CalcParity;
                  BitCount <= BitCount -1;
               ELSIF (PosEdge = '1' and SampleCount > 40) THEN 
                  if (Cmd_nData_cld = '0') then
                   DecoderErr_cld <= '1';
                  end if;
               ELSIF (SampleCount = 0) THEN 
                  SampleCount <= SamplePreload;
                  OutWord_cld(BitCount) <= '1';
                  BitCount <= BitCount -1;
               ELSE
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sCheckDatSyncLow => 
               IF (PosEdge = '1' and SampleCount > 40) THEN 
                  DecoderErr_cld <= '1';
               ELSIF (PosEdge = '1') THEN 
                  SampleCount <= SyncPreload;
                  Cmd_nData_cld <= '0';
                  SyncPosEdge_cld <= '1';
               ELSIF (SampleCount = 0) THEN 
               ELSE
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sCheckDatSyncHigh => 
               IF (NegEdge = '1' and SampleCount > 40) THEN 
               ELSIF (NegEdge = '1') THEN 
                  SampleCount <= SamplePreload;
                  BitCount <= 15;
                  CalcParity <= '1';
               ELSIF (SampleCount = 0) THEN 
                  SampleCount <= SamplePreload;
                  BitCount <= 15;
                  CalcParity <= '0';
               ELSE
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN sCheckParityHigh => 
               IF (CalcParity = RxParity and NegEdge = '1' and RxParity = '0') THEN 
                  NewWord_cld <= '1';
                  SampleCount <= SyncPreload;
               ELSIF (CalcParity = RxParity and SampleCount = 0 and SyncOutP = '1') THEN 
                  NewWord_cld <= '1';
                  SampleCount <= CmdSyncHighPreLoad;
               ELSIF ((SampleCount = 0) or (NegEdge = '1' and RxParity = '0')) THEN 
                  IncrErrCnt(ParityErrCnt);
                  if (Cmd_nData_cld = '0') then
                   DecoderErr_cld <= '1';
                  end if;
               ELSIF (CalcParity = RxParity and NegEdge = '1' and RxParity = '1') THEN 
                  SampleCount <= SamplePreload;
                  DecoderErr_cld <= '0';
               ELSE
                  SampleCount  <= SampleCount  -1;
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      BitCount,
      CalcParity,
      NegEdge,
      PosEdge,
      RxParity,
      SampleCount,
      SyncOutP,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN sBusIdle => 
            IF (PosEdge = '1') THEN 
               next_state <= sCheckCmdSyncHigh;
               -- pragma synthesis_off
               hds_next <= 1;
               -- pragma synthesis_on
            ELSE
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 0;
               -- pragma synthesis_on
            END IF;
         WHEN sCheckCmdSyncLow => 
            IF (PosEdge = '1') THEN 
               next_state <= sGet1High;
               -- pragma synthesis_off
               hds_next <= 2;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sGet0Low;
               -- pragma synthesis_off
               hds_next <= 3;
               -- pragma synthesis_on
            ELSIF (SampleCount > 0) THEN 
               next_state <= sCheckCmdSyncLow;
               -- pragma synthesis_off
               hds_next <= 4;
               -- pragma synthesis_on
            ELSE
               next_state <= sCheckCmdSyncLow;
               -- pragma synthesis_off
               hds_next <= 0;
               -- pragma synthesis_on
            END IF;
         WHEN sGet0Low => 
            IF (PosEdge = '1') THEN 
               next_state <= sGet0High;
               -- pragma synthesis_off
               hds_next <= 5;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 6;
               -- pragma synthesis_on
            ELSE
               next_state <= sGet0Low;
               -- pragma synthesis_off
               hds_next <= 7;
               -- pragma synthesis_on
            END IF;
         WHEN sGet0High => 
            IF (NegEdge = '1' and SampleCount > 40) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 8;
               -- pragma synthesis_on
            ELSIF (BitCount = 0 and NegEdge = '1') THEN 
               next_state <= sCheckParityLow;
               -- pragma synthesis_off
               hds_next <= 9;
               -- pragma synthesis_on
            ELSIF (NegEdge = '1') THEN 
               next_state <= sGet0Low;
               -- pragma synthesis_off
               hds_next <= 10;
               -- pragma synthesis_on
            ELSIF (BitCount = 0 and SampleCount = 0) THEN 
               next_state <= sCheckParityHigh;
               -- pragma synthesis_off
               hds_next <= 11;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sGet1High;
               -- pragma synthesis_off
               hds_next <= 12;
               -- pragma synthesis_on
            ELSE
               next_state <= sGet0High;
               -- pragma synthesis_off
               hds_next <= 13;
               -- pragma synthesis_on
            END IF;
         WHEN sCheckParityLow => 
            IF (PosEdge = '1' and RxParity = '0') THEN 
               next_state <= sCheckParityHigh;
               -- pragma synthesis_off
               hds_next <= 14;
               -- pragma synthesis_on
            ELSIF (CalcParity = RxParity and SampleCount = 0 and SyncOutP = '0' and RxParity = '1') THEN 
               next_state <= sCheckDatSyncLow;
               -- pragma synthesis_off
               hds_next <= 15;
               -- pragma synthesis_on
            ELSIF (CalcParity = RxParity and SampleCount = 0 and SyncOutP = '1') THEN 
               next_state <= sCheckCmdSyncHigh;
               -- pragma synthesis_off
               hds_next <= 16;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sTimeout;
               -- pragma synthesis_off
               hds_next <= 17;
               -- pragma synthesis_on
            ELSE
               next_state <= sCheckParityLow;
               -- pragma synthesis_off
               hds_next <= 18;
               -- pragma synthesis_on
            END IF;
         WHEN sCheckCmdSyncHigh => 
            IF (NegEdge = '1' and SampleCount > 121) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 19;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 20;
               -- pragma synthesis_on
            ELSIF (NegEdge = '1') THEN 
               next_state <= sCheckCmdSyncLow;
               -- pragma synthesis_off
               hds_next <= 21;
               -- pragma synthesis_on
            ELSIF (SampleCount > 0) THEN 
               next_state <= sCheckCmdSyncHigh;
               -- pragma synthesis_off
               hds_next <= 22;
               -- pragma synthesis_on
            ELSE
               next_state <= sCheckCmdSyncHigh;
               -- pragma synthesis_off
               hds_next <= 0;
               -- pragma synthesis_on
            END IF;
         WHEN sGet1High => 
            IF (NegEdge = '1' and SampleCount > 45) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 23;
               -- pragma synthesis_on
            ELSIF (NegEdge = '1') THEN 
               next_state <= sGet1Low;
               -- pragma synthesis_off
               hds_next <= 24;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 25;
               -- pragma synthesis_on
            ELSE
               next_state <= sGet1High;
               -- pragma synthesis_off
               hds_next <= 26;
               -- pragma synthesis_on
            END IF;
         WHEN sGet1Low => 
            IF (BitCount = 0 and PosEdge = '1') THEN 
               next_state <= sCheckParityHigh;
               -- pragma synthesis_off
               hds_next <= 27;
               -- pragma synthesis_on
            ELSIF (BitCount = 0 and SampleCount = 0) THEN 
               next_state <= sCheckParityLow;
               -- pragma synthesis_off
               hds_next <= 28;
               -- pragma synthesis_on
            ELSIF (PosEdge = '1') THEN 
               next_state <= sGet1High;
               -- pragma synthesis_off
               hds_next <= 29;
               -- pragma synthesis_on
            ELSIF (PosEdge = '1' and SampleCount > 40) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 30;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sGet0Low;
               -- pragma synthesis_off
               hds_next <= 31;
               -- pragma synthesis_on
            ELSE
               next_state <= sGet1Low;
               -- pragma synthesis_off
               hds_next <= 32;
               -- pragma synthesis_on
            END IF;
         WHEN sCheckDatSyncLow => 
            IF (PosEdge = '1' and SampleCount > 40) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 33;
               -- pragma synthesis_on
            ELSIF (PosEdge = '1') THEN 
               next_state <= sCheckDatSyncHigh;
               -- pragma synthesis_off
               hds_next <= 34;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 35;
               -- pragma synthesis_on
            ELSE
               next_state <= sCheckDatSyncLow;
               -- pragma synthesis_off
               hds_next <= 36;
               -- pragma synthesis_on
            END IF;
         WHEN sCheckDatSyncHigh => 
            IF (NegEdge = '1' and SampleCount > 40) THEN 
               next_state <= sBusIdle;
               -- pragma synthesis_off
               hds_next <= 37;
               -- pragma synthesis_on
            ELSIF (NegEdge = '1') THEN 
               next_state <= sGet0Low;
               -- pragma synthesis_off
               hds_next <= 38;
               -- pragma synthesis_on
            ELSIF (SampleCount = 0) THEN 
               next_state <= sGet1High;
               -- pragma synthesis_off
               hds_next <= 39;
               -- pragma synthesis_on
            ELSE
               next_state <= sCheckDatSyncHigh;
               -- pragma synthesis_off
               hds_next <= 40;
               -- pragma synthesis_on
            END IF;
         WHEN sCheckParityHigh => 
            IF (CalcParity = RxParity and NegEdge = '1' and RxParity = '0') THEN 
               next_state <= sCheckDatSyncLow;
               -- pragma synthesis_off
               hds_next <= 41;
               -- pragma synthesis_on
            ELSIF (CalcParity = RxParity and SampleCount = 0 and SyncOutP = '1') THEN 
               next_state <= sCheckCmdSyncHigh;
               -- pragma synthesis_off
               hds_next <= 42;
               -- pragma synthesis_on
            ELSIF ((SampleCount = 0) or (NegEdge = '1' and RxParity = '0')) THEN 
               next_state <= sParErr1;
               -- pragma synthesis_off
               hds_next <= 43;
               -- pragma synthesis_on
            ELSIF (CalcParity = RxParity and NegEdge = '1' and RxParity = '1') THEN 
               next_state <= sCheckParityLow;
               -- pragma synthesis_off
               hds_next <= 44;
               -- pragma synthesis_on
            ELSE
               next_state <= sCheckParityHigh;
               -- pragma synthesis_off
               hds_next <= 45;
               -- pragma synthesis_on
            END IF;
         WHEN sParErr1 => 
            next_state <= sBusIdle;
            -- pragma synthesis_off
            hds_next <= 46;
            -- pragma synthesis_on
         WHEN sTimeout => 
            next_state <= sBusIdle;
            -- pragma synthesis_off
            hds_next <= 47;
            -- pragma synthesis_on
         WHEN OTHERS =>
            next_state <= sBusIdle;
            -- pragma synthesis_off
            hds_next <= 0;
            -- pragma synthesis_on
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      Cmd_nData_cld,
      NegEdge,
      SampleCount,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      Err_Noise <= 0;

      -- Combined Actions
      CASE current_state IS
         WHEN sCheckCmdSyncHigh => 
            IF (NegEdge = '1' and SampleCount > 121) THEN 
               if (Cmd_nData_cld = '0') then
                --DecoderErr_cld <= '1';
               end if;
            END IF;
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   CmdEdge <= CmdEdge_cld;
   Cmd_nData <= Cmd_nData_cld;
   DecoderErr <= DecoderErr_cld;
   EarlyReplyRx <= EarlyReplyRx_cld;
   NewWord <= NewWord_cld;
   OutWord <= OutWord_cld;
   SyncNegEdge <= SyncNegEdge_cld;
   SyncPosEdge <= SyncPosEdge_cld;
END fsm;
