-- VHDL Entity mil1553_lib.manchester_decoder.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (jeansmithE313)
--          at - 14:38:07 05/03/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY manchester_decoder IS
   GENERIC( 
      gBitFreq    : natural := 1000000;
      gClkInFreq  : natural := 100000000;
      gOverSample : natural := 4
   );
   PORT( 
      BlankDecoder : IN     std_logic;
      Clk          : IN     std_logic;
      ClrNoiseErr  : IN     std_logic;
      ClrParityErr : IN     std_logic;
      ERP_tmr      : IN     std_logic;
      InN          : IN     std_logic;
      InP          : IN     std_logic;
      nReset       : IN     std_logic;
      CmdEdge      : OUT    std_logic;
      Cmd_nData    : OUT    std_logic;
      DecoderErr   : OUT    std_logic;
      EarlyReplyRx : OUT    std_logic;
      Err_Noise    : OUT    integer;
      NewWord      : OUT    std_logic;
      OutWord      : OUT    std_logic_vector (15 DOWNTO 0);
      ParityErrCnt : OUT    integer;
      SyncPosEdge  : OUT    std_logic
   );

-- Declarations

END manchester_decoder ;

-- VHDL Architecture mil1553_lib.manchester_decoder.struct
-- *********************************************************************************************************************
-- Company:         Al Tariq, Abu Dhabi
-- Created by:       jeansmith.UNKNOWN (jeansmithE313)
-- Date:                14:38:07 05/03/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
-- *********************************************************************************************************************
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY at_gen_lib;
LIBRARY mil1553_lib;

ARCHITECTURE struct OF manchester_decoder IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL NegEdge     : std_logic;
   SIGNAL PosEdge     : std_logic;
   SIGNAL RegN        : std_logic_vector(1 DOWNTO 0);
   SIGNAL RegP        : std_logic_vector(1 DOWNTO 0);
   SIGNAL SyncNegEdge : std_logic;
   SIGNAL SyncOut     : std_logic;
   SIGNAL SyncOutN    : std_logic;
   SIGNAL SyncOutP    : std_logic;
   SIGNAL TxWord      : std_logic_vector(16 DOWNTO 0);
   SIGNAL nSyncOutP   : std_logic;


   -- Component Declarations
   COMPONENT synchroniser
   PORT (
      AsyncIn : IN     std_logic ;
      clk     : IN     std_logic ;
      nReset  : IN     std_logic ;
      SyncOut : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT man_dec_fsm
   GENERIC (
      gBitFreq1    : natural := 100000000;
      gClkInFreq1  : natural := 100000000;
      gOverSample1 : natural := 4
   );
   PORT (
      Clk          : IN     std_logic ;
      ERP_tmr      : IN     std_logic ;
      NegEdge      : IN     std_logic ;
      PosEdge      : IN     std_logic ;
      SyncOutN     : IN     std_logic ;
      SyncOutP     : IN     std_logic ;
      TxWord       : IN     std_logic_vector (16 DOWNTO 0);
      nReset       : IN     std_logic ;
      CmdEdge      : OUT    std_logic ;
      Cmd_nData    : OUT    std_logic ;
      DecoderErr   : OUT    std_logic ;
      EarlyReplyRx : OUT    std_logic ;
      Err_Noise    : OUT    integer ;
      NewWord      : OUT    std_logic ;
      OutWord      : OUT    std_logic_vector (15 DOWNTO 0);
      SyncNegEdge  : OUT    std_logic ;
      SyncPosEdge  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : man_dec_fsm USE ENTITY mil1553_lib.man_dec_fsm;
   FOR ALL : synchroniser USE ENTITY at_gen_lib.synchroniser;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eInv1
   -- eInv1 1   
   nSyncOutP <= not SyncOutP;  
                              

   -- HDL Embedded Text Block 2 ebEdgeDetect
   -- ebEdgeDetect 2     
   process(nReset,Clk)
   begin
   if (nReset = '0') then
     PosEdge <= '0';
     NegEdge <= '0';
     RegN <= "11";
     RegP <= "00";
   elsif (clk'event and clk='1') then
     RegN <= RegN(0) & nSyncOutP;--used to be SyncOutN
     RegP <= RegP(0) & SyncOutP;
     NegEdge <= '0';
     PosEdge <= '0';
     if (RegP = "01" and RegN(0) = '0') then
       PosEdge <= '1';
     elsif (RegN = "01" and RegP(0) = '0') then
       NegEdge <= '1';
    -- elsif (RegP = "01" and RegN(1) = '1') then
   --    PosEdge <= '1';
    -- elsif (RegP = "10" and RegN(1) = '1') then
    --   NegEdge <= '1';
     end if;
   end if;
   end process;                                   

   -- HDL Embedded Text Block 3 ebBlankDecoder
   -- ebBlankDecoder 3   
   SyncOutP <= SyncOut when BlankDecoder = '0' else '0';                                     


   -- Instance port mappings.
   SyncInN : synchroniser
      PORT MAP (
         AsyncIn => InN,
         clk     => Clk,
         nReset  => nReset,
         SyncOut => SyncOutN
      );
   SyncInP : synchroniser
      PORT MAP (
         AsyncIn => InP,
         clk     => Clk,
         nReset  => nReset,
         SyncOut => SyncOut
      );
   man_dec_fsm1 : man_dec_fsm
      GENERIC MAP (
         gBitFreq1    => gBitFreq,
         gClkInFreq1  => gClkInFreq,
         gOverSample1 => gOverSample
      )
      PORT MAP (
         Clk          => Clk,
         ERP_tmr      => ERP_tmr,
         NegEdge      => NegEdge,
         PosEdge      => PosEdge,
         SyncOutN     => SyncOutN,
         SyncOutP     => SyncOutP,
         TxWord       => TxWord,
         nReset       => nReset,
         CmdEdge      => CmdEdge,
         Cmd_nData    => Cmd_nData,
         DecoderErr   => DecoderErr,
         EarlyReplyRx => EarlyReplyRx,
         Err_Noise    => Err_Noise,
         NewWord      => NewWord,
         OutWord      => OutWord,
         SyncNegEdge  => SyncNegEdge,
         SyncPosEdge  => SyncPosEdge
      );

END struct;
