-- VHDL Entity mil1553_lib.manchester_encoder.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (jeansmithE313)
--          at - 09:07:23 20/09/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY manchester_encoder IS
   GENERIC( 
      gClkInFreq : natural := 100000000;
      gBitFreq   : natural := 1000000
   );
   PORT( 
      Clk           : IN     std_logic;
      Cmd_nData     : IN     std_logic;
      Data          : IN     std_logic_vector (15 DOWNTO 0);
      Err_inj       : IN     std_logic_vector (15 DOWNTO 0);
      Go            : IN     std_logic;
      nReset        : IN     std_logic;
      tmr_Blank     : IN     std_logic;
      BlankStart    : OUT    std_logic;
      BlankStop     : OUT    std_logic;
      Done          : OUT    std_logic;
      LastBitEdge   : OUT    std_logic;
      OutEn         : OUT    std_logic;
      OutN          : OUT    std_logic;
      OutP          : OUT    std_logic;
      PulseBit      : OUT    std_logic;
      PulseWord     : OUT    std_logic;
      tmr_ERP_Reset : OUT    std_logic
   );

-- Declarations

END manchester_encoder ;

--
-- VHDL Architecture mil1553_lib.manchester_encoder.fsm
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 18:05:37 01/28/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
 
ARCHITECTURE fsm OF manchester_encoder IS

   -- Architecture Declarations
   constant PreLoad : integer := (gClkInFreq / gBitFreq)/2-1;
   constant SyncPreLoad : integer := (((gClkInFreq / gBitFreq)/2)*3)-1;
   signal Count : integer range 0 to SyncPreload;
   signal WordCount : integer range 0 to 64;
   signal BitCount : integer range 0 to 32;
   signal DataWord : std_logic_vector(15 downto 0);
   signal Parity : std_logic;
   signal inj_ParityError : std_logic;
   signal inj_WordLenError : std_logic;
   signal inj_WrdLoc : integer range 0 to 64;
   signal inj_BitLoc :std_logic_vector(5 downto 0);

   TYPE STATE_TYPE IS (
      sIdle,
      sSync0,
      sSync1,
      sParity1,
      sData0,
      sData1,
      sParity0,
      sLastBit0,
      sLastBit1,
      sBlank
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare any pre-registered internal signals
   SIGNAL BlankStart_cld : std_logic ;
   SIGNAL BlankStop_cld : std_logic ;
   SIGNAL Done_cld : std_logic ;
   SIGNAL LastBitEdge_cld : std_logic ;
   SIGNAL OutEn_cld : std_logic ;
   SIGNAL OutP_cld : std_logic ;
   SIGNAL PulseBit_cld : std_logic ;
   SIGNAL PulseWord_cld : std_logic ;
   SIGNAL tmr_ERP_Reset_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      Clk,
      nReset
   )
   -----------------------------------------------------------------
   variable TempBitCount : integer range 0 to 15;
   BEGIN
      IF (nReset = '0') THEN
         current_state <= sIdle;
         -- Default Reset Values
         BlankStart_cld <= '0';
         BlankStop_cld <= '0';
         Done_cld <= '0';
         LastBitEdge_cld <= '0';
         OutEn_cld <= '0';
         OutP_cld <= '0';
         PulseBit_cld <= '0';
         PulseWord_cld <= '0';
         tmr_ERP_Reset_cld <= '1';
         BitCount <= 0;
         Count <= 0;
         DataWord <= (others => '0');
         Parity <= '0';
         WordCount <= 0;
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         current_state <= next_state;
         -- Default Assignment To Internals
         BlankStart_cld <= '0';
         Done_cld <= '0';
         PulseBit_cld <= '0';
         PulseWord_cld <= '0';
         tmr_ERP_Reset_cld <= '0';

         -- Combined Actions
         CASE current_state IS
            WHEN sIdle => 
               IF (Go = '1') THEN 
                  OutP_cld <= Cmd_nData;
                  OutEn_cld <= '1';
                  Count <= SyncPreload;
                  BlankStop_cld <= '1';
                  BlankStart_cld <= '0';
                  if (inj_WordLenError = '1' and WordCount = inj_WrdLoc) then
                    if (err_inj(9) = '1') then
                      BitCount <= 15 - to_integer(unsigned(err_inj(8 downto 4)));
                    else
                      BitCount <= 15 + to_integer(unsigned(err_inj(8 downto 4)));
                    end if;
                  else
                    BitCount <= 15;
                  end if;
                  if (Cmd_nData = '1') then
                    WordCount <= 0;
                  --else
                  --  WordCount <= WordCount + 1;
                  end if;
                  DataWord <= Data;
                  Done_cld <= '0';
                  PulseWord_cld <= '1';
                  PulseBit_cld <= '1';
                  LastBitEdge_cld <= '0';
                  tmr_ERP_Reset_cld <= '1';
                  Parity <= not(Data(15) xor Data(14) xor 
                                  Data(13) xor Data(12) xor
                                  Data(11) xor Data(10) xor
                                  Data(9) xor Data(8) xor
                                  Data(7) xor Data(6) xor
                                  Data(5) xor Data(4) xor
                                  Data(3) xor Data(2) xor
                                  Data(1) xor Data(0));
               END IF;
            WHEN sSync0 => 
               IF (Count =0) THEN 
                  OutP_cld <= not Cmd_nData;
                  OutEn_cld <= '1';
                  Count <= SyncPreload;
                  PulseBit_cld <= '1';
               ELSE
                  Count <= Count -1;
               END IF;
            WHEN sSync1 => 
               IF (Count =0) THEN 
                  if (BitCount > 15) then 
                    TempBitCount := 15;
                  else
                   TempBitCount := BitCount;
                  end if;
                  OutP_cld <= DataWord(TempBitCount);
                  OutEn_cld <= '1';
                  Count <= Preload;
                  PulseBit_cld <= '1';
               ELSE
                  Count <= Count -1;
               END IF;
            WHEN sParity1 => 
               IF (Go = '1' and Count = 0) THEN 
                  OutP_cld <= Cmd_nData;
                  OutEn_cld <= '1';
                  Count <= SyncPreload;
                  if (inj_WordLenError = '1' and WordCount = inj_WrdLoc) then
                    if (err_inj(9) = '1') then
                      BitCount <= 15 - to_integer(unsigned(err_inj(8 downto 4)));
                    else
                      BitCount <= 15 + to_integer(unsigned(err_inj(8 downto 4)));
                    end if;
                  else
                    BitCount <= 15;
                  end if;
                  DataWord <= Data;
                  Done_cld <= '0';
                  PulseWord_cld <= '1';
                  PulseBit_cld <= '1';
                  LastBitEdge_cld <= '0';
                  tmr_ERP_Reset_cld <= '1';
                  Parity <= not (Data(15) xor Data(14) xor 
                                  Data(13) xor Data(12) xor
                                  Data(11) xor Data(10) xor
                                  Data(9) xor Data(8) xor
                                  Data(7) xor Data(6) xor
                                  Data(5) xor Data(4) xor
                                  Data(3) xor Data(2) xor
                                  Data(1) xor Data(0));
               ELSIF (Count =0) THEN 
                  OutP_cld <= '0';
                  -- delaying the OutEn_cld until GAP timer expires
                  OutEn_cld <= '0';
                  WordCount <= 0;
               ELSE
                  Count <= Count -1;
               END IF;
            WHEN sData0 => 
               IF (Count =0) THEN 
                  if (BitCount > 15) then 
                    TempBitCount := 15;
                  else
                   TempBitCount := BitCount;
                  end if;
                  OutP_cld <= not DataWord(TempBitCount);
                  OutEn_cld <= '1';
                  Count <= Preload;
                  BitCount <= BitCount -1;
                  PulseBit_cld <= '1';
               ELSE
                  Count <= Count -1;
               END IF;
            WHEN sData1 => 
               IF (Count =0 and Bitcount = 0) THEN 
                  OutP_cld <= DataWord(BitCount);
                  OutEn_cld <= '1';
                  Count <= Preload;
                  PulseBit_cld <= '1';
               ELSIF (Count =0) THEN 
                  if (BitCount > 15) then 
                    TempBitCount := 15;
                  else
                   TempBitCount := BitCount;
                  end if;
                  OutP_cld <= DataWord(TempBitCount);
                  OutEn_cld <= '1';
                  Count <= Preload;
                  PulseBit_cld <= '1';
               ELSE
                  Count <= Count -1;
               END IF;
            WHEN sParity0 => 
               IF (Count =0) THEN 
                  if (inj_ParityError = '1') and (WordCount = inj_WrdLoc) then 
                    OutP_cld <= Parity;
                  else
                    OutP_cld <= not Parity;
                  end if;
                  OutEn_cld <= '1';
                  Count <= Preload;
                  Done_cld <= '1';
                  PulseBit_cld <= '1';
                  BlankStart_cld <= '1';
                  BlankStop_cld <= '0';
                  LastBitEdge_cld <= '1';
                  WordCount <= WordCount + 1;
               ELSE
                  Count <= Count -1;
               END IF;
            WHEN sLastBit0 => 
               IF (Count =0) THEN 
                  OutP_cld <= not DataWord(BitCount);
                  OutEn_cld <= '1';
                  Count <= Preload;
                  PulseBit_cld <= '1';
               ELSE
                  Count <= Count -1;
               END IF;
            WHEN sLastBit1 => 
               IF (Count =0) THEN 
                  if (inj_ParityError = '1') and (WordCount = inj_WrdLoc) then 
                    OutP_cld <= not Parity;
                  else
                    OutP_cld <= Parity;
                  end if;
                  OutEn_cld <= '1';
                  Count <= Preload;
                  PulseBit_cld <= '1';
               ELSE
                  Count <= Count -1;
               END IF;
            WHEN sBlank => 
               IF (tmr_Blank = '1') THEN 
                  OutEn_cld <= '0';
                  BlankStop_cld <= '1';
                  BlankStart_cld <= '0';
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      BitCount,
      Count,
      Go,
      current_state,
      tmr_Blank
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN sIdle => 
            IF (Go = '1') THEN 
               next_state <= sSync0;
            ELSE
               next_state <= sIdle;
            END IF;
         WHEN sSync0 => 
            IF (Count =0) THEN 
               next_state <= sSync1;
            ELSE
               next_state <= sSync0;
            END IF;
         WHEN sSync1 => 
            IF (Count =0) THEN 
               next_state <= sData0;
            ELSE
               next_state <= sSync1;
            END IF;
         WHEN sParity1 => 
            IF (Go = '1' and Count = 0) THEN 
               next_state <= sSync0;
            ELSIF (Count =0) THEN 
               next_state <= sBlank;
            ELSE
               next_state <= sParity1;
            END IF;
         WHEN sData0 => 
            IF (Count =0) THEN 
               next_state <= sData1;
            ELSE
               next_state <= sData0;
            END IF;
         WHEN sData1 => 
            IF (Count =0 and Bitcount = 0) THEN 
               next_state <= sLastBit0;
            ELSIF (Count =0) THEN 
               next_state <= sData0;
            ELSE
               next_state <= sData1;
            END IF;
         WHEN sParity0 => 
            IF (Count =0) THEN 
               next_state <= sParity1;
            ELSE
               next_state <= sParity0;
            END IF;
         WHEN sLastBit0 => 
            IF (Count =0) THEN 
               next_state <= sLastBit1;
            ELSE
               next_state <= sLastBit0;
            END IF;
         WHEN sLastBit1 => 
            IF (Count =0) THEN 
               next_state <= sParity0;
            ELSE
               next_state <= sLastBit1;
            END IF;
         WHEN sBlank => 
            IF (tmr_Blank = '1') THEN 
               next_state <= sIdle;
            ELSE
               next_state <= sBlank;
            END IF;
         WHEN OTHERS =>
            next_state <= sIdle;
      END CASE;
   END PROCESS nextstate_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   BlankStart <= BlankStart_cld;
   BlankStop <= BlankStop_cld;
   Done <= Done_cld;
   LastBitEdge <= LastBitEdge_cld;
   OutEn <= OutEn_cld;
   OutP <= OutP_cld;
   PulseBit <= PulseBit_cld;
   PulseWord <= PulseWord_cld;
   tmr_ERP_Reset <= tmr_ERP_Reset_cld;
   OutN <= not OutP_cld when OutEn_cld = '1' else OutP_cld;
   inj_ParityError <= '1' when err_inj(3 downto 0) = "0001" else '0';
   inj_WordLenError <= '1' when err_inj(3 downto 0) = "0010" else '0';
   inj_WrdLoc <= to_integer(unsigned(err_inj(15 downto 10)));
   inj_BitLoc <= err_inj(9 downto 4);
END fsm;
