-- VHDL Entity mil1553_lib.mil1553_singlebus.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 17:16:09 01/28/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY mil1553_lib;
USE mil1553_lib.mil1553.ALL;

ENTITY mil1553_singlebus IS
   GENERIC( 
      CoreMode : core_mode_t := BCRT_MODE
   );
   PORT( 
      BIT1              : IN     std_logic_vector (15 DOWNTO 0);
      BroadcastEnable   : IN     std_logic;
      BusBusy           : IN     std_logic;
      Clear_InitiateBIT : IN     std_logic;
      Clear_Synchronize : IN     std_logic;
      CmdProcLen        : IN     std_logic_vector (15 DOWNTO 0);
      CmdProcStart      : IN     std_logic_vector (15 DOWNTO 0);
      DBC_Enable        : IN     std_logic;
      DataWrapSubAddr   : IN     std_logic_vector (4 DOWNTO 0);
      EnableHwDataWrap  : IN     std_logic;
      InN               : IN     std_logic;
      InP               : IN     std_logic;
      IsRT              : IN     std_logic;
      LegalModeBrdcst   : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeRx       : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeTx       : IN     std_logic_vector (31 DOWNTO 0);
      LegalSubAddr      : IN     std_logic_vector (31 DOWNTO 0);
      MyRtAddr          : IN     std_logic_vector (4 DOWNTO 0);
      MyRtAddrParity    : IN     std_logic;
      SendMessage       : IN     std_logic;
      ServiceReqVector  : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest    : IN     std_logic;
      SubsystemFlag     : IN     std_logic;
      TerminalFlagIn    : IN     std_logic;
      TxDataIn          : IN     std_logic_vector (16 DOWNTO 0);
      TxOffIn           : IN     std_logic;
      clk               : IN     std_logic;
      nReset            : IN     std_logic;
      reg_err_inj       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_1us       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_GAP       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_NRP       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_REP       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_SAF       : IN     std_logic_vector (15 DOWNTO 0);
      BusActive         : OUT    std_logic;
      BusReset_Rxed     : OUT    std_logic;
      CmdRxed           : OUT    std_logic_vector (15 DOWNTO 0);
      DBC_Accepted      : OUT    std_logic;
      DataReqFlag       : OUT    std_logic;
      DataRxedFlag      : OUT    std_logic;
      DataWrapActive    : OUT    std_logic;
      EarlyReplyRx      : OUT    std_logic;
      InitiateBIT_Rxed  : OUT    std_logic;
      ModeCmd           : OUT    std_logic_vector (15 DOWNTO 0);
      ModeData          : OUT    std_logic_vector (15 DOWNTO 0);
      NewModeCmd        : OUT    std_logic;
      OutEn             : OUT    std_logic;
      OutN              : OUT    std_logic;
      OutP              : OUT    std_logic;
      RxDataAddr        : OUT    std_logic_vector (9 DOWNTO 0);
      RxDataOut         : OUT    std_logic_vector (15 DOWNTO 0);
      RxDataWr          : OUT    std_logic;
      SelTxShutdown     : OUT    std_logic;
      ShutdownData      : OUT    std_logic_vector (4 DOWNTO 0);
      StatusRxed        : OUT    std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag    : OUT    std_logic;
      Strobe            : OUT    std_logic;
      Synchronize       : OUT    std_logic;
      TerminalFlag      : OUT    std_logic;
      TxAvail           : OUT    std_logic;
      TxDataAddr        : OUT    std_logic_vector (9 DOWNTO 0);
      TxOffOut          : OUT    std_logic;
      UnexpectedEdgeCnt : OUT    std_logic_vector (15 DOWNTO 0);
      tmr_GAP           : OUT    std_logic;
      tmr_NRP           : OUT    std_logic;
      tmr_REP           : OUT    std_logic;
      tmr_SAF           : OUT    std_logic
   );

-- Declarations

END mil1553_singlebus ;

-- VHDL Architecture mil1553_lib.mil1553_singlebus.struct
-- *********************************************************************************************************************
-- Company:         Al Tariq, Abu Dhabi
-- Created by:       jeansmith.UNKNOWN (jeansmithE313)
-- Date:                14:39:44 05/03/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
-- *********************************************************************************************************************
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY at_gen_lib;
LIBRARY mil1553_lib;

ARCHITECTURE struct OF mil1553_singlebus IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL BlankDecoder      : std_logic;
   SIGNAL BrdcstRxed        : std_logic;
   SIGNAL ClrNoiseErr       : std_logic;
   SIGNAL ClrParityErr      : std_logic;
   SIGNAL CmdEdge           : std_logic;
   SIGNAL Cmd_nData         : std_logic;
   SIGNAL Cmd_nDataIn       : std_logic;
   SIGNAL DataOut1          : std_logic_vector(15 DOWNTO 0);
   SIGNAL DecoderErr        : std_logic;
   SIGNAL Done              : std_logic;
   SIGNAL Encoder_ERP_Reset : std_logic;
   SIGNAL Instrumentation   : std_logic;
   SIGNAL LastBitEdge       : std_logic;
   SIGNAL NewWord           : std_logic;
   SIGNAL OutEn1            : std_logic;
   SIGNAL OutWord           : std_logic_vector(15 DOWNTO 0);
   SIGNAL SendWord          : std_logic;
   SIGNAL SyncPosEdge       : std_logic;
   SIGNAL nOutEn1           : std_logic;
   SIGNAL nResetEnc         : std_logic;
   SIGNAL nReset_Decoder    : std_logic;
   SIGNAL reg_tmr_ERP       : std_logic_vector(15 DOWNTO 0);
   SIGNAL rx_data           : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL rx_rdaddress      : STD_LOGIC_VECTOR(9 DOWNTO 0);
   SIGNAL tmr_1us           : std_logic;
   SIGNAL tmr_1us_Start     : std_logic;
   SIGNAL tmr_1us_Stop      : std_logic;
   SIGNAL tmr_25us          : std_logic;
   SIGNAL tmr_25us_Start    : std_logic;
   SIGNAL tmr_25us_Stop     : std_logic;
   SIGNAL tmr_Blank         : std_logic;
   SIGNAL tmr_Blank_Start   : std_logic;
   SIGNAL tmr_Blank_Stop    : std_logic;
   SIGNAL tmr_ERP           : std_logic;
   SIGNAL tmr_ERP_Reset     : std_logic;
   SIGNAL tmr_ERP_Stop      : std_logic;
   SIGNAL tmr_ERP_enable    : std_logic;
   SIGNAL tmr_GAP_Start     : std_logic;
   SIGNAL tmr_GAP_Stop      : std_logic;
   SIGNAL tmr_GAP_internal  : std_logic;
   SIGNAL tmr_NRP_Start     : std_logic;
   SIGNAL tmr_NRP_Start1    : std_logic;
   SIGNAL tmr_NRP_Stop      : std_logic;
   SIGNAL tmr_NRP_internal  : std_logic;
   SIGNAL tmr_REP_Start     : std_logic;
   SIGNAL tmr_REP_Stop      : std_logic;
   SIGNAL tmr_REP_internal  : std_logic;
   SIGNAL tmr_SAF_Start     : std_logic;
   SIGNAL tmr_SAF_Start1    : std_logic;
   SIGNAL tmr_SAF_Start2    : std_logic;
   SIGNAL tmr_SAF_Stop      : std_logic;
   SIGNAL tmr_SAF_internal  : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL TerminalFlag_internal : std_logic;


   -- Component Declarations
   COMPONENT edge_detect
   GENERIC (
      PulseWidth : integer := 65550
   );
   PORT (
      Clk    : IN     std_logic ;
      Edge   : IN     std_logic ;
      nReset : IN     std_logic ;
      Toggle : OUT    std_logic ;
      Pulse  : BUFFER std_logic 
   );
   END COMPONENT;
   COMPONENT manchester_decoder
   GENERIC (
      gBitFreq    : natural := 1000000;
      gClkInFreq  : natural := 100000000;
      gOverSample : natural := 4
   );
   PORT (
      BlankDecoder : IN     std_logic ;
      Clk          : IN     std_logic ;
      ClrNoiseErr  : IN     std_logic ;
      ClrParityErr : IN     std_logic ;
      ERP_tmr      : IN     std_logic ;
      InN          : IN     std_logic ;
      InP          : IN     std_logic ;
      nReset       : IN     std_logic ;
      CmdEdge      : OUT    std_logic ;
      Cmd_nData    : OUT    std_logic ;
      DecoderErr   : OUT    std_logic ;
      EarlyReplyRx : OUT    std_logic ;
      Err_Noise    : OUT    integer ;
      NewWord      : OUT    std_logic ;
      OutWord      : OUT    std_logic_vector (15 DOWNTO 0);
      ParityErrCnt : OUT    integer ;
      SyncPosEdge  : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT manchester_encoder
   GENERIC (
      gClkInFreq : natural := 100000000;
      gBitFreq   : natural := 1000000
   );
   PORT (
      Clk           : IN     std_logic ;
      Cmd_nData     : IN     std_logic ;
      Data          : IN     std_logic_vector (15 DOWNTO 0);
      Err_inj       : IN     std_logic_vector (15 DOWNTO 0);
      Go            : IN     std_logic ;
      nReset        : IN     std_logic ;
      tmr_Blank     : IN     std_logic ;
      BlankStart    : OUT    std_logic ;
      BlankStop     : OUT    std_logic ;
      Done          : OUT    std_logic ;
      LastBitEdge   : OUT    std_logic ;
      OutEn         : OUT    std_logic ;
      OutN          : OUT    std_logic ;
      OutP          : OUT    std_logic ;
      PulseBit      : OUT    std_logic ;
      PulseWord     : OUT    std_logic ;
      tmr_ERP_Reset : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT mil1553_framer
   GENERIC (
      CoreMode : core_mode_t := RT_MODE
   );
   PORT (
      BIT_word               : IN     std_logic_vector (15 DOWNTO 0);
      BrdcstRxed             : IN     std_logic ;
      BroadcastEnable        : IN     std_logic ;
      Busy                   : IN     std_logic ;
      Clear_InitiateBIT_Rxed : IN     std_logic ;
      Clear_Sync_Rxed        : IN     std_logic ;
      Clk                    : IN     std_logic ;
      CmdEdge                : IN     std_logic ;
      CmdProcLen             : IN     std_logic_vector (15 DOWNTO 0);
      CmdProcStart           : IN     std_logic_vector (15 DOWNTO 0);
      Cmd_nDataIn            : IN     std_logic ;
      DBC_Enable             : IN     std_logic ;
      DataWrapSubAddr        : IN     std_logic_vector (4 DOWNTO 0);
      DecoderErr             : IN     std_logic ;
      Done                   : IN     std_logic ;
      EnableHwDataWrap       : IN     std_logic ;
      Err_inj                : IN     std_logic_vector (15 DOWNTO 0);
      Instrumentation        : IN     std_logic ;
      IsRT                   : IN     std_logic ;
      LegalModeBrdcst        : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeRx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeTx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalSubAddr           : IN     std_logic_vector (31 DOWNTO 0);
      MyRtAddr               : IN     std_logic_vector (4 DOWNTO 0);
      NegEdge                : IN     std_logic ;
      NewWord                : IN     std_logic ;
      OutWord                : IN     std_logic_vector (15 DOWNTO 0);
      PosEdge                : IN     std_logic ;
      SendMessage            : IN     std_logic ;
      ServiceReqVector       : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest         : IN     std_logic ;
      SubsystemFlag          : IN     std_logic ;
      TerminalFlagIn         : IN     std_logic ;
      TxDataIn               : IN     std_logic_vector (16 DOWNTO 0);
      nReset                 : IN     std_logic ;
      tmr_1us                : IN     std_logic ;
      tmr_25us               : IN     std_logic ;
      tmr_GAP                : IN     std_logic ;
      tmr_NRP                : IN     std_logic ;
      tmr_REP                : IN     std_logic ;
      tmr_SAF                : IN     std_logic ;
      BlankDecoder           : OUT    std_logic ;
      BusActive              : OUT    std_logic ;
      BusReset_Rxed          : OUT    std_logic ;
      CmdRxed                : OUT    std_logic_vector (15 DOWNTO 0);
      Cmd_nData              : OUT    std_logic ;
      DBC_Accepted           : OUT    std_logic ;
      DataOut                : OUT    std_logic_vector (15 DOWNTO 0);
      DataReqFlag            : OUT    std_logic ;
      DataRxedFlag           : OUT    std_logic ;
      DataWrapActive         : OUT    std_logic ;
      InitiateBIT_Rxed       : OUT    std_logic ;
      ModeCmd                : OUT    std_logic_vector (15 DOWNTO 0);
      ModeData               : OUT    std_logic_vector (15 DOWNTO 0);
      NewModeCmd             : OUT    std_logic ;
      RxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      RxDataOut              : OUT    std_logic_vector (15 DOWNTO 0);
      RxDataWr               : OUT    std_logic ;
      SelTxShutdown          : OUT    std_logic ;
      SendWord               : OUT    std_logic ;
      ShutdownData           : OUT    std_logic_vector (4 DOWNTO 0);
      StatusRxed             : OUT    std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag         : OUT    std_logic ;
      Sync_Rxed              : OUT    std_logic ;
      TxAvail                : OUT    std_logic ;
      TxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      TxDataRd               : OUT    std_logic ;
      TxShutdown             : OUT    std_logic ;
      inj_ParityError        : OUT    std_logic ;
      tmr_25us_Start         : OUT    std_logic ;
      tmr_25us_Stop          : OUT    std_logic ;
      tmr_GAP_Start          : OUT    std_logic ;
      tmr_GAP_Stop           : OUT    std_logic ;
      tmr_NRP_Start          : OUT    std_logic ;
      tmr_NRP_Stop           : OUT    std_logic ;
      tmr_REP_Start          : OUT    std_logic ;
      tmr_REP_Stop           : OUT    std_logic ;
      TerminalFlag           : BUFFER std_logic 
   );
   END COMPONENT;
   COMPONENT mill1553_timers
   PORT (
      SyncPosEdge     : IN     std_logic ;
      clk             : IN     std_logic ;
      nReset          : IN     std_logic ;
      reg_tmr_1us     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_ERP     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_GAP     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_NRP     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_REP     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_SAF     : IN     std_logic_vector (15 DOWNTO 0);
      tmr_1us_Start   : IN     std_logic ;
      tmr_1us_Stop    : IN     std_logic ;
      tmr_25us_Start  : IN     std_logic ;
      tmr_25us_Stop   : IN     std_logic ;
      tmr_Blank_Start : IN     std_logic ;
      tmr_Blank_Stop  : IN     std_logic ;
      tmr_ERP_Reset   : IN     std_logic ;
      tmr_ERP_Stop    : IN     std_logic ;
      tmr_ERP_enable  : IN     std_logic ;
      tmr_GAP_Start   : IN     std_logic ;
      tmr_GAP_Stop    : IN     std_logic ;
      tmr_NRP_Start   : IN     std_logic ;
      tmr_NRP_Stop    : IN     std_logic ;
      tmr_REP_Start   : IN     std_logic ;
      tmr_REP_Stop    : IN     std_logic ;
      tmr_SAF_Start   : IN     std_logic ;
      tmr_SAF_Stop    : IN     std_logic ;
      tmr_1us         : OUT    std_logic ;
      tmr_25us        : OUT    std_logic ;
      tmr_Blank       : OUT    std_logic ;
      tmr_ERP         : OUT    std_logic ;
      tmr_GAP         : OUT    std_logic ;
      tmr_NRP         : OUT    std_logic ;
      tmr_REP         : OUT    std_logic ;
      tmr_SAF         : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : edge_detect USE ENTITY at_gen_lib.edge_detect;
   FOR ALL : manchester_decoder USE ENTITY mil1553_lib.manchester_decoder;
   FOR ALL : manchester_encoder USE ENTITY mil1553_lib.manchester_encoder;
   FOR ALL : mil1553_framer USE ENTITY mil1553_lib.mil1553_framer;
   FOR ALL : mill1553_timers USE ENTITY mil1553_lib.mill1553_timers;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1  
   nReset_Decoder <= '0' when nReset = '0' else
   '0' when OutEn1 = '1' else '1';                                      

   -- HDL Embedded Text Block 2 eGlue1
   -- eGlue  
   Instrumentation <= '0';
   BrdcstRxed <= '0';
   ClrParityErr <= '0';
   ClrNoiseErr <= '0';
   tmr_1us_Start <= '0';
   tmr_1us_Stop <= '0';
   nResetEnc <= '0' when SendMessage = '1' else
                              nReset when tmr_SAF_internal = '0' else 
                              '1';
   tmr_NRP_Start <= tmr_NRP_Start1 or CmdEdge or NewWord;
   tmr_ERP_enable <= LastBitEdge;
   tmr_ERP_Reset <= Encoder_ERP_Reset;
   tmr_ERP_Stop <= '0';
   reg_tmr_ERP <= X"0190";  --4.01us
   
   tmr_GAP <= tmr_GAP_internal;
   tmr_NRP <= tmr_NRP_internal;
   tmr_REP <= tmr_REP_internal;
   tmr_SAF <= tmr_SAF_internal;
   
   
                              

   -- HDL Embedded Text Block 4 TransmitterControl1
   -- TransmitterControl1 4   
   OutEn <= OutEn1 when TxOffIn = '0' and tmr_SAF_internal = '0' else '0';     
   Strobe <= OutEn;      
   nOutEn1 <= not OutEn1;   
   tmr_SAF_Stop <= nOutEn1;    
   tmr_SAF_Start <= tmr_SAF_Start1 or tmr_SAF_Start2;                 


   -- Instance port mappings.
   OutEdge : edge_detect
      GENERIC MAP (
         PulseWidth => 1
      )
      PORT MAP (
         Clk    => clk,
         Edge   => OutEn1,
         nReset => nReset,
         Toggle => OPEN,
         Pulse  => tmr_SAF_Start1
      );
   nOutEdge : edge_detect
      GENERIC MAP (
         PulseWidth => 1
      )
      PORT MAP (
         Clk    => clk,
         Edge   => nOutEn1,
         nReset => nReset,
         Toggle => OPEN,
         Pulse  => tmr_SAF_Start2
      );
   Decoder : manchester_decoder
      GENERIC MAP (
         gBitFreq    => 1000000,
         gClkInFreq  => 100000000,
         gOverSample => 4
      )
      PORT MAP (
         BlankDecoder => BlankDecoder,
         Clk          => clk,
         ClrNoiseErr  => ClrNoiseErr,
         ClrParityErr => ClrParityErr,
         ERP_tmr      => tmr_ERP,
         InN          => InN,
         InP          => InP,
         nReset       => nReset_Decoder,
         CmdEdge      => CmdEdge,
         Cmd_nData    => Cmd_nDataIn,
         DecoderErr   => DecoderErr,
         EarlyReplyRx => EarlyReplyRx,
         Err_Noise    => OPEN,
         NewWord      => NewWord,
         OutWord      => OutWord,
         ParityErrCnt => OPEN,
         SyncPosEdge  => SyncPosEdge
      );
   Encoder : manchester_encoder
      GENERIC MAP (
         gClkInFreq => 100000000,
         gBitFreq   => 1000000
      )
      PORT MAP (
         Clk           => clk,
         Cmd_nData     => Cmd_nData,
         Data          => DataOut1,
         Err_inj       => reg_err_inj,
         Go            => SendWord,
         nReset        => nResetEnc,
         tmr_Blank     => tmr_Blank,
         BlankStart    => tmr_Blank_Start,
         BlankStop     => tmr_Blank_Stop,
         Done          => Done,
         LastBitEdge   => LastBitEdge,
         OutEn         => OutEn1,
         OutN          => OutN,
         OutP          => OutP,
         PulseBit      => OPEN,
         PulseWord     => OPEN,
         tmr_ERP_Reset => Encoder_ERP_Reset
      );
   Framer : mil1553_framer
      GENERIC MAP (
         CoreMode => CoreMode
      )
      PORT MAP (
         BIT_word               => BIT1,
         BrdcstRxed             => BrdcstRxed,
         BroadcastEnable        => BroadcastEnable,
         Busy                   => BusBusy,
         Clear_InitiateBIT_Rxed => Clear_InitiateBIT,
         Clear_Sync_Rxed        => Clear_Synchronize,
         Clk                    => clk,
         CmdEdge                => CmdEdge,
         CmdProcLen             => CmdProcLen,
         CmdProcStart           => CmdProcStart,
         Cmd_nDataIn            => Cmd_nDataIn,
         DBC_Enable             => DBC_Enable,
         DataWrapSubAddr        => DataWrapSubAddr,
         DecoderErr             => DecoderErr,
         Done                   => Done,
         EnableHwDataWrap       => EnableHwDataWrap,
         Err_inj                => reg_err_inj,
         Instrumentation        => Instrumentation,
         IsRT                   => IsRT,
         LegalModeBrdcst        => LegalModeBrdcst,
         LegalModeRx            => LegalModeRx,
         LegalModeTx            => LegalModeTx,
         LegalSubAddr           => LegalSubAddr,
         MyRtAddr               => MyRtAddr,
         NegEdge                => CmdEdge,
         NewWord                => NewWord,
         OutWord                => OutWord,
         PosEdge                => SyncPosEdge,
         SendMessage            => SendMessage,
         ServiceReqVector       => ServiceReqVector,
         ServiceRequest         => ServiceRequest,
         SubsystemFlag          => SubsystemFlag,
         TerminalFlagIn         => TerminalFlagIn,
         TxDataIn               => TxDataIn,
         nReset                 => nReset,
         tmr_1us                => tmr_1us,
         tmr_25us               => tmr_25us,
         tmr_GAP                => tmr_GAP_internal,
         tmr_NRP                => tmr_NRP_internal,
         tmr_REP                => tmr_REP_internal,
         tmr_SAF                => tmr_SAF_internal,
         BlankDecoder           => BlankDecoder,
         BusActive              => BusActive,
         BusReset_Rxed          => BusReset_Rxed,
         CmdRxed                => CmdRxed,
         Cmd_nData              => Cmd_nData,
         DBC_Accepted           => DBC_Accepted,
         DataOut                => DataOut1,
         DataReqFlag            => DataReqFlag,
         DataRxedFlag           => DataRxedFlag,
         DataWrapActive         => DataWrapActive,
         InitiateBIT_Rxed       => InitiateBIT_Rxed,
         ModeCmd                => ModeCmd,
         ModeData               => ModeData,
         NewModeCmd             => NewModeCmd,
         RxDataAddr             => RxDataAddr,
         RxDataOut              => RxDataOut,
         RxDataWr               => RxDataWr,
         SelTxShutdown          => SelTxShutdown,
         SendWord               => SendWord,
         ShutdownData           => ShutdownData,
         StatusRxed             => StatusRxed,
         StatusRxedFlag         => StatusRxedFlag,
         Sync_Rxed              => Synchronize,
         TxAvail                => TxAvail,
         TxDataAddr             => TxDataAddr,
         TxDataRd               => OPEN,
         TxShutdown             => TxOffOut,
         inj_ParityError        => OPEN,
         tmr_25us_Start         => tmr_25us_Start,
         tmr_25us_Stop          => tmr_25us_Stop,
         tmr_GAP_Start          => tmr_GAP_Start,
         tmr_GAP_Stop           => tmr_GAP_Stop,
         tmr_NRP_Start          => tmr_NRP_Start1,
         tmr_NRP_Stop           => tmr_NRP_Stop,
         tmr_REP_Start          => tmr_REP_Start,
         tmr_REP_Stop           => tmr_REP_Stop,
         TerminalFlag           => TerminalFlag_internal
      );
   timers : mill1553_timers
      PORT MAP (
         SyncPosEdge     => SyncPosEdge,
         clk             => clk,
         nReset          => nReset,
         reg_tmr_1us     => reg_tmr_1us,
         reg_tmr_ERP     => reg_tmr_ERP,
         reg_tmr_GAP     => reg_tmr_GAP,
         reg_tmr_NRP     => reg_tmr_NRP,
         reg_tmr_REP     => reg_tmr_REP,
         reg_tmr_SAF     => reg_tmr_SAF,
         tmr_1us_Start   => tmr_1us_Start,
         tmr_1us_Stop    => tmr_1us_Stop,
         tmr_25us_Start  => tmr_25us_Start,
         tmr_25us_Stop   => tmr_25us_Stop,
         tmr_Blank_Start => tmr_Blank_Start,
         tmr_Blank_Stop  => tmr_Blank_Stop,
         tmr_ERP_Reset   => tmr_ERP_Reset,
         tmr_ERP_Stop    => tmr_ERP_Stop,
         tmr_ERP_enable  => tmr_ERP_enable,
         tmr_GAP_Start   => tmr_GAP_Start,
         tmr_GAP_Stop    => tmr_GAP_Stop,
         tmr_NRP_Start   => tmr_NRP_Start,
         tmr_NRP_Stop    => tmr_NRP_Stop,
         tmr_REP_Start   => tmr_REP_Start,
         tmr_REP_Stop    => tmr_REP_Stop,
         tmr_SAF_Start   => tmr_SAF_Start,
         tmr_SAF_Stop    => tmr_SAF_Stop,
         tmr_1us         => tmr_1us,
         tmr_25us        => tmr_25us,
         tmr_Blank       => tmr_Blank,
         tmr_ERP         => tmr_ERP,
         tmr_GAP         => tmr_GAP_internal,
         tmr_NRP         => tmr_NRP_internal,
         tmr_REP         => tmr_REP_internal,
         tmr_SAF         => tmr_SAF_internal
      );

   -- Implicit buffered output assignments
   TerminalFlag <= TerminalFlag_internal;

END struct;
