-- VHDL Entity mil1553_lib.mil1553_framer.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 08:15:47 02/20/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY mil1553_lib;
USE mil1553_lib.mil1553.ALL;

ENTITY mil1553_framer IS
   GENERIC( 
      CoreMode : core_mode_t := RT_MODE
   );
   PORT( 
      BIT_word               : IN     std_logic_vector (15 DOWNTO 0);
      BrdcstRxed             : IN     std_logic;
      BroadcastEnable        : IN     std_logic;
      Busy                   : IN     std_logic;
      Clear_InitiateBIT_Rxed : IN     std_logic;
      Clear_Sync_Rxed        : IN     std_logic;
      Clk                    : IN     std_logic;
      CmdEdge                : IN     std_logic;
      CmdProcLen             : IN     std_logic_vector (15 DOWNTO 0);
      CmdProcStart           : IN     std_logic_vector (15 DOWNTO 0);
      Cmd_nDataIn            : IN     std_logic;
      DBC_Enable             : IN     std_logic;
      DataWrapSubAddr        : IN     std_logic_vector (4 DOWNTO 0);
      DecoderErr             : IN     std_logic;
      Done                   : IN     std_logic;
      EnableHwDataWrap       : IN     std_logic;
      Err_inj                : IN     std_logic_vector (15 DOWNTO 0);
      Instrumentation        : IN     std_logic;
      IsRT                   : IN     std_logic;
      LegalModeBrdcst        : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeRx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeTx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalSubAddr           : IN     std_logic_vector (31 DOWNTO 0);
      MyRtAddr               : IN     std_logic_vector (4 DOWNTO 0);
      NegEdge                : IN     std_logic;
      NewWord                : IN     std_logic;
      OutWord                : IN     std_logic_vector (15 DOWNTO 0);
      PosEdge                : IN     std_logic;
      SendMessage            : IN     std_logic;
      ServiceReqVector       : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest         : IN     std_logic;
      SubsystemFlag          : IN     std_logic;
      TerminalFlagIn         : IN     std_logic;
      TxDataIn               : IN     std_logic_vector (16 DOWNTO 0);
      nReset                 : IN     std_logic;
      tmr_1us                : IN     std_logic;
      tmr_25us               : IN     std_logic;
      tmr_GAP                : IN     std_logic;
      tmr_NRP                : IN     std_logic;
      tmr_REP                : IN     std_logic;
      tmr_SAF                : IN     std_logic;
      BlankDecoder           : OUT    std_logic;
      BusActive              : OUT    std_logic;
      BusReset_Rxed          : OUT    std_logic;
      CmdRxed                : OUT    std_logic_vector (15 DOWNTO 0);
      Cmd_nData              : OUT    std_logic;
      DBC_Accepted           : OUT    std_logic;
      DataOut                : OUT    std_logic_vector (15 DOWNTO 0);
      DataReqFlag            : OUT    std_logic;
      DataRxedFlag           : OUT    std_logic;
      DataWrapActive         : OUT    std_logic;
      InitiateBIT_Rxed       : OUT    std_logic;
      ModeCmd                : OUT    std_logic_vector (15 DOWNTO 0);
      ModeData               : OUT    std_logic_vector (15 DOWNTO 0);
      NewModeCmd             : OUT    std_logic;
      RxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      RxDataOut              : OUT    std_logic_vector (15 DOWNTO 0);
      RxDataWr               : OUT    std_logic;
      SelTxShutdown          : OUT    std_logic;
      SendWord               : OUT    std_logic;
      ShutdownData           : OUT    std_logic_vector (4 DOWNTO 0);
      StatusRxed             : OUT    std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag         : OUT    std_logic;
      Sync_Rxed              : OUT    std_logic;
      TxAvail                : OUT    std_logic;
      TxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      TxDataRd               : OUT    std_logic;
      TxShutdown             : OUT    std_logic;
      inj_ParityError        : OUT    std_logic;
      tmr_25us_Start         : OUT    std_logic;
      tmr_25us_Stop          : OUT    std_logic;
      tmr_GAP_Start          : OUT    std_logic;
      tmr_GAP_Stop           : OUT    std_logic;
      tmr_NRP_Start          : OUT    std_logic;
      tmr_NRP_Stop           : OUT    std_logic;
      tmr_REP_Start          : OUT    std_logic;
      tmr_REP_Stop           : OUT    std_logic;
      TerminalFlag           : BUFFER std_logic
   );

-- Declarations

END mil1553_framer ;

-- VHDL Architecture mil1553_lib.mil1553_framer.struct
-- *********************************************************************************************************************
-- Company:         Al Tariq, Abu Dhabi
-- Created by:       jeansmith.UNKNOWN (DESKTOP2)
-- Date:                08:40:54 02/20/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
-- *********************************************************************************************************************
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY mil1553_lib;

ARCHITECTURE struct OF mil1553_framer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL BIT_word1               : std_logic_vector(15 DOWNTO 0);
   SIGNAL BIT_word2               : std_logic_vector(15 DOWNTO 0);
   SIGNAL BlankDecoder1           : std_logic;
   SIGNAL BlankDecoder2           : std_logic;
   SIGNAL BrdcstRxed1             : std_logic;
   SIGNAL BrdcstRxed2             : std_logic;
   SIGNAL BroadcastEnable1        : std_logic;
   SIGNAL BroadcastEnable2        : std_logic;
   SIGNAL BusActive1              : std_logic;
   SIGNAL BusActive2              : std_logic;
   SIGNAL BusReset_Rxed1          : std_logic;
   SIGNAL BusReset_Rxed2          : std_logic;
   SIGNAL Busy1                   : std_logic;
   SIGNAL Busy2                   : std_logic;
   SIGNAL Clear_InitiateBIT_Rxed1 : std_logic;
   SIGNAL Clear_InitiateBIT_Rxed2 : std_logic;
   SIGNAL Clear_Sync_Rxed1        : std_logic;
   SIGNAL Clear_Sync_Rxed2        : std_logic;
   SIGNAL Clk1                    : std_logic;
   SIGNAL Clk2                    : std_logic;
   SIGNAL CmdEdge1                : std_logic;
   SIGNAL CmdEdge2                : std_logic;
   SIGNAL CmdProcLen1             : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdProcLen2             : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdProcStart1           : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdProcStart2           : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdRxed1                : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdRxed2                : std_logic_vector(15 DOWNTO 0);
   SIGNAL Cmd_nData1              : std_logic;
   SIGNAL Cmd_nData2              : std_logic;
   SIGNAL Cmd_nDataIn1            : std_logic;
   SIGNAL Cmd_nDataIn2            : std_logic;
   SIGNAL DBC_Accepted1           : std_logic;
   SIGNAL DBC_Accepted2           : std_logic;
   SIGNAL DBC_Enable1             : std_logic;
   SIGNAL DBC_Enable2             : std_logic;
   SIGNAL DataOut1                : std_logic_vector(15 DOWNTO 0);
   SIGNAL DataOut2                : std_logic_vector(15 DOWNTO 0);
   SIGNAL DataReqFlag1            : std_logic;
   SIGNAL DataReqFlag2            : std_logic;
   SIGNAL DataRxedFlag1           : std_logic;
   SIGNAL DataRxedFlag2           : std_logic;
   SIGNAL DataWrapActive1         : std_logic;
   SIGNAL DataWrapActive2         : std_logic;
   SIGNAL DataWrapSubAddr1        : std_logic_vector(4 DOWNTO 0);
   SIGNAL DataWrapSubAddr2        : std_logic_vector(4 DOWNTO 0);
   SIGNAL DecoderErr1             : std_logic;
   SIGNAL DecoderErr2             : std_logic;
   SIGNAL Done1                   : std_logic;
   SIGNAL Done2                   : std_logic;
   SIGNAL EnableHwDataWrap1       : std_logic;
   SIGNAL EnableHwDataWrap2       : std_logic;
   SIGNAL Err_inj1                : std_logic_vector(15 DOWNTO 0);
   SIGNAL Err_inj2                : std_logic_vector(15 DOWNTO 0);
   SIGNAL InitiateBIT_Rxed1       : std_logic;
   SIGNAL InitiateBIT_Rxed2       : std_logic;
   SIGNAL Instrumentation1        : std_logic;
   SIGNAL Instrumentation2        : std_logic;
   SIGNAL IsRT1                   : std_logic;
   SIGNAL IsRT2                   : std_logic;
   SIGNAL LegalModeBrdcst1        : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalModeBrdcst2        : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalModeRx1            : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalModeRx2            : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalModeTx1            : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalModeTx2            : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalSubAddr1           : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalSubAddr2           : std_logic_vector(31 DOWNTO 0);
   SIGNAL ModeCmd1                : std_logic_vector(15 DOWNTO 0);
   SIGNAL ModeCmd2                : std_logic_vector(15 DOWNTO 0);
   SIGNAL ModeData1               : std_logic_vector(15 DOWNTO 0);
   SIGNAL ModeData2               : std_logic_vector(15 DOWNTO 0);
   SIGNAL MyRtAddr1               : std_logic_vector(4 DOWNTO 0);
   SIGNAL MyRtAddr2               : std_logic_vector(4 DOWNTO 0);
   SIGNAL NegEdge1                : std_logic;
   SIGNAL NegEdge2                : std_logic;
   SIGNAL NewModeCmd1             : std_logic;
   SIGNAL NewModeCmd2             : std_logic;
   SIGNAL NewWord1                : std_logic;
   SIGNAL NewWord2                : std_logic;
   SIGNAL OutWord1                : std_logic_vector(15 DOWNTO 0);
   SIGNAL OutWord2                : std_logic_vector(15 DOWNTO 0);
   SIGNAL PosEdge1                : std_logic;
   SIGNAL PosEdge2                : std_logic;
   SIGNAL RxDataAddr1             : std_logic_vector(9 DOWNTO 0);
   SIGNAL RxDataAddr2             : std_logic_vector(9 DOWNTO 0);
   SIGNAL RxDataOut1              : std_logic_vector(15 DOWNTO 0);
   SIGNAL RxDataOut2              : std_logic_vector(15 DOWNTO 0);
   SIGNAL RxDataWr1               : std_logic;
   SIGNAL RxDataWr2               : std_logic;
   SIGNAL SelTxShutdown1          : std_logic;
   SIGNAL SelTxShutdown2          : std_logic;
   SIGNAL SendMessage1            : std_logic;
   SIGNAL SendMessage2            : std_logic;
   SIGNAL SendWord1               : std_logic;
   SIGNAL SendWord2               : std_logic;
   SIGNAL ServiceReqVector1       : std_logic_vector(15 DOWNTO 0);
   SIGNAL ServiceReqVector2       : std_logic_vector(15 DOWNTO 0);
   SIGNAL ServiceRequest1         : std_logic;
   SIGNAL ServiceRequest2         : std_logic;
   SIGNAL ShutdownData1           : std_logic_vector(4 DOWNTO 0);
   SIGNAL ShutdownData2           : std_logic_vector(4 DOWNTO 0);
   SIGNAL StatusRxed1             : std_logic_vector(15 DOWNTO 0);
   SIGNAL StatusRxed2             : std_logic_vector(15 DOWNTO 0);
   SIGNAL StatusRxedFlag1         : std_logic;
   SIGNAL StatusRxedFlag2         : std_logic;
   SIGNAL SubsystemFlag1          : std_logic;
   SIGNAL SubsystemFlag2          : std_logic;
   SIGNAL Sync_Rxed1              : std_logic;
   SIGNAL Sync_Rxed2              : std_logic;
   SIGNAL TerminalFlag1           : std_logic;
   SIGNAL TerminalFlag2           : std_logic;
   SIGNAL TerminalFlagIn1         : std_logic;
   SIGNAL TerminalFlagIn2         : std_logic;
   SIGNAL TxAvail1                : std_logic;
   SIGNAL TxAvail2                : std_logic;
   SIGNAL TxDataAddr1             : std_logic_vector(9 DOWNTO 0);
   SIGNAL TxDataAddr2             : std_logic_vector(9 DOWNTO 0);
   SIGNAL TxDataIn1               : std_logic_vector(16 DOWNTO 0);
   SIGNAL TxDataIn2               : std_logic_vector(16 DOWNTO 0);
   SIGNAL TxDataRd1               : std_logic;
   SIGNAL TxDataRd2               : std_logic;
   SIGNAL TxShutdown1             : std_logic;
   SIGNAL TxShutdown2             : std_logic;
   SIGNAL inj_ParityError1        : std_logic;
   SIGNAL inj_ParityError2        : std_logic;
   SIGNAL nReset1                 : std_logic;
   SIGNAL nReset2                 : std_logic;
   SIGNAL tmr_1us1                : std_logic;
   SIGNAL tmr_1us2                : std_logic;
   SIGNAL tmr_25us1               : std_logic;
   SIGNAL tmr_25us2               : std_logic;
   SIGNAL tmr_25us_Start1         : std_logic;
   SIGNAL tmr_25us_Start2         : std_logic;
   SIGNAL tmr_25us_Stop1          : std_logic;
   SIGNAL tmr_25us_Stop2          : std_logic;
   SIGNAL tmr_GAP1                : std_logic;
   SIGNAL tmr_GAP2                : std_logic;
   SIGNAL tmr_GAP_Start1          : std_logic;
   SIGNAL tmr_GAP_Start2          : std_logic;
   SIGNAL tmr_GAP_Stop1           : std_logic;
   SIGNAL tmr_GAP_Stop2           : std_logic;
   SIGNAL tmr_NRP1                : std_logic;
   SIGNAL tmr_NRP2                : std_logic;
   SIGNAL tmr_NRP_Start1          : std_logic;
   SIGNAL tmr_NRP_Start2          : std_logic;
   SIGNAL tmr_NRP_Stop1           : std_logic;
   SIGNAL tmr_NRP_Stop2           : std_logic;
   SIGNAL tmr_REP1                : std_logic;
   SIGNAL tmr_REP2                : std_logic;
   SIGNAL tmr_REP_Start1          : std_logic;
   SIGNAL tmr_REP_Start2          : std_logic;
   SIGNAL tmr_REP_Stop1           : std_logic;
   SIGNAL tmr_REP_Stop2           : std_logic;
   SIGNAL tmr_SAF1                : std_logic;
   SIGNAL tmr_SAF2                : std_logic;


   -- Component Declarations
   COMPONENT mil1553_framer_bc
   PORT (
      BIT_word               : IN     std_logic_vector (15 DOWNTO 0);
      BrdcstRxed             : IN     std_logic ;
      BroadcastEnable        : IN     std_logic ;
      Busy                   : IN     std_logic ;
      Clear_InitiateBIT_Rxed : IN     std_logic ;
      Clear_Sync_Rxed        : IN     std_logic ;
      Clk                    : IN     std_logic ;
      CmdEdge                : IN     std_logic ;
      CmdProcLen             : IN     std_logic_vector (15 DOWNTO 0);
      CmdProcStart           : IN     std_logic_vector (15 DOWNTO 0);
      Cmd_nDataIn            : IN     std_logic ;
      DBC_Enable             : IN     std_logic ;
      DataWrapSubAddr        : IN     std_logic_vector (4 DOWNTO 0);
      DecoderErr             : IN     std_logic ;
      Done                   : IN     std_logic ;
      EnableHwDataWrap       : IN     std_logic ;
      Err_inj                : IN     std_logic_vector (15 DOWNTO 0);
      Instrumentation        : IN     std_logic ;
      IsRT                   : IN     std_logic ;
      LegalModeBrdcst        : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeRx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeTx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalSubAddr           : IN     std_logic_vector (31 DOWNTO 0);
      MyRtAddr               : IN     std_logic_vector (4 DOWNTO 0);
      NegEdge                : IN     std_logic ;
      NewWord                : IN     std_logic ;
      OutWord                : IN     std_logic_vector (15 DOWNTO 0);
      PosEdge                : IN     std_logic ;
      SendMessage            : IN     std_logic ;
      ServiceReqVector       : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest         : IN     std_logic ;
      SubsystemFlag          : IN     std_logic ;
      TerminalFlagIn         : IN     std_logic ;
      TxDataIn               : IN     std_logic_vector (16 DOWNTO 0);
      nReset                 : IN     std_logic ;
      tmr_1us                : IN     std_logic ;
      tmr_25us               : IN     std_logic ;
      tmr_GAP                : IN     std_logic ;
      tmr_NRP                : IN     std_logic ;
      tmr_REP                : IN     std_logic ;
      tmr_SAF                : IN     std_logic ;
      BlankDecoder           : OUT    std_logic ;
      BusActive              : OUT    std_logic ;
      BusReset_Rxed          : OUT    std_logic ;
      CmdRxed                : OUT    std_logic_vector (15 DOWNTO 0);
      Cmd_nData              : OUT    std_logic ;
      DBC_Accepted           : OUT    std_logic ;
      DataOut                : OUT    std_logic_vector (15 DOWNTO 0);
      DataReqFlag            : OUT    std_logic ;
      DataRxedFlag           : OUT    std_logic ;
      DataWrapActive         : OUT    std_logic ;
      InitiateBIT_Rxed       : OUT    std_logic ;
      ModeCmd                : OUT    std_logic_vector (15 DOWNTO 0);
      ModeData               : OUT    std_logic_vector (15 DOWNTO 0);
      NewModeCmd             : OUT    std_logic ;
      RxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      RxDataOut              : OUT    std_logic_vector (15 DOWNTO 0);
      RxDataWr               : OUT    std_logic ;
      SelTxShutdown          : OUT    std_logic ;
      SendWord               : OUT    std_logic ;
      ShutdownData           : OUT    std_logic_vector (4 DOWNTO 0);
      StatusRxed             : OUT    std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag         : OUT    std_logic ;
      Sync_Rxed              : OUT    std_logic ;
      TxAvail                : OUT    std_logic ;
      TxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      TxDataRd               : OUT    std_logic ;
      TxShutdown             : OUT    std_logic ;
      inj_ParityError        : OUT    std_logic ;
      tmr_25us_Start         : OUT    std_logic ;
      tmr_25us_Stop          : OUT    std_logic ;
      tmr_GAP_Start          : OUT    std_logic ;
      tmr_GAP_Stop           : OUT    std_logic ;
      tmr_NRP_Start          : OUT    std_logic ;
      tmr_NRP_Stop           : OUT    std_logic ;
      tmr_REP_Start          : OUT    std_logic ;
      tmr_REP_Stop           : OUT    std_logic ;
      TerminalFlag           : BUFFER std_logic 
   );
   END COMPONENT;
   COMPONENT mil1553_framer_rt
   PORT (
      BIT_word               : IN     std_logic_vector (15 DOWNTO 0);
      BrdcstRxed             : IN     std_logic ;
      BroadcastEnable        : IN     std_logic ;
      Busy                   : IN     std_logic ;
      Clear_InitiateBIT_Rxed : IN     std_logic ;
      Clear_Sync_Rxed        : IN     std_logic ;
      Clk                    : IN     std_logic ;
      CmdEdge                : IN     std_logic ;
      CmdProcLen             : IN     std_logic_vector (15 DOWNTO 0);
      CmdProcStart           : IN     std_logic_vector (15 DOWNTO 0);
      Cmd_nDataIn            : IN     std_logic ;
      DBC_Enable             : IN     std_logic ;
      DataWrapSubAddr        : IN     std_logic_vector (4 DOWNTO 0);
      DecoderErr             : IN     std_logic ;
      Done                   : IN     std_logic ;
      EnableHwDataWrap       : IN     std_logic ;
      Err_inj                : IN     std_logic_vector (15 DOWNTO 0);
      Instrumentation        : IN     std_logic ;
      IsRT                   : IN     std_logic ;
      LegalModeBrdcst        : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeRx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeTx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalSubAddr           : IN     std_logic_vector (31 DOWNTO 0);
      MyRtAddr               : IN     std_logic_vector (4 DOWNTO 0);
      NegEdge                : IN     std_logic ;
      NewWord                : IN     std_logic ;
      OutWord                : IN     std_logic_vector (15 DOWNTO 0);
      PosEdge                : IN     std_logic ;
      SendMessage            : IN     std_logic ;
      ServiceReqVector       : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest         : IN     std_logic ;
      SubsystemFlag          : IN     std_logic ;
      TerminalFlagIn         : IN     std_logic ;
      TxDataIn               : IN     std_logic_vector (16 DOWNTO 0);
      nReset                 : IN     std_logic ;
      tmr_1us                : IN     std_logic ;
      tmr_25us               : IN     std_logic ;
      tmr_GAP                : IN     std_logic ;
      tmr_NRP                : IN     std_logic ;
      tmr_REP                : IN     std_logic ;
      tmr_SAF                : IN     std_logic ;
      BlankDecoder           : OUT    std_logic ;
      BusActive              : OUT    std_logic ;
      BusReset_Rxed          : OUT    std_logic ;
      CmdRxed                : OUT    std_logic_vector (15 DOWNTO 0);
      Cmd_nData              : OUT    std_logic ;
      DBC_Accepted           : OUT    std_logic ;
      DataOut                : OUT    std_logic_vector (15 DOWNTO 0);
      DataReqFlag            : OUT    std_logic ;
      DataRxedFlag           : OUT    std_logic ;
      DataWrapActive         : OUT    std_logic ;
      InitiateBIT_Rxed       : OUT    std_logic ;
      ModeCmd                : OUT    std_logic_vector (15 DOWNTO 0);
      ModeData               : OUT    std_logic_vector (15 DOWNTO 0);
      NewModeCmd             : OUT    std_logic ;
      RxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      RxDataOut              : OUT    std_logic_vector (15 DOWNTO 0);
      RxDataWr               : OUT    std_logic ;
      SelTxShutdown          : OUT    std_logic ;
      SendWord               : OUT    std_logic ;
      ShutdownData           : OUT    std_logic_vector (4 DOWNTO 0);
      StatusRxed             : OUT    std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag         : OUT    std_logic ;
      Sync_Rxed              : OUT    std_logic ;
      TxAvail                : OUT    std_logic ;
      TxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      TxDataRd               : OUT    std_logic ;
      TxShutdown             : OUT    std_logic ;
      inj_ParityError        : OUT    std_logic ;
      tmr_25us_Start         : OUT    std_logic ;
      tmr_25us_Stop          : OUT    std_logic ;
      tmr_GAP_Start          : OUT    std_logic ;
      tmr_GAP_Stop           : OUT    std_logic ;
      tmr_NRP_Start          : OUT    std_logic ;
      tmr_NRP_Stop           : OUT    std_logic ;
      tmr_REP_Start          : OUT    std_logic ;
      tmr_REP_Stop           : OUT    std_logic ;
      TerminalFlag           : BUFFER std_logic 
   );
   END COMPONENT;


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 ebPortSelection
   -- ebPortSelection 1                                        
      -- Assign top block inputs to RT component inputs (suffix 1)
      BIT_word1               <= BIT_word;
      BrdcstRxed1             <= BrdcstRxed;
      BroadcastEnable1        <= BroadcastEnable;
      Busy1                   <= Busy;
      Clear_InitiateBIT_Rxed1 <= Clear_InitiateBIT_Rxed;
      Clear_Sync_Rxed1        <= Clear_Sync_Rxed;
      Clk1                    <= Clk;
      CmdEdge1                <= CmdEdge;
      CmdProcLen1             <= CmdProcLen;
      CmdProcStart1           <= CmdProcStart;
      Cmd_nDataIn1            <= Cmd_nDataIn;
      DBC_Enable1             <= DBC_Enable;
      DataWrapSubAddr1        <= DataWrapSubAddr;
      DecoderErr1             <= DecoderErr;
      Done1                   <= Done;
      EnableHwDataWrap1       <= EnableHwDataWrap;
      Err_inj1                <= Err_inj;
      Instrumentation1        <= Instrumentation;
      IsRT1                   <= IsRT;
      LegalModeBrdcst1        <= LegalModeBrdcst;
      LegalModeRx1            <= LegalModeRx;
      LegalModeTx1            <= LegalModeTx;
      LegalSubAddr1           <= LegalSubAddr;
      MyRtAddr1               <= MyRtAddr;
      NegEdge1                <= NegEdge;
      NewWord1                <= NewWord;
      OutWord1                <= OutWord;
      PosEdge1                <= PosEdge;
      SendMessage1            <= SendMessage;
      ServiceReqVector1       <= ServiceReqVector;
      ServiceRequest1         <= ServiceRequest;
      SubsystemFlag1          <= SubsystemFlag;
      TerminalFlagIn1         <= TerminalFlagIn;
      TxDataIn1               <= TxDataIn;
      nReset1                 <= nReset;
      tmr_1us1                <= tmr_1us;
      tmr_25us1               <= tmr_25us;
      tmr_GAP1                <= tmr_GAP;
      tmr_NRP1                <= tmr_NRP;
      tmr_REP1                <= tmr_REP;
      tmr_SAF1                <= tmr_SAF;
   
      -- Assign top block inputs to BC component inputs (suffix 2)
      BIT_word2               <= BIT_word;
      BrdcstRxed2             <= BrdcstRxed;
      BroadcastEnable2        <= BroadcastEnable;
      Busy2                   <= Busy;
      Clear_InitiateBIT_Rxed2 <= Clear_InitiateBIT_Rxed;
      Clear_Sync_Rxed2        <= Clear_Sync_Rxed;
      Clk2                    <= Clk;
      CmdEdge2                <= CmdEdge;
      CmdProcLen2             <= CmdProcLen;
      CmdProcStart2           <= CmdProcStart;
      Cmd_nDataIn2            <= Cmd_nDataIn;
      DBC_Enable2             <= DBC_Enable;
      DataWrapSubAddr2        <= DataWrapSubAddr;
      DecoderErr2             <= DecoderErr;
      Done2                   <= Done;
      EnableHwDataWrap2       <= EnableHwDataWrap;
      Err_inj2                <= Err_inj;
      Instrumentation2        <= Instrumentation;
      IsRT2                   <= IsRT;
      LegalModeBrdcst2        <= LegalModeBrdcst;
      LegalModeRx2            <= LegalModeRx;
      LegalModeTx2            <= LegalModeTx;
      LegalSubAddr2           <= LegalSubAddr;
      MyRtAddr2               <= MyRtAddr;
      NegEdge2                <= NegEdge;
      NewWord2                <= NewWord;
      OutWord2                <= OutWord;
      PosEdge2                <= PosEdge;
      SendMessage2            <= SendMessage;
      ServiceReqVector2       <= ServiceReqVector;
      ServiceRequest2         <= ServiceRequest;
      SubsystemFlag2          <= SubsystemFlag;
      TerminalFlagIn2         <= TerminalFlagIn;
      TxDataIn2               <= TxDataIn;
      nReset2                 <= nReset;
      tmr_1us2                <= tmr_1us;
      tmr_25us2               <= tmr_25us;
      tmr_GAP2                <= tmr_GAP;
      tmr_NRP2                <= tmr_NRP;
      tmr_REP2                <= tmr_REP;
      tmr_SAF2                <= tmr_SAF;
   
      -- Output port selection based on CoreMode generic
      -- If RT_MODE: use RT framer outputs (suffix 1)
      -- If BC_MODE: use BC framer outputs (suffix 2)
      -- If BCRT_MODE: use IsRT signal to select RT (suffix 1) or BC (suffix 2)
      BlankDecoder     <= BlankDecoder1     when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else BlankDecoder2;
      BusActive        <= BusActive1        when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else BusActive2;
      BusReset_Rxed    <= BusReset_Rxed1    when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else BusReset_Rxed2;
      CmdRxed          <= CmdRxed1          when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else CmdRxed2;
      Cmd_nData        <= Cmd_nData1        when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else Cmd_nData2;
      DBC_Accepted     <= DBC_Accepted1     when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else DBC_Accepted2;
      DataOut          <= DataOut1          when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else DataOut2;
      DataReqFlag      <= DataReqFlag1      when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else DataReqFlag2;
      DataRxedFlag     <= DataRxedFlag1     when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else DataRxedFlag2;
      DataWrapActive   <= DataWrapActive1   when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else DataWrapActive2;
      InitiateBIT_Rxed <= InitiateBIT_Rxed1 when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else InitiateBIT_Rxed2;
      ModeCmd          <= ModeCmd1          when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else ModeCmd2;
      ModeData         <= ModeData1         when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else ModeData2;
      NewModeCmd       <= NewModeCmd1       when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else NewModeCmd2;
      RxDataAddr       <= RxDataAddr1       when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else RxDataAddr2;
      RxDataOut        <= RxDataOut1        when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else RxDataOut2;
      RxDataWr         <= RxDataWr1         when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else RxDataWr2;
      SelTxShutdown    <= SelTxShutdown1    when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else SelTxShutdown2;
      SendWord         <= SendWord1         when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else SendWord2;
      ShutdownData     <= ShutdownData1     when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else ShutdownData2;
      StatusRxed       <= StatusRxed1       when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else StatusRxed2;
      StatusRxedFlag   <= StatusRxedFlag1   when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else StatusRxedFlag2;
      Sync_Rxed        <= Sync_Rxed1        when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else Sync_Rxed2;
      TxAvail          <= TxAvail1          when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else TxAvail2;
      TxDataAddr       <= TxDataAddr1       when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else TxDataAddr2;
      TxDataRd         <= TxDataRd1         when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else TxDataRd2;
      TxShutdown       <= TxShutdown1       when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else TxShutdown2;
      inj_ParityError  <= inj_ParityError1  when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else inj_ParityError2;
      tmr_25us_Start   <= tmr_25us_Start1   when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else tmr_25us_Start2;
      tmr_25us_Stop    <= tmr_25us_Stop1    when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else tmr_25us_Stop2;
      tmr_GAP_Start    <= tmr_GAP_Start1    when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else tmr_GAP_Start2;
      tmr_GAP_Stop     <= tmr_GAP_Stop1     when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else tmr_GAP_Stop2;
      tmr_NRP_Start    <= tmr_NRP_Start1    when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else tmr_NRP_Start2;
      tmr_NRP_Stop     <= tmr_NRP_Stop1     when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else tmr_NRP_Stop2;
      tmr_REP_Start    <= tmr_REP_Start1    when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else tmr_REP_Start2;
      tmr_REP_Stop     <= tmr_REP_Stop1     when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else tmr_REP_Stop2;
      TerminalFlag     <= TerminalFlag1     when (CoreMode = RT_MODE) or (CoreMode = BCRT_MODE and IsRT = '1') else TerminalFlag2;
   


   -- Instance port mappings.

   gBC_Framer: IF (CoreMode = BC_MODE or CoreMode = BCRT_MODE) GENERATE
   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : mil1553_framer_bc USE ENTITY mil1553_lib.mil1553_framer_bc;
   -- pragma synthesis_on

   BEGIN
      BC : mil1553_framer_bc
         PORT MAP (
            BIT_word               => BIT_word2,
            BrdcstRxed             => BrdcstRxed2,
            BroadcastEnable        => BroadcastEnable2,
            Busy                   => Busy2,
            Clear_InitiateBIT_Rxed => Clear_InitiateBIT_Rxed2,
            Clear_Sync_Rxed        => Clear_Sync_Rxed2,
            Clk                    => Clk2,
            CmdEdge                => CmdEdge2,
            CmdProcLen             => CmdProcLen2,
            CmdProcStart           => CmdProcStart2,
            Cmd_nDataIn            => Cmd_nDataIn2,
            DBC_Enable             => DBC_Enable2,
            DataWrapSubAddr        => DataWrapSubAddr2,
            DecoderErr             => DecoderErr2,
            Done                   => Done2,
            EnableHwDataWrap       => EnableHwDataWrap2,
            Err_inj                => Err_inj2,
            Instrumentation        => Instrumentation2,
            IsRT                   => IsRT2,
            LegalModeBrdcst        => LegalModeBrdcst2,
            LegalModeRx            => LegalModeRx2,
            LegalModeTx            => LegalModeTx2,
            LegalSubAddr           => LegalSubAddr2,
            MyRtAddr               => MyRtAddr2,
            NegEdge                => NegEdge2,
            NewWord                => NewWord2,
            OutWord                => OutWord2,
            PosEdge                => PosEdge2,
            SendMessage            => SendMessage2,
            ServiceReqVector       => ServiceReqVector2,
            ServiceRequest         => ServiceRequest2,
            SubsystemFlag          => SubsystemFlag2,
            TerminalFlagIn         => TerminalFlagIn2,
            TxDataIn               => TxDataIn2,
            nReset                 => nReset2,
            tmr_1us                => tmr_1us2,
            tmr_25us               => tmr_25us2,
            tmr_GAP                => tmr_GAP2,
            tmr_NRP                => tmr_NRP2,
            tmr_REP                => tmr_REP2,
            tmr_SAF                => tmr_SAF2,
            BlankDecoder           => BlankDecoder2,
            BusActive              => BusActive2,
            BusReset_Rxed          => BusReset_Rxed2,
            CmdRxed                => CmdRxed2,
            Cmd_nData              => Cmd_nData2,
            DBC_Accepted           => DBC_Accepted2,
            DataOut                => DataOut2,
            DataReqFlag            => DataReqFlag2,
            DataRxedFlag           => DataRxedFlag2,
            DataWrapActive         => DataWrapActive2,
            InitiateBIT_Rxed       => InitiateBIT_Rxed2,
            ModeCmd                => ModeCmd2,
            ModeData               => ModeData2,
            NewModeCmd             => NewModeCmd2,
            RxDataAddr             => RxDataAddr2,
            RxDataOut              => RxDataOut2,
            RxDataWr               => RxDataWr2,
            SelTxShutdown          => SelTxShutdown2,
            SendWord               => SendWord2,
            ShutdownData           => ShutdownData2,
            StatusRxed             => StatusRxed2,
            StatusRxedFlag         => StatusRxedFlag2,
            Sync_Rxed              => Sync_Rxed2,
            TxAvail                => TxAvail2,
            TxDataAddr             => TxDataAddr2,
            TxDataRd               => TxDataRd2,
            TxShutdown             => TxShutdown2,
            inj_ParityError        => inj_ParityError2,
            tmr_25us_Start         => tmr_25us_Start2,
            tmr_25us_Stop          => tmr_25us_Stop2,
            tmr_GAP_Start          => tmr_GAP_Start2,
            tmr_GAP_Stop           => tmr_GAP_Stop2,
            tmr_NRP_Start          => tmr_NRP_Start2,
            tmr_NRP_Stop           => tmr_NRP_Stop2,
            tmr_REP_Start          => tmr_REP_Start2,
            tmr_REP_Stop           => tmr_REP_Stop2,
            TerminalFlag           => TerminalFlag2
         );
   END;
   END GENERATE gBC_Framer;

   gRT: IF (CoreMode = RT_MODE or CoreMode = BCRT_MODE) GENERATE
   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : mil1553_framer_rt USE ENTITY mil1553_lib.mil1553_framer_rt;
   -- pragma synthesis_on

   BEGIN
      RT : mil1553_framer_rt
         PORT MAP (
            BIT_word               => BIT_word1,
            BrdcstRxed             => BrdcstRxed1,
            BroadcastEnable        => BroadcastEnable1,
            Busy                   => Busy1,
            Clear_InitiateBIT_Rxed => Clear_InitiateBIT_Rxed1,
            Clear_Sync_Rxed        => Clear_Sync_Rxed1,
            Clk                    => Clk1,
            CmdEdge                => CmdEdge1,
            CmdProcLen             => CmdProcLen1,
            CmdProcStart           => CmdProcStart1,
            Cmd_nDataIn            => Cmd_nDataIn1,
            DBC_Enable             => DBC_Enable1,
            DataWrapSubAddr        => DataWrapSubAddr1,
            DecoderErr             => DecoderErr1,
            Done                   => Done1,
            EnableHwDataWrap       => EnableHwDataWrap1,
            Err_inj                => Err_inj1,
            Instrumentation        => Instrumentation1,
            IsRT                   => IsRT1,
            LegalModeBrdcst        => LegalModeBrdcst1,
            LegalModeRx            => LegalModeRx1,
            LegalModeTx            => LegalModeTx1,
            LegalSubAddr           => LegalSubAddr1,
            MyRtAddr               => MyRtAddr1,
            NegEdge                => NegEdge1,
            NewWord                => NewWord1,
            OutWord                => OutWord1,
            PosEdge                => PosEdge1,
            SendMessage            => SendMessage1,
            ServiceReqVector       => ServiceReqVector1,
            ServiceRequest         => ServiceRequest1,
            SubsystemFlag          => SubsystemFlag1,
            TerminalFlagIn         => TerminalFlagIn1,
            TxDataIn               => TxDataIn1,
            nReset                 => nReset1,
            tmr_1us                => tmr_1us1,
            tmr_25us               => tmr_25us1,
            tmr_GAP                => tmr_GAP1,
            tmr_NRP                => tmr_NRP1,
            tmr_REP                => tmr_REP1,
            tmr_SAF                => tmr_SAF1,
            BlankDecoder           => BlankDecoder1,
            BusActive              => BusActive1,
            BusReset_Rxed          => BusReset_Rxed1,
            CmdRxed                => CmdRxed1,
            Cmd_nData              => Cmd_nData1,
            DBC_Accepted           => DBC_Accepted1,
            DataOut                => DataOut1,
            DataReqFlag            => DataReqFlag1,
            DataRxedFlag           => DataRxedFlag1,
            DataWrapActive         => DataWrapActive1,
            InitiateBIT_Rxed       => InitiateBIT_Rxed1,
            ModeCmd                => ModeCmd1,
            ModeData               => ModeData1,
            NewModeCmd             => NewModeCmd1,
            RxDataAddr             => RxDataAddr1,
            RxDataOut              => RxDataOut1,
            RxDataWr               => RxDataWr1,
            SelTxShutdown          => SelTxShutdown1,
            SendWord               => SendWord1,
            ShutdownData           => ShutdownData1,
            StatusRxed             => StatusRxed1,
            StatusRxedFlag         => StatusRxedFlag1,
            Sync_Rxed              => Sync_Rxed1,
            TxAvail                => TxAvail1,
            TxDataAddr             => TxDataAddr1,
            TxDataRd               => TxDataRd1,
            TxShutdown             => TxShutdown1,
            inj_ParityError        => inj_ParityError1,
            tmr_25us_Start         => tmr_25us_Start1,
            tmr_25us_Stop          => tmr_25us_Stop1,
            tmr_GAP_Start          => tmr_GAP_Start1,
            tmr_GAP_Stop           => tmr_GAP_Stop1,
            tmr_NRP_Start          => tmr_NRP_Start1,
            tmr_NRP_Stop           => tmr_NRP_Stop1,
            tmr_REP_Start          => tmr_REP_Start1,
            tmr_REP_Stop           => tmr_REP_Stop1,
            TerminalFlag           => TerminalFlag1
         );
   END;
   END GENERATE gRT;

END struct;
