-- VHDL Entity mil1553_lib.mil1553_cpu_interface.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 08:53:53 02/20/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY mil1553_lib;
USE mil1553_lib.mil1553.ALL;

ENTITY mil1553_cpu_interface IS
   GENERIC( 
      CoreMode : core_mode_t := BCRT_Mode
   );
   PORT( 
      Addr               : IN     std_logic_vector (15 DOWNTO 0);
      BitWord            : IN     std_logic_vector (15 DOWNTO 0);
      CmdRxed1           : IN     std_logic_vector (15 DOWNTO 0);
      CmdRxed2           : IN     std_logic_vector (15 DOWNTO 0);
      Cs                 : IN     std_logic;
      DBC_Accepted1      : IN     std_logic;
      DBC_Accepted2      : IN     std_logic;
      DataIn             : IN     std_logic_vector (15 DOWNTO 0);
      DataReqFlag1       : IN     std_logic;
      DataReqFlag2       : IN     std_logic;
      DataRxedFlag1      : IN     std_logic;
      DataRxedFlag2      : IN     std_logic;
      DataWrapActive1    : IN     std_logic;
      DataWrapActive2    : IN     std_logic;
      EarlyReplyRx1      : IN     std_logic;
      EarlyReplyRx2      : IN     std_logic;
      InitiateBIT_Rxed1  : IN     std_logic;
      InitiateBIT_Rxed2  : IN     std_logic;
      ModeCmd1           : IN     std_logic_vector (15 DOWNTO 0);
      ModeCmd2           : IN     std_logic_vector (15 DOWNTO 0);
      ModeData1          : IN     std_logic_vector (15 DOWNTO 0);
      ModeData2          : IN     std_logic_vector (15 DOWNTO 0);
      MyRtAddr           : IN     std_logic_vector (4 DOWNTO 0);
      MyRtAddrParity     : IN     std_logic;
      NewModeCmd1        : IN     std_logic;
      NewModeCmd2        : IN     std_logic;
      Rd                 : IN     std_logic;
      RtActiveBus        : IN     std_logic;
      RxDataAddr1        : IN     std_logic_vector (9 DOWNTO 0);
      RxDataAddr2        : IN     std_logic_vector (9 DOWNTO 0);
      RxDataOut1         : IN     std_logic_vector (15 DOWNTO 0);
      RxDataOut2         : IN     std_logic_vector (15 DOWNTO 0);
      RxDataWr1          : IN     std_logic;
      RxDataWr2          : IN     std_logic;
      ServiceReqVector   : IN     std_logic_vector (15 DOWNTO 0);
      StatusRxed1        : IN     std_logic_vector (15 DOWNTO 0);
      StatusRxed2        : IN     std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag1    : IN     std_logic;
      StatusRxedFlag2    : IN     std_logic;
      Synchronize1       : IN     std_logic;
      Synchronize2       : IN     std_logic;
      TerminalFlag_Rxed1 : IN     std_logic;
      TerminalFlag_Rxed2 : IN     std_logic;
      TxAvail1           : IN     std_logic;
      TxAvail2           : IN     std_logic;
      TxDataAddr1        : IN     std_logic_vector (9 DOWNTO 0);
      TxDataAddr2        : IN     std_logic_vector (9 DOWNTO 0);
      TxOffOut1          : IN     std_logic;
      TxOffOut2          : IN     std_logic;
      UnexpectedEdgeCnt1 : IN     std_logic_vector (15 DOWNTO 0);
      UnexpectedEdgeCnt2 : IN     std_logic_vector (15 DOWNTO 0);
      Wr                 : IN     std_logic;
      clk                : IN     std_logic;
      nReset             : IN     std_logic;
      tmr_GAP1           : IN     std_logic;
      tmr_GAP2           : IN     std_logic;
      tmr_NRP1           : IN     std_logic;
      tmr_NRP2           : IN     std_logic;
      tmr_REP1           : IN     std_logic;
      tmr_REP2           : IN     std_logic;
      tmr_SAF1           : IN     std_logic;
      tmr_SAF2           : IN     std_logic;
      BIT1               : OUT    std_logic_vector (15 DOWNTO 0);
      BroadcastEnable    : OUT    std_logic;
      BusBusy            : OUT    std_logic;
      Clear_InitiateBIT1 : OUT    std_logic;
      Clear_InitiateBIT2 : OUT    std_logic;
      Clear_Synchronize1 : OUT    std_logic;
      Clear_Synchronize2 : OUT    std_logic;
      CmdProcLen1        : OUT    std_logic_vector (15 DOWNTO 0);
      CmdProcLen2        : OUT    std_logic_vector (15 DOWNTO 0);
      CmdProcStart1      : OUT    std_logic_vector (15 DOWNTO 0);
      CmdProcStart2      : OUT    std_logic_vector (15 DOWNTO 0);
      DBC_Enable         : OUT    std_logic;
      DataOut            : OUT    std_logic_vector (15 DOWNTO 0);
      DataValid          : OUT    std_logic;
      EnableHwDataWrap   : OUT    std_logic;
      Intr               : OUT    std_logic;
      LegalModeBrdcst    : OUT    std_logic_vector (31 DOWNTO 0);
      LegalModeRx        : OUT    std_logic_vector (31 DOWNTO 0);
      LegalModeTx        : OUT    std_logic_vector (31 DOWNTO 0);
      LegalSubAddr       : OUT    std_logic_vector (31 DOWNTO 0);
      RtControl          : OUT    std_logic_vector (15 DOWNTO 0);
      SendMessage1       : OUT    std_logic;
      SendMessage2       : OUT    std_logic;
      ServiceReqVector1  : OUT    std_logic_vector (15 DOWNTO 0);
      TerminalFlag1      : OUT    std_logic;
      TerminalFlag2      : OUT    std_logic;
      TxDataIn1          : OUT    std_logic_vector (16 DOWNTO 0);
      TxDataIn2          : OUT    std_logic_vector (16 DOWNTO 0);
      datawrap_subaddr   : OUT    std_logic_vector (4 DOWNTO 0);
      nResetCore1        : OUT    std_logic;
      nResetCore2        : OUT    std_logic;
      reg_tmr_1us        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_GAP        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_NRP        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_REP        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_SAF        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_err_inj        : INOUT  std_logic_vector (15 DOWNTO 0);
      IsRT               : BUFFER std_logic;
      MyRtAddrInt        : BUFFER std_logic_vector (4 DOWNTO 0);
      MyRtAddrParityInt  : BUFFER std_logic
   );

-- Declarations

END mil1553_cpu_interface ;

-- VHDL Architecture mil1553_lib.mil1553_cpu_interface.struct
-- *********************************************************************************************************************
-- Company:         Al Tariq, Abu Dhabi
-- Created by:       jeansmith.UNKNOWN (DESKTOP2)
-- Date:                08:53:36 02/20/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
-- *********************************************************************************************************************
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY at_gen_lib;
LIBRARY mil1553_lib;

ARCHITECTURE struct OF mil1553_cpu_interface IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL ActiveBus               : std_logic;
   SIGNAL Bus1Intr                : std_logic;
   SIGNAL Bus2Intr                : std_logic;
   SIGNAL ClrTimestamp            : std_logic;
   SIGNAL DataOut1                : std_logic_vector(15 DOWNTO 0);
   SIGNAL DebugRAM                : std_logic;
   SIGNAL DelayedRdEn             : std_logic;
   SIGNAL RamDataValid            : std_logic;
   SIGNAL RdDel1                  : std_logic;
   SIGNAL RegDataValid            : std_logic;
   SIGNAL RxDataAddr              : std_logic_vector(9 DOWNTO 0);
   SIGNAL RxDataWr                : std_logic;
   SIGNAL SendMessage1Pulse       : std_logic;
   SIGNAL SendMessage2Pulse       : std_logic;
   SIGNAL SetTimestamp            : std_logic;
   SIGNAL SetValue                : std_logic_vector(63 DOWNTO 0);
   SIGNAL TerminalFlagIn1         : std_logic;
   SIGNAL TerminalFlagIn2         : std_logic;
   SIGNAL Timestamp               : std_logic_vector(63 DOWNTO 0);
   SIGNAL TxDataAddr              : std_logic_vector(9 DOWNTO 0);
   SIGNAL UseBcRepeat             : std_logic;
   SIGNAL clk_en                  : std_logic;
   SIGNAL cpu_reg_dataout         : std_logic_vector(15 DOWNTO 0);
   SIGNAL cpu_rx_data             : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL cpu_rx_rdAddress        : STD_LOGIC_VECTOR(9 DOWNTO 0);
   SIGNAL cpu_rx_wren             : STD_LOGIC := '0';
   SIGNAL cpu_tx_data             : STD_LOGIC_VECTOR(15 DOWNTO 0);
   SIGNAL cpu_tx_wraddress        : STD_LOGIC_VECTOR(9 DOWNTO 0);
   SIGNAL cpu_tx_wren             : STD_LOGIC := '0';
   SIGNAL reg_Status              : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_bit                 : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_bus1_status         : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_bus2_status         : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_clear_bits          : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_legal_brdcst_mode1  : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_legal_brdcst_mode2  : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_legal_rx_mode1      : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_legal_rx_mode2      : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_legal_subaddr1      : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_legal_subaddr2      : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_legal_tx_mode1      : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_legal_tx_mode2      : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_node_control        : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_repeat_rate         : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_rt_addr             : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_rx_cmd1             : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_rx_cmd2             : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_sw_rtaddr           : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_tx_control1         : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_tx_control2         : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_vectorword          : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_wrap_subaddr        : std_logic_vector(15 DOWNTO 0);
   SIGNAL rx_data                 : STD_LOGIC_VECTOR(16 DOWNTO 0);
   SIGNAL rx_q                    : STD_LOGIC_VECTOR(16 DOWNTO 0);
   SIGNAL rx_rdaddress            : STD_LOGIC_VECTOR(9 DOWNTO 0);
   SIGNAL tmrRepeatStart          : std_logic;
   SIGNAL tmrRepeatStop           : std_logic;
   SIGNAL tmrRepeatTimeout_Level  : std_logic;
   SIGNAL tmrRepeatTimeout_Pulse  : std_logic;
   SIGNAL tmrRepeat_500usSetValue : std_logic_vector(15 DOWNTO 0);
   SIGNAL tx_control_RT2RT        : std_logic;
   SIGNAL tx_control_RT2RT1       : std_logic;
   SIGNAL tx_control_RT2RT2       : std_logic;
   SIGNAL tx_control_SendMessage1 : std_logic;
   SIGNAL tx_control_SendMessage2 : std_logic;
   SIGNAL tx_data                 : STD_LOGIC_VECTOR(16 DOWNTO 0);
   SIGNAL tx_q                    : STD_LOGIC_VECTOR(16 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL CmdProcLen1_internal   : std_logic_vector (15 DOWNTO 0);
   SIGNAL CmdProcLen2_internal   : std_logic_vector (15 DOWNTO 0);
   SIGNAL CmdProcStart1_internal : std_logic_vector (15 DOWNTO 0);
   SIGNAL CmdProcStart2_internal : std_logic_vector (15 DOWNTO 0);
   SIGNAL reg_tmr_1us_internal   : std_logic_vector (15 DOWNTO 0);
   SIGNAL reg_tmr_GAP_internal   : std_logic_vector (15 DOWNTO 0);
   SIGNAL reg_tmr_NRP_internal   : std_logic_vector (15 DOWNTO 0);
   SIGNAL reg_tmr_REP_internal   : std_logic_vector (15 DOWNTO 0);
   SIGNAL reg_tmr_SAF_internal   : std_logic_vector (15 DOWNTO 0);


   -- Component Declarations
   COMPONENT edge_detect
   GENERIC (
      PulseWidth : integer := 65550
   );
   PORT (
      Clk    : IN     std_logic ;
      Edge   : IN     std_logic ;
      nReset : IN     std_logic ;
      Toggle : OUT    std_logic ;
      Pulse  : BUFFER std_logic 
   );
   END COMPONENT;
   COMPONENT mil1553_cpu_registers
   GENERIC (
      gID      : std_logic_vector(15 downto 0) := X"BEEF";
      gVersion : std_logic_vector(15 downto 0) := X"0202"
   );
   PORT (
      Addr                   : IN     std_logic_vector (15 DOWNTO 0);
      Cs                     : IN     std_logic ;
      DataIn                 : IN     std_logic_vector (15 DOWNTO 0);
      Rd                     : IN     std_logic ;
      Wr                     : IN     std_logic ;
      clk                    : IN     std_logic ;
      nReset                 : IN     std_logic ;
      DataOut                : OUT    std_logic_vector (15 DOWNTO 0);
      DataValid              : OUT    std_logic ;
      Intr                   : OUT    std_logic ;
      reg_tmr_SAF            : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_intr_mask          : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_legal_subaddr2     : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_legal_subaddr1     : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_tmr_REP            : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_status_rxed1       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_NRP            : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_legal_rx_mode1     : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_legal_rx_mode2     : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_legal_tx_mode1     : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_legal_tx_mode2     : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_legal_brdcst_mode1 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_legal_brdcst_mode2 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_gID                : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_mode_data_rxed1    : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_1us            : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_tmr_GAP            : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_fw_version         : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_rt_addr            : IN     std_logic_vector (15 DOWNTO 0);
      reg_mode_cmd_rxed1     : IN     std_logic_vector (15 DOWNTO 0);
      reg_clear_bits         : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_node_control       : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_err_inj_data       : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_status             : IN     std_logic_vector (15 DOWNTO 0);
      reg_rx_cmd1            : IN     std_logic_vector (15 DOWNTO 0);
      reg_tx_control1        : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_cmd_proc_start1    : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_cmd_proc_length1   : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_cmd_rxed1          : IN     std_logic_vector (15 DOWNTO 0);
      reg_24                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_25                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_26                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_27                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_28                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_29                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_bus1_status        : IN     std_logic_vector (15 DOWNTO 0);
      reg_bus1_mask          : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_status_rxed2       : IN     std_logic_vector (15 DOWNTO 0);
      reg_mode_cmd_rxed2     : IN     std_logic_vector (15 DOWNTO 0);
      reg_mode_data_rxed2    : IN     std_logic_vector (15 DOWNTO 0);
      reg_rx_cmd2            : IN     std_logic_vector (15 DOWNTO 0);
      reg_tx_control2        : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_cmd_proc_start2    : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_cmd_proc_length2   : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_cmd_rxed2          : IN     std_logic_vector (15 DOWNTO 0);
      reg_40                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_41                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_42                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_43                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_44                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_45                 : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_bus2_status        : IN     std_logic_vector (15 DOWNTO 0);
      reg_bus2_mask          : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_repeat_rate        : BUFFER std_logic_vector (15 DOWNTO 0);
      TimeStamp              : IN     std_logic_vector (63 DOWNTO 0);
      reg_wrap_subaddr       : BUFFER std_logic_vector (15 DOWNTO 0);
      Bus1Intr               : BUFFER std_logic ;
      Bus2Intr               : BUFFER std_logic ;
      reg_vectorword         : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_bit                : BUFFER std_logic_vector (15 DOWNTO 0);
      reg_sw_rtaddr          : BUFFER std_logic_vector (15 DOWNTO 0);
      MyRtAddrParity         : IN     std_logic ;
      MyRtAddr               : IN     std_logic_vector (4 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT ram_dp_1kx17
   PORT (
      clock     : IN     STD_LOGIC  := '1';
      data      : IN     STD_LOGIC_VECTOR (16 DOWNTO 0);
      rdaddress : IN     STD_LOGIC_VECTOR (9 DOWNTO 0);
      wraddress : IN     STD_LOGIC_VECTOR (9 DOWNTO 0);
      wren      : IN     STD_LOGIC  := '0';
      q         : OUT    STD_LOGIC_VECTOR (16 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT repeat_timer
   GENERIC (
      CoreMode : core_mode_t := BCRT_MODE
   );
   PORT (
      clk             : IN     std_logic ;
      clk_en          : IN     std_logic ;
      nReset          : IN     std_logic ;
      reset           : IN     std_logic ;
      stop            : IN     std_logic ;
      timer1_config   : IN     std_logic_vector (15 DOWNTO 0);
      timer2_config   : IN     std_logic_vector (15 DOWNTO 0);
      clockout        : OUT    std_logic ;
      pulse           : OUT    std_logic ;
      timeout         : OUT    std_logic ;
      timer1_clockout : BUFFER std_logic ;
      timer1_pulse    : BUFFER std_logic ;
      timer1_timeout  : BUFFER std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : edge_detect USE ENTITY at_gen_lib.edge_detect;
   FOR ALL : mil1553_cpu_registers USE ENTITY mil1553_lib.mil1553_cpu_registers;
   FOR ALL : ram_dp_1kx17 USE ENTITY mil1553_lib.ram_dp_1kx17;
   FOR ALL : repeat_timer USE ENTITY mil1553_lib.repeat_timer;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 RepeatControl
   -- RepeatControl 1  
   SendMessage1 <= tmrRepeatTimeout_pulse when UseBcRepeat = '1' and ActiveBus = '0' else SendMessage1Pulse;                  
   SendMessage2 <= tmrRepeatTimeout_pulse when UseBcRepeat = '1' and ActiveBus = '1' else SendMessage2Pulse;                                     

   -- HDL Embedded Text Block 2 eRAM_IF1
   -- eRAM_IF 1  
   tx_control_RT2RT <= tx_control_RT2RT1 when ActiveBus = '0' else tx_control_RT2RT2;            
   TxDataIn1 <= tx_q when DataWrapActive1 = '0' else rx_q;
   TxDataIn2 <= tx_q when DataWrapActive2 = '0' else rx_q;
   -- NOTE: Reading from the TxRAM and Writing to the RxRAM from the CPU may cause data failures
   -- and should ONLY be used for debugging purposes.
   TxDataAddr <=   cpu_tx_wraddress when DebugRAM = '1' else
                              TxDataAddr1 when ActiveBus = '0' else 
                              TxDataAddr2 when ActiveBus = '1' else 
                              (others => '0');
   RamDataValid <= DelayedRdEn when Addr(11 downto 10) = "01" or Addr(11 downto 10) = "10" else
                              RegDataValid;
   DataValid <= RamDataValid;
   tx_data <= tx_control_RT2RT1 & DataIn when ActiveBus = '0' and Addr(11 downto 10) = "01" else 
                     tx_control_RT2RT2 & DataIn when ActiveBus = '1' and Addr(11 downto 10) = "01" else
                     (others => '0');
   rx_rdaddress <= cpu_rx_rdaddress(9 downto 0) when DebugRAM = '1' else
                         cpu_rx_rdaddress(9 downto 0) when DataWrapActive1 = '0' and DataWrapActive2 = '0' else
                         TxDataAddr1 when DataWrapActive1  = '1' and ActiveBus = '0' and DebugRAM = '0' else
                         TxDataAddr2 when DataWrapActive2  = '1' and ActiveBus = '1' and DebugRAM = '0' else
                         (others => '0');
   cpu_rx_data <= rx_q(15 downto 0);
   rx_data <= '0' & DataIn when DebugRAM = '1' else
                     '0' & RxDataOut1 when ActiveBus = '0' else 
                     '0' & RxDataOut2 when ActiveBus = '1' else
                     '0' & X"A5A5";
   RxDataWr <=    cpu_rx_wren when DebugRAM = '1' else
                           RxDataWr1 when ActiveBus = '0' else 
                           RxDataWr2 when ActiveBus = '1' else
                           '0';
   RxDataAddr <=    cpu_rx_rdaddress when DebugRAM = '1' else
                             RxDataAddr1 when ActiveBus ='0' else 
                             RxDataAddr2 when ActiveBus = '1' else
                              (others => '0');
   -- Address mapping to RAM
   cpu_tx_wraddress  <= Addr(9 downto 0) when Addr(11 downto 10) = "01" else (others => '0');
   cpu_rx_rdaddress <= Addr(9 downto 0) when Addr(11 downto 10) = "10" else (others => '0');
   cpu_tx_wren <=Wr when Addr(11 downto 10) = "01" else '0';
   cpu_rx_wren <=Wr when Addr(11 downto 10) = "10" else '0';
   
   DataOut <=  cpu_reg_dataout when Addr(11 downto 10) = "00" else
                      tx_q(15 downto 0) when Addr(11 downto 10) = "01" else
                      rx_q(15 downto 0) when Addr(11 downto 10) = "10" else
                      X"DEAD";
   

   -- HDL Embedded Text Block 3 eRegDemux1
   -- eRegDemux 2
   tx_control_RT2RT1 <= reg_tx_control1(15);   
   tx_control_SendMessage1 <= reg_tx_control1(14); 
   tx_control_RT2RT2 <= reg_tx_control2(15);   
   tx_control_SendMessage2 <= reg_tx_control2(14);            
   LegalSubAddr <= reg_legal_subaddr2 & reg_legal_subaddr1;
   LegalModeRx <= reg_legal_rx_mode2 & reg_legal_rx_mode1;
   LegalModeTx <= reg_legal_tx_mode2 & reg_legal_tx_mode1;
   LegalModeBrdcst <= reg_legal_brdcst_mode2 & reg_legal_brdcst_mode1;
   -- RT Status register (not BUS STATUS)
   reg_Status(15) <= TxAvail1;
   reg_Status(14) <= TxAvail2;
   reg_Status(13) <= TxOffOut1;
   reg_Status(12) <= TxOffOut2;
   reg_Status(11) <= TerminalFlag_Rxed1 or TerminalFlag_Rxed2;  
   reg_Status(10) <= DBC_Accepted1 or DBC_Accepted2;      
   reg_Status(9) <= Synchronize1 or Synchronize2;     
   reg_Status(8) <= InitiateBIT_Rxed1 or InitiateBIT_Rxed2;  
   reg_Status(7 downto 2) <= (others => '0'); 
   reg_Status(1) <= Bus2Intr;
   reg_Status(0) <= Bus1Intr;   
   Clear_Synchronize1 <= reg_clear_bits(11);  
   Clear_InitiateBIT1 <= reg_clear_bits(10);
   Clear_Synchronize2 <= reg_clear_bits(11);  
   Clear_InitiateBIT2 <= reg_clear_bits(10);
   
   --Bus specific status
   reg_bus1_status(15 downto 9) <= "0000000";
   reg_bus1_status(8) <= EarlyReplyRx1 and (not IsRT);
   reg_bus1_status(7) <= NewModeCmd1;
   reg_bus1_status(6) <= DataReqFlag1;
   reg_bus1_status(5) <= DataRxedFlag1;
   reg_bus1_status(4) <= StatusRxedFlag1;
   reg_bus1_status(3) <= tmr_SAF1;
   reg_bus1_status(2) <= tmr_REP1;
   reg_bus1_status(1) <= tmr_NRP1;
   reg_bus1_status(0) <= tmr_GAP1;
   
   reg_bus2_status(15 downto 9) <= "0000000";
   reg_bus2_status(8) <= EarlyReplyRx2 and (not IsRT);
   reg_bus2_status(7) <= NewModeCmd2;
   reg_bus2_status(6) <= DataReqFlag2;
   reg_bus2_status(5) <= DataRxedFlag2;
   reg_bus2_status(4) <= StatusRxedFlag2;
   reg_bus2_status(3) <= tmr_SAF2;
   reg_bus2_status(2) <= tmr_REP2;
   reg_bus2_status(1) <= tmr_NRP2;
   reg_bus2_status(0) <= tmr_GAP2;
   
   -- Rx Cmd
   reg_rx_cmd1(15 downto 13) <= "000";
   reg_rx_cmd1(12) <= TxOffOut2;
   reg_rx_cmd1(11) <= TerminalFlag_Rxed1;
   reg_rx_cmd1(10) <= DBC_Accepted1;
   reg_rx_cmd1(9) <= Synchronize1;
   reg_rx_cmd1(8) <= InitiateBIT_Rxed1;
   reg_rx_cmd1(7 downto 0) <= X"00";
   
   reg_rx_cmd2(15 downto 13) <= "000";
   reg_rx_cmd2(12) <= TxOffOut1;
   reg_rx_cmd2(11) <= TerminalFlag_Rxed2;
   reg_rx_cmd2(10) <= DBC_Accepted2;
   reg_rx_cmd2(9) <= Synchronize2;
   reg_rx_cmd2(8) <= InitiateBIT_Rxed2;
   reg_rx_cmd2(7 downto 0) <= X"00";
   
   RtControl <= reg_node_control;
   BusBusy <= reg_node_control(15);
   BroadcastEnable <= reg_node_control(14); 
   DBC_Enable <= reg_node_control(13);   
   ActiveBus <= reg_node_control(12) when IsRt = '0' else RtActiveBus;
   UseBcRepeat <= reg_node_control(11);
   tmrRepeatStop <= reg_node_control(10);
   tmrRepeatStart <= reg_node_control(9);
   EnableHwDataWrap <= reg_node_control(8);
   ServiceReqVector1 <= reg_vectorword when reg_node_control(7) = '1' else ServiceReqVector;
   Bit1 <= reg_bit when reg_node_control(6) = '1' else BitWord;
   IsRt <= reg_node_control(5);
   TerminalFlag1 <= reg_node_control(4);
   TerminalFlag2 <= reg_node_control(4);
   -- bit 3 is for use sw rt addr
   DebugRAM <= reg_node_control(2);
   nResetCore1 <= not reg_node_control(0);
   nResetCore2 <= not reg_node_control(1);
   
   -- Timestamp
   ClrTimestamp <= '0';
   SetTimeStamp <= '0';
   SetValue <= (others => '0');
   
   --RT ADDR
      reg_rt_addr <= "00" & MyRtAddrParityInt & MyRtAddrInt & "00" & MyRtAddrParity & MyRtAddr;
   process (nReset, Clk)
   begin
   if (nReset = '0') then
     MyRtAddrInt <= (others => '0');
     MyRtAddrParityInt <= '0';
   elsif (clk'event and clk = '1') then
     if (reg_node_control(3) = '0') then
       MyRtAddrInt <= MyRtAddr;
       MyRtAddrParityInt <= MyRtAddrParity;
     else 
       MyRtAddrInt <= reg_sw_rtaddr(4 downto 0);
       MyRtAddrParityInt <= reg_sw_rtaddr(5);
     end if;
   end if;
   end process;
   
   datawrap_subaddr <= reg_wrap_subaddr(4 downto 0);
   
   
   

   -- HDL Embedded Text Block 4 eb1
   -- eb1 4                      
   process(Clk)
   begin
   if (clk'event and clk='1') then
     RdDel1 <= Rd;
     DelayedRdEn <= RdDel1;
   end if;
   end process;
                    

   -- HDL Embedded Text Block 5 tmrRepeat
   -- tmrGen 4  
   tmrRepeat_500usSetValue <= X"C34F";
   clk_en <= '1';  
                                


   -- Instance port mappings.
   SndMsg1 : edge_detect
      GENERIC MAP (
         PulseWidth => 1
      )
      PORT MAP (
         Clk    => clk,
         Edge   => tx_control_SendMessage1,
         nReset => nReset,
         Toggle => OPEN,
         Pulse  => SendMessage1Pulse
      );
   SndMsg2 : edge_detect
      GENERIC MAP (
         PulseWidth => 1
      )
      PORT MAP (
         Clk    => clk,
         Edge   => tx_control_SendMessage2,
         nReset => nReset,
         Toggle => OPEN,
         Pulse  => SendMessage2Pulse
      );
   --USE ieee.std_logic_arith.all;
   --USE ieee.std_logic_arith.all;
   mil1553_registers : mil1553_cpu_registers
      GENERIC MAP (
         gID      => X"FEEB",
         gVersion => X"0503"
      )
      PORT MAP (
         Addr                   => Addr,
         Cs                     => Cs,
         DataIn                 => DataIn,
         Rd                     => Rd,
         Wr                     => Wr,
         clk                    => clk,
         nReset                 => nReset,
         DataOut                => cpu_reg_dataout,
         DataValid              => RegDataValid,
         Intr                   => Intr,
         reg_tmr_SAF            => reg_tmr_SAF_internal,
         reg_intr_mask          => OPEN,
         reg_legal_subaddr2     => reg_legal_subaddr2,
         reg_legal_subaddr1     => reg_legal_subaddr1,
         reg_tmr_REP            => reg_tmr_REP_internal,
         reg_status_rxed1       => StatusRxed1,
         reg_tmr_NRP            => reg_tmr_NRP_internal,
         reg_legal_rx_mode1     => reg_legal_rx_mode1,
         reg_legal_rx_mode2     => reg_legal_rx_mode2,
         reg_legal_tx_mode1     => reg_legal_tx_mode1,
         reg_legal_tx_mode2     => reg_legal_tx_mode2,
         reg_legal_brdcst_mode1 => reg_legal_brdcst_mode1,
         reg_legal_brdcst_mode2 => reg_legal_brdcst_mode2,
         reg_gID                => OPEN,
         reg_mode_data_rxed1    => ModeData1,
         reg_tmr_1us            => reg_tmr_1us_internal,
         reg_tmr_GAP            => reg_tmr_GAP_internal,
         reg_fw_version         => OPEN,
         reg_rt_addr            => reg_rt_addr,
         reg_mode_cmd_rxed1     => ModeCmd1,
         reg_clear_bits         => reg_clear_bits,
         reg_node_control       => reg_node_control,
         reg_err_inj_data       => reg_err_inj,
         reg_status             => reg_Status,
         reg_rx_cmd1            => reg_rx_cmd1,
         reg_tx_control1        => reg_tx_control1,
         reg_cmd_proc_start1    => CmdProcStart1_internal,
         reg_cmd_proc_length1   => CmdProcLen1_internal,
         reg_cmd_rxed1          => CmdRxed1,
         reg_24                 => OPEN,
         reg_25                 => OPEN,
         reg_26                 => OPEN,
         reg_27                 => OPEN,
         reg_28                 => OPEN,
         reg_29                 => OPEN,
         reg_bus1_status        => reg_bus1_status,
         reg_bus1_mask          => OPEN,
         reg_status_rxed2       => StatusRxed2,
         reg_mode_cmd_rxed2     => ModeCmd2,
         reg_mode_data_rxed2    => ModeData2,
         reg_rx_cmd2            => reg_rx_cmd2,
         reg_tx_control2        => reg_tx_control2,
         reg_cmd_proc_start2    => CmdProcStart2_internal,
         reg_cmd_proc_length2   => CmdProcLen2_internal,
         reg_cmd_rxed2          => CmdRxed2,
         reg_40                 => OPEN,
         reg_41                 => OPEN,
         reg_42                 => OPEN,
         reg_43                 => OPEN,
         reg_44                 => OPEN,
         reg_45                 => OPEN,
         reg_bus2_status        => reg_bus2_status,
         reg_bus2_mask          => OPEN,
         reg_repeat_rate        => reg_repeat_rate,
         TimeStamp              => Timestamp,
         reg_wrap_subaddr       => reg_wrap_subaddr,
         Bus1Intr               => Bus1Intr,
         Bus2Intr               => Bus2Intr,
         reg_vectorword         => reg_vectorword,
         reg_bit                => reg_bit,
         reg_sw_rtaddr          => reg_sw_rtaddr,
         MyRtAddrParity         => MyRtAddrParity,
         MyRtAddr               => MyRtAddr
      );
   RxRAM : ram_dp_1kx17
      PORT MAP (
         clock     => clk,
         data      => rx_data,
         rdaddress => rx_rdaddress,
         wraddress => RxDataAddr,
         wren      => RxDataWr,
         q         => rx_q
      );
   TxRAM : ram_dp_1kx17
      PORT MAP (
         clock     => clk,
         data      => tx_data,
         rdaddress => TxDataAddr,
         wraddress => cpu_tx_wraddress,
         wren      => cpu_tx_wren,
         q         => tx_q
      );
   U_0 : repeat_timer
      GENERIC MAP (
         CoreMode => CoreMode
      )
      PORT MAP (
         clk             => clk,
         clk_en          => clk_en,
         nReset          => nReset,
         reset           => tmrRepeatStart,
         stop            => tmrRepeatStop,
         timer1_config   => tmrRepeat_500usSetValue,
         timer2_config   => reg_repeat_rate,
         clockout        => OPEN,
         pulse           => tmrRepeatTimeout_Pulse,
         timeout         => tmrRepeatTimeout_Level,
         timer1_clockout => OPEN,
         timer1_pulse    => OPEN,
         timer1_timeout  => OPEN
      );

   -- Implicit buffered output assignments
   CmdProcLen1   <= CmdProcLen1_internal;
   CmdProcLen2   <= CmdProcLen2_internal;
   CmdProcStart1 <= CmdProcStart1_internal;
   CmdProcStart2 <= CmdProcStart2_internal;
   reg_tmr_1us   <= reg_tmr_1us_internal;
   reg_tmr_GAP   <= reg_tmr_GAP_internal;
   reg_tmr_NRP   <= reg_tmr_NRP_internal;
   reg_tmr_REP   <= reg_tmr_REP_internal;
   reg_tmr_SAF   <= reg_tmr_SAF_internal;

END struct;
