-- VHDL Entity mil1553_lib.mil1553_framer_rt.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (jeansmithE313)
--          at - 08:15:00 16/01/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY mil1553_framer_rt IS
   PORT( 
      BIT_word               : IN     std_logic_vector (15 DOWNTO 0);
      BrdcstRxed             : IN     std_logic;
      BroadcastEnable        : IN     std_logic;
      Busy                   : IN     std_logic;
      Clear_InitiateBIT_Rxed : IN     std_logic;
      Clear_Sync_Rxed        : IN     std_logic;
      Clk                    : IN     std_logic;
      CmdEdge                : IN     std_logic;
      CmdProcLen             : IN     std_logic_vector (15 DOWNTO 0);
      CmdProcStart           : IN     std_logic_vector (15 DOWNTO 0);
      Cmd_nDataIn            : IN     std_logic;
      DBC_Enable             : IN     std_logic;
      DataWrapSubAddr        : IN     std_logic_vector (4 DOWNTO 0);
      DecoderErr             : IN     std_logic;
      Done                   : IN     std_logic;
      EnableHwDataWrap       : IN     std_logic;
      Err_inj                : IN     std_logic_vector (15 DOWNTO 0);
      Instrumentation        : IN     std_logic;
      IsRT                   : IN     std_logic;
      LegalModeBrdcst        : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeRx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeTx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalSubAddr           : IN     std_logic_vector (31 DOWNTO 0);
      MyRtAddr               : IN     std_logic_vector (4 DOWNTO 0);
      NegEdge                : IN     std_logic;
      NewWord                : IN     std_logic;
      OutWord                : IN     std_logic_vector (15 DOWNTO 0);
      PosEdge                : IN     std_logic;
      SendMessage            : IN     std_logic;
      ServiceReqVector       : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest         : IN     std_logic;
      SubsystemFlag          : IN     std_logic;
      TerminalFlagIn         : IN     std_logic;
      TxDataIn               : IN     std_logic_vector (16 DOWNTO 0);
      nReset                 : IN     std_logic;
      tmr_1us                : IN     std_logic;
      tmr_25us               : IN     std_logic;
      tmr_GAP                : IN     std_logic;
      tmr_NRP                : IN     std_logic;
      tmr_REP                : IN     std_logic;
      tmr_SAF                : IN     std_logic;
      BlankDecoder           : OUT    std_logic;
      BusActive              : OUT    std_logic;
      BusReset_Rxed          : OUT    std_logic;
      CmdRxed                : OUT    std_logic_vector (15 DOWNTO 0);
      Cmd_nData              : OUT    std_logic;
      DBC_Accepted           : OUT    std_logic;
      DataOut                : OUT    std_logic_vector (15 DOWNTO 0);
      DataReqFlag            : OUT    std_logic;
      DataRxedFlag           : OUT    std_logic;
      DataWrapActive         : OUT    std_logic;
      InitiateBIT_Rxed       : OUT    std_logic;
      ModeCmd                : OUT    std_logic_vector (15 DOWNTO 0);
      ModeData               : OUT    std_logic_vector (15 DOWNTO 0);
      NewModeCmd             : OUT    std_logic;
      RxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      RxDataOut              : OUT    std_logic_vector (15 DOWNTO 0);
      RxDataWr               : OUT    std_logic;
      SelTxShutdown          : OUT    std_logic;
      SendWord               : OUT    std_logic;
      ShutdownData           : OUT    std_logic_vector (4 DOWNTO 0);
      StatusRxed             : OUT    std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag         : OUT    std_logic;
      Sync_Rxed              : OUT    std_logic;
      TxAvail                : OUT    std_logic;
      TxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      TxDataRd               : OUT    std_logic;
      TxShutdown             : OUT    std_logic;
      inj_ParityError        : OUT    std_logic;
      tmr_25us_Start         : OUT    std_logic;
      tmr_25us_Stop          : OUT    std_logic;
      tmr_GAP_Start          : OUT    std_logic;
      tmr_GAP_Stop           : OUT    std_logic;
      tmr_NRP_Start          : OUT    std_logic;
      tmr_NRP_Stop           : OUT    std_logic;
      tmr_REP_Start          : OUT    std_logic;
      tmr_REP_Stop           : OUT    std_logic;
      TerminalFlag           : BUFFER std_logic
   );

-- Declarations

END mil1553_framer_rt ;

--
-- VHDL Architecture mil1553_lib.mil1553_framer_rt.fsm
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 15:08:43 02/16/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
 
ARCHITECTURE fsm OF mil1553_framer_rt IS

   -- Architecture Declarations
   -- Status bits generated in FSM
   signal MessageError : std_logic;
   signal sWaitforStatusActive : std_logic;
   ---------------------------------
   signal TxStatus_Rxed : std_logic;
   signal TxLastCommand : std_logic;
   signal InhibitTFlag_Rxed : std_logic;
   signal ClrInhibitTFlag_Rxed : std_logic;
   signal ResetRt_Rxed : std_logic;
   signal Broadcast : std_logic;
   signal WordCount : integer range 0 to 34;
   signal CmdCount : integer range 0 to 32;
   signal DelayCount : integer;
   signal Len : integer range 0 to 33;
   signal LegalModeRxed : std_logic;
   signal LegalSubAddrRxed : std_logic;
   signal PrevStatus : std_logic_vector(15 downto 0);
   signal PrevCmdWord : std_logic_vector(15 downto 0);
   signal CmdWord : std_logic_vector(15 downto 0);
   signal RtAddr : std_logic_vector(4 downto 0);
   signal RtSubAddr : std_logic_vector(4 downto 0);
   signal RamWaitStates : integer range 0 to 3;
   signal RtLen_Mode : std_logic_vector(4 downto 0);
   signal Tx_nRx : std_logic;
   signal RT2RT : std_logic;
   signal RT2RT_Busy : std_logic;
   signal RT2RT_RxRtAddr : std_logic_vector(4 downto 0);
   signal Status : std_logic_vector(15 downto 0);
   signal RT2RT_Flag : std_logic;
   function CheckLegalMode(RtLen_Mode : std_logic_vector(4 downto 0); LegalMode :  std_logic_vector(31 downto 0)) return std_logic is
   variable Count : integer range 0 to 31;
   begin
     Count := to_integer(unsigned(RtLen_Mode));
     return LegalMode(Count);
   end function;
   
   function CheckLegalSubaddr (RtSubAddr : std_logic_vector(4 downto 0); LegalSubAddr :  std_logic_vector(31 downto 0)) return std_logic is
   variable Count : integer range 0 to 31;
   begin
     if (RtSubAddr /= "00000" and RtSubAddr /= "11111")  then 
       Count := to_integer(unsigned(RtSubAddr));
       return LegalSubAddr(Count);
     else
       return '0';
     End if;
   end function;
   function BcLegalMode(RtSubAddr: std_logic_vector(4 downto 0); RtLenMode : std_logic_vector(4 downto 0);Tx_nRx : std_logic) return std_logic is
   begin
   if (RtSubAddr = "00000" or RtSubAddr = "11111") then 
   if (RtLenMode(4) = '0') then
     if (Tx_nRx = '0') then
       return '0';
     else
       case RtLenMode(3 downto 0) is
         when X"9" => return '0';
         when X"A" => return '0';
         when X"B" => return '0';
         when X"C" => return '0';
         when X"D" => return '0';
         when X"E" => return '0';
         when X"F" => return '0';
         when others => return '1';
       end case;
     end if;
   else
     if (Tx_nRx = '0') then
       case RtLenMode(3 downto 0) is
         when X"1" => return '1';
         when X"4" => return '1';
         when X"5" => return '1';
         when others => return '0';
       end case;
     else
       case RtLenMode(3 downto 0) is
         when X"0" => return '1';
         when X"2" => return '1';
         when X"3" => return '1';
         when others => return '0';
       end case;
     end if;
   end if;
   else
    return '0';
   end if;
   end function;

   TYPE STATE_TYPE IS (
      sIdle,
      rtCheckLegal,
      rt2SendData,
      rt2SendWords,
      rt2SendStatus,
      rt1SendStatus,
      rt1RxWords,
      rt1REP_A,
      rt1Wait1stWord,
      rt4Mode_Rx,
      rt4SendStatus,
      rt5ModeDatTx_Rx,
      rt5SendStatus,
      rt5SendWord,
      rt6ModeDatRx_Rx,
      rt6REPA,
      rt6SendStatus,
      rtRxedCmd1,
      rt4ModeResp,
      rtNoBroadcast,
      rtWrngAddr,
      rt1REP_B,
      rt6REPB,
      rt1RT2RT_transition,
      rtRxGap,
      rt1ScndCmdWord,
      sClrNRP,
      rt1CaptureStatus,
      rt6CaptureStatus,
      rt5REPB,
      rt5CaptureStatus,
      rt5REPA,
      s0
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare any pre-registered internal signals
   SIGNAL BlankDecoder_cld : std_logic ;
   SIGNAL BusActive_cld : std_logic ;
   SIGNAL BusReset_Rxed_cld : std_logic ;
   SIGNAL CmdRxed_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL Cmd_nData_cld : std_logic ;
   SIGNAL DBC_Accepted_cld : std_logic ;
   SIGNAL DataOut_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL DataReqFlag_cld : std_logic ;
   SIGNAL DataRxedFlag_cld : std_logic ;
   SIGNAL DataWrapActive_cld : std_logic ;
   SIGNAL InitiateBIT_Rxed_cld : std_logic ;
   SIGNAL ModeCmd_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL ModeData_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL NewModeCmd_cld : std_logic ;
   SIGNAL RxDataOut_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL RxDataWr_cld : std_logic ;
   SIGNAL SelTxShutdown_cld : std_logic ;
   SIGNAL SendWord_cld : std_logic ;
   SIGNAL ShutdownData_cld : std_logic_vector (4 DOWNTO 0);
   SIGNAL StatusRxed_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL StatusRxedFlag_cld : std_logic ;
   SIGNAL Sync_Rxed_cld : std_logic ;
   SIGNAL TxAvail_cld : std_logic ;
   SIGNAL TxDataRd_cld : std_logic ;
   SIGNAL TxShutdown_cld : std_logic ;
   SIGNAL inj_ParityError_cld : std_logic ;
   SIGNAL tmr_25us_Start_cld : std_logic ;
   SIGNAL tmr_25us_Stop_cld : std_logic ;
   SIGNAL tmr_GAP_Start_cld : std_logic ;
   SIGNAL tmr_GAP_Stop_cld : std_logic ;
   SIGNAL tmr_NRP_Start_cld : std_logic ;
   SIGNAL tmr_NRP_Stop_cld : std_logic ;
   SIGNAL tmr_REP_Start_cld : std_logic ;
   SIGNAL tmr_REP_Stop_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      Clk,
      nReset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (nReset = '0') THEN
         current_state <= sIdle;
         -- Default Reset Values
         BlankDecoder_cld <= '0';
         BusActive_cld <= '0';
         BusReset_Rxed_cld <= '0';
         CmdRxed_cld <= (others => '0');
         Cmd_nData_cld <= '0';
         DBC_Accepted_cld <= '0';
         DataOut_cld <= (others => '0');
         DataReqFlag_cld <= '0';
         DataRxedFlag_cld <= '0';
         DataWrapActive_cld <= '0';
         InitiateBIT_Rxed_cld <= '0';
         ModeCmd_cld <= (others => '0');
         ModeData_cld <= (others => '0');
         NewModeCmd_cld <= '0';
         RxDataOut_cld <= X"AAAA";
         RxDataWr_cld <= '0';
         SelTxShutdown_cld <= '0';
         SendWord_cld <= '0';
         ShutdownData_cld <= (others => '0');
         StatusRxed_cld <= (others=> '0');
         StatusRxedFlag_cld <= '0';
         Sync_Rxed_cld <= '0';
         TxAvail_cld <= '1';
         TxDataRd_cld <= '0';
         TxShutdown_cld <= '0';
         inj_ParityError_cld <= '0';
         tmr_25us_Start_cld <= '0';
         tmr_25us_Stop_cld <= '1';
         tmr_GAP_Start_cld <= '0';
         tmr_GAP_Stop_cld <= '1';
         tmr_NRP_Start_cld <= '0';
         tmr_NRP_Stop_cld <= '1';
         tmr_REP_Start_cld <= '0';
         tmr_REP_Stop_cld <= '1';
         Broadcast <= '0';
         ClrInhibitTFlag_Rxed <= '0';
         CmdCount <= 0;
         CmdWord <= (others => '0');
         DelayCount <= 0;
         InhibitTFlag_Rxed <= '0';
         LegalModeRxed <= '0';
         LegalSubAddrRxed <= '0';
         Len <= 0;
         MessageError <= '0';
         PrevCmdWord <= (others => '0');
         PrevStatus <= (others => '0');
         RT2RT <= '0';
         RT2RT_Busy <= '0';
         RT2RT_Flag <= '0';
         RT2RT_RxRtAddr <= (others => '1');
         RamWaitStates <= 0;
         ResetRt_Rxed <= '0';
         RtAddr <= (others => '0');
         RtLen_Mode <= (others => '0');
         RtSubAddr <= (others => '0');
         TxLastCommand <= '0';
         TxStatus_Rxed <= '0';
         Tx_nRx <= '0';
         WordCount <= 0;
         sWaitforStatusActive <= '0';
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         current_state <= next_state;
         -- Default Assignment To Internals
         ResetRt_Rxed <= '0';
         BusReset_Rxed_cld <= '0';
         DataReqFlag_cld <= '0';
         DataRxedFlag_cld <= '0';
         NewModeCmd_cld <= '0';
         RxDataWr_cld <= '0';
         StatusRxedFlag_cld <= '0';
         TxDataRd_cld <= '0';
         inj_ParityError_cld <= '0';
         tmr_25us_Start_cld <= '0';
         tmr_GAP_Start_cld <= '0';
         tmr_NRP_Start_cld <= '0';
         tmr_REP_Start_cld <= '0';
         -- Global Internal Actions
         if (Clear_Sync_Rxed = '1') then
           Sync_Rxed_cld <= '0';
         end if;
         if (Clear_InitiateBIT_Rxed = '1') then
           InitiateBIT_Rxed_cld <= '0';
         end if;

         -- Interrupts
         IF (tmr_SAF = '1') THEN
            SendWord_cld <= '0';
            WordCount <= 0;
            CmdCount <= 0;
            RtSubAddr <= "00000";
            tmr_GAP_Stop_cld <= '1';
            tmr_GAP_Start_cld <= '0';
            TxAvail_cld <= '1';
         ELSIF (newWord = '1' and Cmd_nDataIn = '1'   and IsRT = '1' and sWaitforStatusActive = '0') THEN
            sWaitforStatusActive <= '0';
            -- RX Command word decoding
            CmdRxed_cld <= Outword;
            RtAddr <= Outword(15 downto 11);
            Tx_nRx <= Outword(10);
            RtSubAddr <= Outword(9 downto 5);
            RtLen_Mode <= Outword(4 downto 0);
            CmdWord <= Outword;
            StatusRxedFlag_cld <= '0';
            if (RT2RT_busy = '1') then
              tmr_NRP_Start_cld <= '1';
              tmr_NRP_Stop_cld <= '1';
            end if;
         ELSIF (DecoderErr = '1') THEN
            SendWord_cld <= '0';
            WordCount <= 0;
            CmdCount <= 0;
            RtSubAddr <= "00000";
            tmr_GAP_Stop_cld <= '1';
            tmr_GAP_Start_cld <= '0';
            tmr_NRP_Start_cld<= '1';
            tmr_NRP_Stop_cld <= '1';
            
            TxAvail_cld <= '1';
            MessageError <= '1';
         ELSE

            -- Combined Actions
            CASE current_state IS
               WHEN sIdle => 
                  BusActive_cld <= '0';
                  IF (NewWord = '1' and Cmd_nDataIn = '1'  and IsRT = '1') THEN 
                     -- RX Command word decoding
                     CmdRxed_cld <= Outword;
                     RtAddr <= Outword(15 downto 11);
                     Tx_nRx <= Outword(10);
                     RtSubAddr <= Outword(9 downto 5);
                     RtLen_Mode <= Outword(4 downto 0);
                     CmdWord <= Outword;
                     StatusRxedFlag_cld <= '0';
                     if (RT2RT_busy = '1') then
                       tmr_NRP_Start_cld <= '1';
                       tmr_NRP_Stop_cld <= '1';
                     end if;
                  ELSIF ((tmr_NRP = '1' or CmdEdge = '1')) THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     if (RT2RT_busy = '1' and tmr_NRP = '1') then
                       RT2RT_Busy <= '0';
                     end if;
                  ELSE
                     tmr_REP_Stop_cld <= '1';
                  END IF;
               WHEN rtCheckLegal => 
                  IF (RtAddr /= MyRtAddr and Broadcast = '0') THEN 
                  ELSIF (RtAddr = "11111" and BroadcastEnable = '0') THEN 
                  ELSIF (Cmd_nDataIn = '1' and Tx_nRx = '0' and  
                         (RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and 
                         IsRt = '1') THEN 
                     BusActive_cld <= '1';
                     RT2RT_Flag <= '0';
                     sWaitforStatusActive <= '1';
                     WordCount <= 0;
                     PrevStatus <= Status;
                     if (RtLen_Mode = "00000") then
                       Len <= 32;
                     else
                       Len <= to_integer(unsigned(RtLen_Mode));
                     end if;
                     MessageError <= not LegalSubAddrRxed;
                     tmr_GAP_Stop_cld <= '1';
                     tmr_GAP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '0';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (Cmd_nDataIn = '1' and Tx_nRx = '1' and  
                         (RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and 
                         IsRt = '1') THEN 
                     BusActive_cld <= '1';
                     WordCount <= 0;
                     PrevStatus <= Status;
                     if (Err_Inj(3 downto 0) = "0110") then
                       if (Err_inj(15 downto 10) = "000001") then
                         if (RtLen_Mode = "00000") then
                             Len <= 31;
                         else
                             Len <= to_integer(unsigned(RtLen_Mode)) - 1;
                         end if;
                       elsif (Err_inj(15 downto 10) = "000010") then
                         if (RtLen_Mode = "00000") then
                             Len <= 33;
                         else
                             Len <= to_integer(unsigned(RtLen_Mode)) + 1;
                         end if;
                       else 
                         Len <= 16;
                       end if;
                     elsif (RtLen_Mode = "00000") then
                       Len <= 32;
                     else
                       Len <= to_integer(unsigned(RtLen_Mode));
                     end if;
                     MessageError <= not LegalSubAddrRxed;
                     DataReqFlag_cld <= '1';
                  ELSIF (Cmd_nDataIn = '1' and  (RtSubAddr = "00000"  or  RtSubAddr = "11111") and 
                         RtLen_Mode(4) = '0'  and IsRt = '1') THEN 
                     BusActive_cld <= '1';
                     WordCount <= 0;
                     if (LegalModeRxed = '1') then
                       ModeCmd_cld <= "00000000000" & RtLen_Mode;
                       NewModeCmd_cld <= '1';
                     end if;
                     NewModeCmd_cld <= '1';
                     MessageError <= not LegalModeRxed;
                  ELSIF (Cmd_nDataIn = '1' and Tx_nRx = '1' and  
                         (RtSubAddr = "00000"  or  RtSubAddr = "11111") and 
                         RtLen_Mode(4) = '1'  and IsRt = '1') THEN 
                     BusActive_cld <= '1';
                     WordCount <= 0;
                     if (LegalModeRxed = '1') then
                       ModeCmd_cld <= "00000000000" & RtLen_Mode;
                       NewModeCmd_cld <= '1';
                     end if;
                     NewModeCmd_cld <= '1';
                     MessageError <= not LegalModeRxed;
                  ELSIF (Cmd_nDataIn = '1' and Tx_nRx = '0' and  
                         (RtSubAddr = "00000"  or  RtSubAddr = "11111") and 
                         RtLen_Mode(4) = '1'  and IsRt = '1') THEN 
                     BusActive_cld <= '1';
                     WordCount <= 0;
                     PrevStatus <= Status;
                     if (LegalModeRxed = '1') then
                       ModeCmd_cld <= "00000000000" & RtLen_Mode;
                     end if;
                     MessageError <= not LegalModeRxed;
                     tmr_25us_Stop_cld <= '0';
                     tmr_25us_Start_cld <= '1';
                  END IF;
               WHEN rt2SendData => 
                  IF (tmr_REP = '1') THEN 
                     DataOut_cld <= Status;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                  END IF;
               WHEN rt2SendWords => 
                  IF (WordCount = Len and Done = '1') THEN 
                     SendWord_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     PrevStatus <= Status;
                     DataWrapActive_cld <= '0';
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (Done = '1') THEN 
                     WordCount <= WordCount + 1;
                     DataOut_cld <= TxDataIn(15 downto 0);
                     Cmd_nData_cld <= '0';
                     SendWord_cld <= '1';
                  END IF;
               WHEN rt2SendStatus => 
                  IF (Done = '1' and (MessageError = '1' or Len = 0)) THEN 
                     SendWord_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (Done = '1') THEN 
                     WordCount <= 1;
                     DataOut_cld <= TxDataIn(15 downto 0);
                     Cmd_nData_cld <= '0';
                     SendWord_cld <= '1';
                  END IF;
               WHEN rt1SendStatus => 
                  IF (Done = '1') THEN 
                     SendWord_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  END IF;
               WHEN rt1RxWords => 
                  IF (Broadcast = '1' and (WordCount+1) = Len) THEN 
                     MessageError <= not LegalSubAddrRxed;
                     PrevCmdWord <= CmdWord;
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     DataRxedFlag_cld <= '1';
                     RT2RT_Busy <= '0';
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  ELSIF ((WordCount+1) = Len) THEN 
                     tmr_REP_Stop_cld <= '0';
                     tmr_REP_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     MessageError <= not LegalSubAddrRxed;
                     DataRxedFlag_cld <= '1';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                     WordCount <= WordCount + 1;
                     tmr_25us_Start_cld <= '1';
                     if (LegalSubAddrRxed = '1') then 
                       RxDataOut_cld <= OutWord;
                       RxDataWr_cld <= '1';
                     end if;
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Start_cld<= '1';
                     tmr_25us_Stop_cld <= '1';
                     if (RT2RT_Busy = '1') then
                       RT2RT_Busy <= '0';
                     end if;
                     sWaitforStatusActive <= '0';
                     MessageError <= '1';
                  END IF;
               WHEN rt1Wait1stWord => 
                  IF (newWord = '1' and Cmd_nDataIn = '1' and Outword(15 downto 11) = MyRtAddr) THEN 
                     -- RX Command word decoding
                     CmdRxed_cld <= Outword;
                     RtAddr <= Outword(15 downto 11);
                     Tx_nRx <= Outword(10);
                     RtSubAddr <= Outword(9 downto 5);
                     RtLen_Mode <= Outword(4 downto 0);
                     PrevStatus <= Status;
                     CmdWord <= Outword;
                     sWaitforStatusActive <= '0';
                     StatusRxedFlag_cld <= '0';
                     tmr_REP_Stop_cld <= '0';
                     tmr_REP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '0';
                     tmr_GAP_Stop_cld <= '1';
                     tmr_GAP_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '1' and RT2RT_Flag = '0') THEN 
                     WordCount <= 0;
                     RT2RT_Busy <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                     --sWaitforStatusActive <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                     WordCount <= 0;
                     tmr_25us_Start_cld <= '1';
                     if (LegalSubAddrRxed = '1') then 
                       RxDataOut_cld <= OutWord;
                       RxDataWr_cld <= '1';
                     end if;
                     sWaitforStatusActive <= '0';
                     tmr_25us_Stop_cld <= '0';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Start_cld<= '1';
                     tmr_25us_Stop_cld <= '1';
                     if (RT2RT_Busy = '1') then
                       RT2RT_Busy <= '0';
                     end if;
                     sWaitforStatusActive <= '0';
                     MessageError <= '1';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                     tmr_25us_Stop_cld <= '0';
                     tmr_25us_Start_cld <= '1';
                  END IF;
               WHEN rt4Mode_Rx => 
                  case ModeCmd_cld(4 downto 0) is
                    when "00000" => DBC_Accepted_cld <= DBC_Enable and not Broadcast;PrevStatus <= Status;
                    when "00001" => Sync_Rxed_cld <= '1';PrevStatus <= Status;
                    when "00010" => TxStatus_Rxed <= '1';
                    when "00011" => InitiateBIT_Rxed_cld <= '1';PrevStatus <= Status;
                    when "00100" => TxShutdown_cld <= '1';PrevStatus <= Status;
                    when "00101" => TxShutdown_cld <= '0';PrevStatus <= Status;
                    when "00110" => InhibitTFlag_Rxed   <= '1';PrevStatus <= Status;
                    when "00111" => InhibitTFlag_Rxed   <= '0';PrevStatus <= Status;
                    when "10010" => TxLastCommand <= '1';
                    when others => Sync_Rxed_cld <= '0';
                                          TxStatus_Rxed <= '0';
                                          InitiateBIT_Rxed_cld <= '0';
                                          TxShutdown_cld <= '0';
                                           InhibitTFlag_Rxed   <= '0';
                  
                  end case;
               WHEN rt4SendStatus => 
                  IF (Done = '1') THEN 
                     SendWord_cld <= '0';
                     if (ModeCmd_cld(4 downto 0) = "01000") then
                       BusReset_Rxed_cld <= '1';
                     end if;
                     PrevCmdWord <= CmdWord;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  END IF;
               WHEN rt5ModeDatTx_Rx => 
                  tmr_REP_Start_cld <= '1';
                  tmr_REP_Stop_cld <= '0';
               WHEN rt5SendStatus => 
                  IF (Done = '1' and MessageError = '1') THEN 
                     SendWord_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (Done = '1') THEN 
                     WordCount <= WordCount + 1;
                     if (ModeCmd_cld(4 downto 0) = "10000") then
                       DataOut_cld <= ServiceReqVector;
                     elsif (ModeCmd_cld(4 downto 0) = "10010") then
                       DataOut_cld <= PrevCmdWord;
                     elsif (ModeCmd_cld(4 downto 0) = "10011") then
                       DataOut_cld <= BIT_word;
                     else
                       DataOut_cld <= TxDataIn(15 downto 0);
                     end if;
                     Cmd_nData_cld <= '0';
                     SendWord_cld <= '1';
                  END IF;
               WHEN rt5SendWord => 
                  IF (Done = '1') THEN 
                     SendWord_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  END IF;
               WHEN rt6ModeDatRx_Rx => 
                  IF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                     WordCount <= 0;
                     if (LegalModeRxed = '1') then
                       ModeData_cld <= OutWord;
                       NewModeCmd_cld <= '1';
                     end if;
                       tmr_REP_Stop_cld <= '0';
                       tmr_REP_Start_cld <= '1';
                     NewModeCmd_cld <= '1';
                     RxDataOut_cld <= OutWord;
                     RxDataWr_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Start_cld<= '1';
                     tmr_25us_Stop_cld <= '1';
                     if (RT2RT_Busy = '1') then
                       RT2RT_Busy <= '0';
                     end if;
                     sWaitforStatusActive <= '0';
                     MessageError <= '1';
                  END IF;
               WHEN rt6REPA => 
                  IF (BroadCast = '1') THEN 
                     case ModeCmd_cld(4 downto 0) is
                       when "10001" => Sync_Rxed_cld <= '1';
                       when "10100" => 
                       SelTxShutdown_cld <= '1';
                       ShutdownData_cld <= ModeData_cld(4 downto 0) ;
                       when "10101" => 
                       SelTxShutdown_cld <= '0';
                       ShutdownData_cld <= ModeData_cld(4 downto 0);
                       when others => Null;
                     end case;
                     tmr_REP_Stop_cld <= '1';
                     tmr_REP_Start_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  END IF;
               WHEN rt6SendStatus => 
                  IF (Done = '1') THEN 
                     SendWord_cld <= '0';
                     case ModeCmd_cld(4 downto 0) is
                       when "10001" => Sync_Rxed_cld <= '1';
                        when "10100" => 
                       SelTxShutdown_cld <= '1';
                       ShutdownData_cld <= ModeData_cld(4 downto 0);
                       when "10101" => 
                       SelTxShutdown_cld <= '0';
                       ShutdownData_cld <= ModeData_cld(4 downto 0);
                       when others => Null;
                     end case;
                     PrevCmdWord <= CmdWord;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  END IF;
               WHEN rtRxedCmd1 => 
                  LegalSubAddrRxed <= CheckLegalSubAddr(RtSubAddr,LegalSubAddr);
                  if (RtAddr = "11111" and BroadcastEnable = '1') then
                    Broadcast <= '1';
                    if (Tx_nRx = '0') then 
                      LegalModeRxed <= CheckLegalMode(RtLen_Mode,(LegalModeRx and LegalModeBrdcst));
                    else
                      LegalModeRxed <= CheckLegalMode(RtLen_Mode,(LegalModeTx and LegalModeBrdcst));
                    end if;
                  else
                    BroadCast <= '0';
                    if (Tx_nRx = '0') then 
                      LegalModeRxed <= CheckLegalMode(RtLen_Mode,LegalModeRx);
                    else
                      LegalModeRxed <= CheckLegalMode(RtLen_Mode,LegalModeTx);
                    end if;
                  end if;
                  DataRxedFlag_cld <= '0';
                  DataReqFlag_cld <= '0';
                  if ((DataWrapSubAddr = RtSubAddr) and (Tx_nRx = '1') and EnableHwDataWrap = '1') then
                    DataWrapActive_cld <= '1';
                  else
                    DataWrapActive_cld <= '0';
                  end if;
                  tmr_REP_Stop_cld <= '0';
                  tmr_REP_Start_cld <= '1';
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '1';
                  tmr_GAP_Stop_cld <= '1';
                  tmr_GAP_Start_cld <= '1';
                  tmr_25us_Stop_cld <= '1';
                  tmr_25us_Start_cld <= '1';
                  RT2RT_Flag <= '0';
                  DBC_Accepted_cld <= '0';
                  Sync_Rxed_cld <= '0';
                  TxStatus_Rxed <= '0';
                  TxLastCommand <= '0';
               WHEN rt4ModeResp => 
                  IF (Broadcast = '1') THEN 
                     if (ModeCmd_cld(4 downto 0) = "01000") then
                       BusReset_Rxed_cld <= '1';
                     end if;
                     PrevCmdWord <= CmdWord;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (tmr_REP = '1') THEN 
                     if (TxStatus_Rxed = '1') or (TxLastCommand = '1') then
                       DataOut_cld <= PrevStatus;
                     else
                       DataOut_cld <= Status;
                       PrevStatus <= Status;
                     end if;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                  END IF;
               WHEN rtNoBroadcast => 
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '1';
                  PrevStatus <= Status;
               WHEN rtWrngAddr => 
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '1';
                  PrevStatus <= Status;
               WHEN rt1REP_B => 
                  IF (PosEdge = '1') THEN 
                     SendWord_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     tmr_REP_Stop_cld <= '1';
                     tmr_REP_Start_cld <= '0';
                     WordCount <= 0;
                     CmdCount <= 0;
                     RtSubAddr <= "00000";
                     TxAvail_cld <= '1';
                     MessageError <= '1';
                  ELSIF (tmr_REP = '1') THEN 
                     DataOut_cld <= Status;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                  END IF;
               WHEN rt6REPB => 
                  IF (PosEdge = '1') THEN 
                     SendWord_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     tmr_REP_Stop_cld <= '1';
                     tmr_REP_Start_cld <= '1';
                     WordCount <= 0;
                     CmdCount <= 0;
                     RtSubAddr <= "00000";
                     TxAvail_cld <= '1';
                     MessageError <= '1';
                  ELSIF (tmr_REP = '1') THEN 
                     DataOut_cld <= Status;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     tmr_REP_Start_cld <= '1';
                  END IF;
               WHEN rt1RT2RT_transition => 
                  IF (Tx_nRx = '1' and  (RtSubAddr /= "00000"  and  RtSubAddr /= "11111")) THEN 
                     WordCount <= 0;
                     if (RtLen_Mode = "00000") then
                       Len <= 32;
                     else
                       Len <= to_integer(unsigned(RtLen_Mode));
                     end if;
                     MessageError <= not LegalSubAddrRxed;
                     DataReqFlag_cld <= '1';
                  END IF;
               WHEN rtRxGap => 
                  IF (tmr_Gap = '1') THEN 
                     WordCount <= 0;
                     CmdCount <= 0;
                     RtSubAddr <= "00000";
                     tmr_GAP_Stop_cld <= '1';
                     tmr_GAP_Start_cld <= '0';
                     TxAvail_cld <= '1';
                  END IF;
               WHEN rt1ScndCmdWord => 
                  IF (tmr_NRP = '1') THEN 
                     tmr_NRP_Start_cld<= '1';
                     tmr_NRP_Stop_cld <= '1';
                     if (RT2RT_Busy = '1') then
                       RT2RT_Busy <= '0';
                     else
                       MessageError <= '1';
                     end if;
                  ELSIF (CmdEdge = '1' and RT2RT_Flag = '0') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     Rt2RT_Flag <= '1';
                     tmr_25us_Stop_cld <= '0';
                     tmr_25us_Start_cld <= '1';
                  END IF;
               WHEN rt1CaptureStatus => 
                  PrevStatus <= Status;
               WHEN rt6CaptureStatus => 
                  PrevStatus <= Status;
               WHEN rt5REPB => 
                  IF (tmr_REP = '1') THEN 
                     if ModeCmd_cld(4 downto 0) = "10010"  then
                       DataOut_cld <= PrevStatus;
                     else
                       DataOut_cld <= Status;
                     end if;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     tmr_REP_Start_cld <= '1';
                  ELSIF (PosEdge = '1') THEN 
                     SendWord_cld <= '0';
                     PrevCmdWord <= CmdWord;
                     tmr_REP_Stop_cld <= '1';
                     tmr_REP_Start_cld <= '1';
                     WordCount <= 0;
                     CmdCount <= 0;
                     RtSubAddr <= "00000";
                     TxAvail_cld <= '1';
                     MessageError <= '1';
                  END IF;
               WHEN rt5CaptureStatus => 
                  PrevStatus <= Status;
               WHEN s0 => 
                  IF (NewWord = '1' and Cmd_nDataIn = '0'  and IsRT = '1') THEN 
                     -- force the message error bit high in previous status 
                     -- due to unexpected data word, probably due to to many data word sent by BC
                     PrevStatus <= PrevStatus(15 downto 11) & '1' & PrevStatus(9 downto 0);
                  END IF;
               WHEN OTHERS =>
                  NULL;
            END CASE;
         END IF;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      Broadcast,
      BroadcastEnable,
      CmdEdge,
      Cmd_nDataIn,
      DecoderErr,
      Done,
      IsRT,
      Len,
      MessageError,
      MyRtAddr,
      NewWord,
      OutWord,
      PosEdge,
      RT2RT_Flag,
      RtAddr,
      RtLen_Mode,
      RtSubAddr,
      Tx_nRx,
      WordCount,
      current_state,
      sWaitforStatusActive,
      tmr_25us,
      tmr_GAP,
      tmr_NRP,
      tmr_REP,
      tmr_SAF
   )
   -----------------------------------------------------------------
   BEGIN

      -- Interrupts
      IF (tmr_SAF = '1') THEN
         next_state <= sIdle;
      ELSIF (newWord = '1' and Cmd_nDataIn = '1'   and IsRT = '1' and sWaitforStatusActive = '0') THEN
         next_state <= rtRxedCmd1;
      ELSIF (DecoderErr = '1') THEN
         next_state <= rt1CaptureStatus;
      ELSE
         CASE current_state IS
            WHEN sIdle => 
               IF (NewWord = '1' and Cmd_nDataIn = '1'  and IsRT = '1') THEN 
                  next_state <= rtRxedCmd1;
               ELSIF ((tmr_NRP = '1' or CmdEdge = '1')) THEN 
                  next_state <= sClrNRP;
               ELSE
                  next_state <= sIdle;
               END IF;
            WHEN rtCheckLegal => 
               IF (RtAddr /= MyRtAddr and Broadcast = '0') THEN 
                  next_state <= rtWrngAddr;
               ELSIF (RtAddr = "11111" and BroadcastEnable = '0') THEN 
                  next_state <= rtNoBroadcast;
               ELSIF (Cmd_nDataIn = '1' and Tx_nRx = '0' and  
                      (RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and 
                      IsRt = '1') THEN 
                  next_state <= rt1Wait1stWord;
               ELSIF (Cmd_nDataIn = '1' and Tx_nRx = '1' and  
                      (RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and 
                      IsRt = '1') THEN 
                  next_state <= rt2SendData;
               ELSIF (Cmd_nDataIn = '1' and  (RtSubAddr = "00000"  or  RtSubAddr = "11111") and 
                      RtLen_Mode(4) = '0'  and IsRt = '1') THEN 
                  next_state <= rt4Mode_Rx;
               ELSIF (Cmd_nDataIn = '1' and Tx_nRx = '1' and  
                      (RtSubAddr = "00000"  or  RtSubAddr = "11111") and 
                      RtLen_Mode(4) = '1'  and IsRt = '1') THEN 
                  next_state <= rt5ModeDatTx_Rx;
               ELSIF (Cmd_nDataIn = '1' and Tx_nRx = '0' and  
                      (RtSubAddr = "00000"  or  RtSubAddr = "11111") and 
                      RtLen_Mode(4) = '1'  and IsRt = '1') THEN 
                  next_state <= rt6ModeDatRx_Rx;
               ELSE
                  next_state <= rtCheckLegal;
               END IF;
            WHEN rt2SendData => 
               IF (tmr_REP = '1') THEN 
                  next_state <= rt2SendStatus;
               ELSE
                  next_state <= rt2SendData;
               END IF;
            WHEN rt2SendWords => 
               IF (WordCount = Len and Done = '1') THEN 
                  next_state <= rtRxGap;
               ELSIF (Done = '1') THEN 
                  next_state <= rt2SendWords;
               ELSE
                  next_state <= rt2SendWords;
               END IF;
            WHEN rt2SendStatus => 
               IF (Done = '1' and (MessageError = '1' or Len = 0)) THEN 
                  next_state <= rtRxGap;
               ELSIF (Done = '1') THEN 
                  next_state <= rt2SendWords;
               ELSE
                  next_state <= rt2SendStatus;
               END IF;
            WHEN rt1SendStatus => 
               IF (Done = '1') THEN 
                  next_state <= rtRxGap;
               ELSE
                  next_state <= rt1SendStatus;
               END IF;
            WHEN rt1RxWords => 
               IF (Broadcast = '1' and (WordCount+1) = Len) THEN 
                  next_state <= rtRxGap;
               ELSIF ((WordCount+1) = Len) THEN 
                  next_state <= rt1REP_A;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                  next_state <= rt1RxWords;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= rt1CaptureStatus;
               ELSE
                  next_state <= rt1RxWords;
               END IF;
            WHEN rt1REP_A => 
               IF (tmr_REP = '0') THEN 
                  next_state <= rt1REP_B;
               ELSE
                  next_state <= rt1REP_A;
               END IF;
            WHEN rt1Wait1stWord => 
               IF (newWord = '1' and Cmd_nDataIn = '1' and Outword(15 downto 11) = MyRtAddr) THEN 
                  next_state <= rt1RT2RT_transition;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '1' and RT2RT_Flag = '0') THEN 
                  next_state <= rt1ScndCmdWord;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                  next_state <= rt1RxWords;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= rt1CaptureStatus;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                  next_state <= rt1Wait1stWord;
               ELSE
                  next_state <= rt1Wait1stWord;
               END IF;
            WHEN rt4Mode_Rx => 
               next_state <= rt4ModeResp;
            WHEN rt4SendStatus => 
               IF (Done = '1') THEN 
                  next_state <= rtRxGap;
               ELSE
                  next_state <= rt4SendStatus;
               END IF;
            WHEN rt5ModeDatTx_Rx => 
               next_state <= rt5REPA;
            WHEN rt5SendStatus => 
               IF (Done = '1' and MessageError = '1') THEN 
                  next_state <= rtRxGap;
               ELSIF (Done = '1') THEN 
                  next_state <= rt5SendWord;
               ELSE
                  next_state <= rt5SendStatus;
               END IF;
            WHEN rt5SendWord => 
               IF (Done = '1') THEN 
                  next_state <= rtRxGap;
               ELSE
                  next_state <= rt5SendWord;
               END IF;
            WHEN rt6ModeDatRx_Rx => 
               IF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                  next_state <= rt6REPA;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= rt6CaptureStatus;
               ELSE
                  next_state <= rt6ModeDatRx_Rx;
               END IF;
            WHEN rt6REPA => 
               IF (BroadCast = '1') THEN 
                  next_state <= rtRxGap;
               ELSIF (tmr_REP = '0') THEN 
                  next_state <= rt6REPB;
               ELSE
                  next_state <= rt6REPA;
               END IF;
            WHEN rt6SendStatus => 
               IF (Done = '1') THEN 
                  next_state <= rtRxGap;
               ELSE
                  next_state <= rt6SendStatus;
               END IF;
            WHEN rtRxedCmd1 => 
               next_state <= rtCheckLegal;
            WHEN rt4ModeResp => 
               IF (Broadcast = '1') THEN 
                  next_state <= rtRxGap;
               ELSIF (tmr_REP = '1') THEN 
                  next_state <= rt4SendStatus;
               ELSE
                  next_state <= rt4ModeResp;
               END IF;
            WHEN rtNoBroadcast => 
               next_state <= rtRxGap;
            WHEN rtWrngAddr => 
               next_state <= rtRxGap;
            WHEN rt1REP_B => 
               IF (PosEdge = '1') THEN 
                  next_state <= rt1CaptureStatus;
               ELSIF (tmr_REP = '1') THEN 
                  next_state <= rt1SendStatus;
               ELSE
                  next_state <= rt1REP_B;
               END IF;
            WHEN rt6REPB => 
               IF (PosEdge = '1') THEN 
                  next_state <= rt6CaptureStatus;
               ELSIF (tmr_REP = '1') THEN 
                  next_state <= rt6SendStatus;
               ELSE
                  next_state <= rt6REPB;
               END IF;
            WHEN rt1RT2RT_transition => 
               IF (Tx_nRx = '1' and  (RtSubAddr /= "00000"  and  RtSubAddr /= "11111")) THEN 
                  next_state <= rt2SendData;
               ELSE
                  next_state <= rt1RT2RT_transition;
               END IF;
            WHEN rtRxGap => 
               IF (tmr_Gap = '1') THEN 
                  next_state <= sIdle;
               ELSE
                  next_state <= rtRxGap;
               END IF;
            WHEN rt1ScndCmdWord => 
               IF (tmr_NRP = '1') THEN 
                  next_state <= rt1CaptureStatus;
               ELSIF (CmdEdge = '1' and RT2RT_Flag = '0') THEN 
                  next_state <= rt1Wait1stWord;
               ELSE
                  next_state <= rt1ScndCmdWord;
               END IF;
            WHEN sClrNRP => 
               next_state <= sIdle;
            WHEN rt1CaptureStatus => 
               next_state <= sIdle;
            WHEN rt6CaptureStatus => 
               next_state <= sIdle;
            WHEN rt5REPB => 
               IF (tmr_REP = '1') THEN 
                  next_state <= rt5SendStatus;
               ELSIF (PosEdge = '1') THEN 
                  next_state <= rt5CaptureStatus;
               ELSE
                  next_state <= rt5REPB;
               END IF;
            WHEN rt5CaptureStatus => 
               next_state <= sIdle;
            WHEN rt5REPA => 
               IF (tmr_REP = '0') THEN 
                  next_state <= rt5REPB;
               ELSE
                  next_state <= rt5REPA;
               END IF;
            WHEN s0 => 
               IF (NewWord = '1' and Cmd_nDataIn = '0'  and IsRT = '1') THEN 
                  next_state <= sIdle;
               ELSE
                  next_state <= s0;
               END IF;
            WHEN OTHERS =>
               next_state <= sIdle;
         END CASE;
      END IF;
   END PROCESS nextstate_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   BlankDecoder <= BlankDecoder_cld;
   BusActive <= BusActive_cld;
   BusReset_Rxed <= BusReset_Rxed_cld;
   CmdRxed <= CmdRxed_cld;
   Cmd_nData <= Cmd_nData_cld;
   DBC_Accepted <= DBC_Accepted_cld;
   DataOut <= DataOut_cld;
   DataReqFlag <= DataReqFlag_cld;
   DataRxedFlag <= DataRxedFlag_cld;
   DataWrapActive <= DataWrapActive_cld;
   InitiateBIT_Rxed <= InitiateBIT_Rxed_cld;
   ModeCmd <= ModeCmd_cld;
   ModeData <= ModeData_cld;
   NewModeCmd <= NewModeCmd_cld;
   RxDataOut <= RxDataOut_cld;
   RxDataWr <= RxDataWr_cld;
   SelTxShutdown <= SelTxShutdown_cld;
   SendWord <= SendWord_cld;
   ShutdownData <= ShutdownData_cld;
   StatusRxed <= StatusRxed_cld;
   StatusRxedFlag <= StatusRxedFlag_cld;
   Sync_Rxed <= Sync_Rxed_cld;
   TxAvail <= TxAvail_cld;
   TxDataRd <= TxDataRd_cld;
   TxShutdown <= TxShutdown_cld;
   inj_ParityError <= inj_ParityError_cld;
   tmr_25us_Start <= tmr_25us_Start_cld;
   tmr_25us_Stop <= tmr_25us_Stop_cld;
   tmr_GAP_Start <= tmr_GAP_Start_cld;
   tmr_GAP_Stop <= tmr_GAP_Stop_cld;
   tmr_NRP_Start <= tmr_NRP_Start_cld;
   tmr_NRP_Stop <= tmr_NRP_Stop_cld;
   tmr_REP_Start <= tmr_REP_Start_cld;
   tmr_REP_Stop <= tmr_REP_Stop_cld;
   TxDataAddr <= RtSubAddr & RtLen_Mode when (RtSubAddr = "11111") else
                           --"11111" & RtLen_Mode when (RtSubAddr = "00000") else
                             RtSubAddr & std_logic_vector(to_unsigned(WordCount,5));
   RxDataAddr <= RtSubAddr & RtLen_Mode when  (RtSubAddr = "11111" ) else
                           "11111" & RtLen_Mode when (RtSubAddr = "00000") else
                             RtSubAddr & std_logic_vector(to_unsigned(WordCount,5));
   TerminalFlag <= TerminalFlagIn and not(InhibitTFlag_Rxed );
   Status <= MyRtAddr & (MessageError or DecoderErr) & Instrumentation & ServiceRequest & "000" & 
   Broadcast & Busy & SubsystemFlag & DBC_Accepted_cld & TerminalFlag;
END fsm;
