-- VHDL Entity mil1553_lib.mil1553_framer_bc.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (jeansmithE313)
--          at - 08:15:00 16/01/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY mil1553_framer_bc IS
   PORT( 
      BIT_word               : IN     std_logic_vector (15 DOWNTO 0);
      BrdcstRxed             : IN     std_logic;
      BroadcastEnable        : IN     std_logic;
      Busy                   : IN     std_logic;
      Clear_InitiateBIT_Rxed : IN     std_logic;
      Clear_Sync_Rxed        : IN     std_logic;
      Clk                    : IN     std_logic;
      CmdEdge                : IN     std_logic;
      CmdProcLen             : IN     std_logic_vector (15 DOWNTO 0);
      CmdProcStart           : IN     std_logic_vector (15 DOWNTO 0);
      Cmd_nDataIn            : IN     std_logic;
      DBC_Enable             : IN     std_logic;
      DataWrapSubAddr        : IN     std_logic_vector (4 DOWNTO 0);
      DecoderErr             : IN     std_logic;
      Done                   : IN     std_logic;
      EnableHwDataWrap       : IN     std_logic;
      Err_inj                : IN     std_logic_vector (15 DOWNTO 0);
      Instrumentation        : IN     std_logic;
      IsRT                   : IN     std_logic;
      LegalModeBrdcst        : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeRx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeTx            : IN     std_logic_vector (31 DOWNTO 0);
      LegalSubAddr           : IN     std_logic_vector (31 DOWNTO 0);
      MyRtAddr               : IN     std_logic_vector (4 DOWNTO 0);
      NegEdge                : IN     std_logic;
      NewWord                : IN     std_logic;
      OutWord                : IN     std_logic_vector (15 DOWNTO 0);
      PosEdge                : IN     std_logic;
      SendMessage            : IN     std_logic;
      ServiceReqVector       : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest         : IN     std_logic;
      SubsystemFlag          : IN     std_logic;
      TerminalFlagIn         : IN     std_logic;
      TxDataIn               : IN     std_logic_vector (16 DOWNTO 0);
      nReset                 : IN     std_logic;
      tmr_1us                : IN     std_logic;
      tmr_25us               : IN     std_logic;
      tmr_GAP                : IN     std_logic;
      tmr_NRP                : IN     std_logic;
      tmr_REP                : IN     std_logic;
      tmr_SAF                : IN     std_logic;
      BlankDecoder           : OUT    std_logic;
      BusActive              : OUT    std_logic;
      BusReset_Rxed          : OUT    std_logic;
      CmdRxed                : OUT    std_logic_vector (15 DOWNTO 0);
      Cmd_nData              : OUT    std_logic;
      DBC_Accepted           : OUT    std_logic;
      DataOut                : OUT    std_logic_vector (15 DOWNTO 0);
      DataReqFlag            : OUT    std_logic;
      DataRxedFlag           : OUT    std_logic;
      DataWrapActive         : OUT    std_logic;
      InitiateBIT_Rxed       : OUT    std_logic;
      ModeCmd                : OUT    std_logic_vector (15 DOWNTO 0);
      ModeData               : OUT    std_logic_vector (15 DOWNTO 0);
      NewModeCmd             : OUT    std_logic;
      RxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      RxDataOut              : OUT    std_logic_vector (15 DOWNTO 0);
      RxDataWr               : OUT    std_logic;
      SelTxShutdown          : OUT    std_logic;
      SendWord               : OUT    std_logic;
      ShutdownData           : OUT    std_logic_vector (4 DOWNTO 0);
      StatusRxed             : OUT    std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag         : OUT    std_logic;
      Sync_Rxed              : OUT    std_logic;
      TxAvail                : OUT    std_logic;
      TxDataAddr             : OUT    std_logic_vector (9 DOWNTO 0);
      TxDataRd               : OUT    std_logic;
      TxShutdown             : OUT    std_logic;
      inj_ParityError        : OUT    std_logic;
      tmr_25us_Start         : OUT    std_logic;
      tmr_25us_Stop          : OUT    std_logic;
      tmr_GAP_Start          : OUT    std_logic;
      tmr_GAP_Stop           : OUT    std_logic;
      tmr_NRP_Start          : OUT    std_logic;
      tmr_NRP_Stop           : OUT    std_logic;
      tmr_REP_Start          : OUT    std_logic;
      tmr_REP_Stop           : OUT    std_logic;
      TerminalFlag           : BUFFER std_logic
   );

-- Declarations

END mil1553_framer_bc ;

--
-- VHDL Architecture mil1553_lib.mil1553_framer_bc.fsm
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 15:08:07 02/16/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
 
ARCHITECTURE fsm OF mil1553_framer_bc IS

   -- Architecture Declarations
   -- Status bits generated in FSM
   signal MessageError : std_logic;
   signal sWaitforStatusActive : std_logic;
   ---------------------------------
   signal TxStatus_Rxed : std_logic;
   signal TxLastCommand : std_logic;
   signal InhibitTFlag_Rxed : std_logic;
   signal ClrInhibitTFlag_Rxed : std_logic;
   signal ResetRt_Rxed : std_logic;
   signal Broadcast : std_logic;
   signal WordCount : integer range 0 to 34;
   signal CmdCount : integer range 0 to 32;
   signal DelayCount : integer;
   signal Len : integer range 0 to 33;
   signal LegalModeRxed : std_logic;
   signal LegalSubAddrRxed : std_logic;
   signal PrevStatus : std_logic_vector(15 downto 0);
   signal PrevCmdWord : std_logic_vector(15 downto 0);
   signal CmdWord : std_logic_vector(15 downto 0);
   signal RtAddr : std_logic_vector(4 downto 0);
   signal RtSubAddr : std_logic_vector(4 downto 0);
   signal RamWaitStates : integer range 0 to 3;
   signal RtLen_Mode : std_logic_vector(4 downto 0);
   signal Tx_nRx : std_logic;
   signal RT2RT : std_logic;
   signal RT2RT_Busy : std_logic;
   signal RT2RT_RxRtAddr : std_logic_vector(4 downto 0);
   signal Status : std_logic_vector(15 downto 0);
   signal RT2RT_Flag : std_logic;
   function CheckLegalMode(RtLen_Mode : std_logic_vector(4 downto 0); LegalMode :  std_logic_vector(31 downto 0)) return std_logic is
   variable Count : integer range 0 to 31;
   begin
     Count := to_integer(unsigned(RtLen_Mode));
     return LegalMode(Count);
   end function;
   
   function CheckLegalSubaddr (RtSubAddr : std_logic_vector(4 downto 0); LegalSubAddr :  std_logic_vector(31 downto 0)) return std_logic is
   variable Count : integer range 0 to 31;
   begin
     if (RtSubAddr /= "00000" and RtSubAddr /= "11111")  then 
       Count := to_integer(unsigned(RtSubAddr));
       return LegalSubAddr(Count);
     else
       return '0';
     End if;
   end function;
   function BcLegalMode(RtSubAddr: std_logic_vector(4 downto 0); RtLenMode : std_logic_vector(4 downto 0);Tx_nRx : std_logic) return std_logic is
   begin
   if (RtSubAddr = "00000" or RtSubAddr = "11111") then 
   if (RtLenMode(4) = '0') then
     if (Tx_nRx = '0') then
       return '0';
     else
       case RtLenMode(3 downto 0) is
         when X"9" => return '0';
         when X"A" => return '0';
         when X"B" => return '0';
         when X"C" => return '0';
         when X"D" => return '0';
         when X"E" => return '0';
         when X"F" => return '0';
         when others => return '1';
       end case;
     end if;
   else
     if (Tx_nRx = '0') then
       case RtLenMode(3 downto 0) is
         when X"1" => return '1';
         when X"4" => return '1';
         when X"5" => return '1';
         when others => return '0';
       end case;
     else
       case RtLenMode(3 downto 0) is
         when X"0" => return '1';
         when X"2" => return '1';
         when X"3" => return '1';
         when others => return '0';
       end case;
     end if;
   end if;
   else
    return '0';
   end if;
   end function;

   TYPE STATE_TYPE IS (
      bcStartCmd,
      bc3RTRT,
      sIdle,
      bcGetCmd,
      bcTxGap,
      rtRxedCmd1,
      bcCheckRtAddr,
      sClrNRP,
      bc2SendCw,
      bc2NRP,
      bc2StatusRx,
      bc2DataRx,
      bc2CmdDone,
      bc1SendCw,
      bc1SendData,
      bc1WaitForStatus,
      bc1NRP,
      bc1WordTimeout,
      bc5SendCw1,
      bc5NRP,
      bc5StatusRx,
      bc5CmdDone,
      bc6SendCw,
      bc6SendData,
      bc6WaitForStatus,
      bc6NRP,
      bc6WordTimeout,
      bc4SendCw,
      bc4WaitForStatus,
      bc4NRP,
      bc4WordTimeout,
      bc3SendCw,
      bc3CmdDone,
      bc3NRP,
      bc3StatusRx,
      bc3DataRx,
      bc3StatusRx2,
      bc4SendWord,
      bc5SendWord,
      bcPreMsgTxGap,
      bc1SendWord1,
      s0,
      s1
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare any pre-registered internal signals
   SIGNAL BlankDecoder_cld : std_logic ;
   SIGNAL BusActive_cld : std_logic ;
   SIGNAL BusReset_Rxed_cld : std_logic ;
   SIGNAL CmdRxed_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL Cmd_nData_cld : std_logic ;
   SIGNAL DBC_Accepted_cld : std_logic ;
   SIGNAL DataOut_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL DataReqFlag_cld : std_logic ;
   SIGNAL DataRxedFlag_cld : std_logic ;
   SIGNAL DataWrapActive_cld : std_logic ;
   SIGNAL InitiateBIT_Rxed_cld : std_logic ;
   SIGNAL ModeCmd_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL ModeData_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL NewModeCmd_cld : std_logic ;
   SIGNAL RxDataOut_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL RxDataWr_cld : std_logic ;
   SIGNAL SelTxShutdown_cld : std_logic ;
   SIGNAL SendWord_cld : std_logic ;
   SIGNAL ShutdownData_cld : std_logic_vector (4 DOWNTO 0);
   SIGNAL StatusRxed_cld : std_logic_vector (15 DOWNTO 0);
   SIGNAL StatusRxedFlag_cld : std_logic ;
   SIGNAL Sync_Rxed_cld : std_logic ;
   SIGNAL TxAvail_cld : std_logic ;
   SIGNAL TxDataRd_cld : std_logic ;
   SIGNAL TxShutdown_cld : std_logic ;
   SIGNAL inj_ParityError_cld : std_logic ;
   SIGNAL tmr_25us_Start_cld : std_logic ;
   SIGNAL tmr_25us_Stop_cld : std_logic ;
   SIGNAL tmr_GAP_Start_cld : std_logic ;
   SIGNAL tmr_GAP_Stop_cld : std_logic ;
   SIGNAL tmr_NRP_Start_cld : std_logic ;
   SIGNAL tmr_NRP_Stop_cld : std_logic ;
   SIGNAL tmr_REP_Start_cld : std_logic ;
   SIGNAL tmr_REP_Stop_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      Clk,
      nReset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (nReset = '0') THEN
         current_state <= sIdle;
         -- Default Reset Values
         BlankDecoder_cld <= '0';
         BusActive_cld <= '0';
         BusReset_Rxed_cld <= '0';
         CmdRxed_cld <= (others => '0');
         Cmd_nData_cld <= '0';
         DBC_Accepted_cld <= '0';
         DataOut_cld <= (others => '0');
         DataReqFlag_cld <= '0';
         DataRxedFlag_cld <= '0';
         DataWrapActive_cld <= '0';
         InitiateBIT_Rxed_cld <= '0';
         ModeCmd_cld <= (others => '0');
         ModeData_cld <= (others => '0');
         NewModeCmd_cld <= '0';
         RxDataOut_cld <= X"AAAA";
         RxDataWr_cld <= '0';
         SelTxShutdown_cld <= '0';
         SendWord_cld <= '0';
         ShutdownData_cld <= (others => '0');
         StatusRxed_cld <= (others=> '0');
         StatusRxedFlag_cld <= '0';
         Sync_Rxed_cld <= '0';
         TxAvail_cld <= '1';
         TxDataRd_cld <= '0';
         TxShutdown_cld <= '0';
         inj_ParityError_cld <= '0';
         tmr_25us_Start_cld <= '0';
         tmr_25us_Stop_cld <= '1';
         tmr_GAP_Start_cld <= '0';
         tmr_GAP_Stop_cld <= '1';
         tmr_NRP_Start_cld <= '0';
         tmr_NRP_Stop_cld <= '1';
         tmr_REP_Start_cld <= '0';
         tmr_REP_Stop_cld <= '1';
         Broadcast <= '0';
         ClrInhibitTFlag_Rxed <= '0';
         CmdCount <= 0;
         CmdWord <= (others => '0');
         DelayCount <= 0;
         InhibitTFlag_Rxed <= '0';
         LegalModeRxed <= '0';
         LegalSubAddrRxed <= '0';
         Len <= 0;
         MessageError <= '0';
         PrevCmdWord <= (others => '0');
         PrevStatus <= (others => '0');
         RT2RT <= '0';
         RT2RT_Busy <= '0';
         RT2RT_Flag <= '0';
         RT2RT_RxRtAddr <= (others => '1');
         RamWaitStates <= 0;
         ResetRt_Rxed <= '0';
         RtAddr <= (others => '0');
         RtLen_Mode <= (others => '0');
         RtSubAddr <= (others => '0');
         TxLastCommand <= '0';
         TxStatus_Rxed <= '0';
         Tx_nRx <= '0';
         WordCount <= 0;
         sWaitforStatusActive <= '0';
      ELSIF (Clk'EVENT AND Clk = '1') THEN
         current_state <= next_state;
         -- Default Assignment To Internals
         ResetRt_Rxed <= '0';
         BusReset_Rxed_cld <= '0';
         DataReqFlag_cld <= '0';
         DataRxedFlag_cld <= '0';
         NewModeCmd_cld <= '0';
         RxDataWr_cld <= '0';
         StatusRxedFlag_cld <= '0';
         TxDataRd_cld <= '0';
         inj_ParityError_cld <= '0';
         tmr_25us_Start_cld <= '0';
         tmr_GAP_Start_cld <= '0';
         tmr_NRP_Start_cld <= '0';
         tmr_REP_Start_cld <= '0';
         -- Global Internal Actions
         if (Clear_Sync_Rxed = '1') then
           Sync_Rxed_cld <= '0';
         end if;
         if (Clear_InitiateBIT_Rxed = '1') then
           InitiateBIT_Rxed_cld <= '0';
         end if;

         -- Interrupts
         IF (tmr_SAF = '1') THEN
            SendWord_cld <= '0';
            WordCount <= 0;
            CmdCount <= 0;
            RtSubAddr <= "00000";
            tmr_GAP_Stop_cld <= '1';
            tmr_GAP_Start_cld <= '0';
            TxAvail_cld <= '1';
         ELSIF (SendMessage = '1' and BusActive_cld = '1') THEN
            tmr_NRP_Stop_cld <= '1';
            tmr_NRP_Start_cld <= '1';
            tmr_GAP_Start_cld <= '1';
            tmr_GAP_Stop_cld <= '0';
            SendWord_cld <= '0';
            WordCount <= 0;
            CmdCount <= 0;
            RtSubAddr <= "00000";
         ELSIF (newWord = '1' and Cmd_nDataIn = '1'   and IsRT = '1' and sWaitforStatusActive = '0') THEN
            sWaitforStatusActive <= '0';
            -- RX Command word decoding
            CmdRxed_cld <= Outword;
            RtAddr <= Outword(15 downto 11);
            Tx_nRx <= Outword(10);
            RtSubAddr <= Outword(9 downto 5);
            RtLen_Mode <= Outword(4 downto 0);
            CmdWord <= Outword;
            StatusRxedFlag_cld <= '0';
            if (RT2RT_busy = '1') then
              tmr_NRP_Start_cld <= '1';
              tmr_NRP_Stop_cld <= '1';
            end if;
         ELSE

            -- Combined Actions
            CASE current_state IS
               WHEN bcStartCmd => 
                  IF ((RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and RT2RT = '1') THEN 
                     if (RtAddr = "11111" and BroadcastEnable = '1') then
                       Broadcast <= '1';
                     else
                       BroadCast <= '0';
                     end if;
                     DataOut_cld <= RTAddr & Tx_nRx & RtSubAddr & RtLen_Mode;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                  ELSIF ((RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and Tx_nRx = '1' and RT2RT_Busy = '1') THEN 
                     DataOut_cld <= RTAddr & Tx_nRx & RtSubAddr & RtLen_Mode;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     if (RtLen_Mode = "00000") then
                       Len <= 32;
                     else
                       Len <= to_integer(unsigned(RtLen_Mode));
                     end if;
                  ELSIF ((RtSubAddr = "00000"  or  RtSubAddr = "11111") and RtLen_Mode(4) = '0') THEN 
                     DataOut_cld <= RTAddr & Tx_nRx & RtSubAddr & RtLen_Mode;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                  ELSIF ((RtSubAddr = "00000"  or  RtSubAddr = "11111") and Tx_nRx = '1' and RtLen_Mode(4) = '1') THEN 
                     DataOut_cld <= RTAddr & Tx_nRx & RtSubAddr & RtLen_Mode;
                     if (RtSubAddr = "00000") then
                       RtSubAddr <= "11111";
                     end if;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     Len <= 1;
                  ELSIF ((RtSubAddr = "00000"  or  RtSubAddr = "11111") and Tx_nRx = '0'  and RtLen_Mode(4) = '1') THEN 
                     DataOut_cld <= RTAddr & Tx_nRx & RtSubAddr & RtLen_Mode;
                     if (RtSubAddr = "00000") then
                       RtSubAddr <= "11111";
                     end if;
                     if (RtLen_Mode = "00000") then
                       Len <= 32;
                     else
                       Len <= to_integer(unsigned(RtLen_Mode));
                     end if;
                     
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                  ELSIF ((RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and Tx_nRx = '0') THEN 
                     DataOut_cld <= RTAddr & Tx_nRx & RtSubAddr & RtLen_Mode;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     if (RtLen_Mode = "00000") then
                       Len <= 32;
                     else
                       Len <= to_integer(unsigned(RtLen_Mode));
                     end if;
                     WordCount <= 0;
                  ELSIF ((RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and Tx_nRx = '1') THEN 
                     DataOut_cld <= RTAddr & Tx_nRx & RtSubAddr & RtLen_Mode;
                     Cmd_nData_cld <= '1';
                     SendWord_cld <= '1';
                     if (RtLen_Mode = "00000") then
                       Len <= 32;
                     else
                       Len <= to_integer(unsigned(RtLen_Mode));
                     end if;
                  END IF;
               WHEN bc3RTRT => 
                  IF (Done  = '1') THEN 
                     BusActive_cld <= '1';
                     WordCount <= WordCount +1;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     --CmdCount <= 0;
                     TxAvail_cld <= '0';
                  END IF;
               WHEN sIdle => 
                  BusActive_cld <= '0';
                  IF (NewWord = '1' and Cmd_nDataIn = '1'  and IsRT = '1') THEN 
                     -- RX Command word decoding
                     CmdRxed_cld <= Outword;
                     RtAddr <= Outword(15 downto 11);
                     Tx_nRx <= Outword(10);
                     RtSubAddr <= Outword(9 downto 5);
                     RtLen_Mode <= Outword(4 downto 0);
                     CmdWord <= Outword;
                     StatusRxedFlag_cld <= '0';
                     if (RT2RT_busy = '1') then
                       tmr_NRP_Start_cld <= '1';
                       tmr_NRP_Stop_cld <= '1';
                     end if;
                  ELSIF (SendMessage = '1') THEN 
                     BusActive_cld <= '1';
                     WordCount <= to_integer(unsigned(CmdProcStart));
                     RamWaitStates <= 0;
                     CmdCount <= 0;
                     TxAvail_cld <= '0';
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     RT2RT_Busy <= '0';
                  ELSIF ((tmr_NRP = '1' or CmdEdge = '1')) THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     if (RT2RT_busy = '1' and tmr_NRP = '1') then
                       RT2RT_Busy <= '0';
                     end if;
                  ELSE
                     tmr_REP_Stop_cld <= '1';
                  END IF;
               WHEN bcGetCmd => 
                  IF (RamWaitStates  = 3) THEN 
                     -- Command word decoding
                     RtAddr <= TxDataIn(15 downto 11);
                     Tx_nRx <= TxDataIn(10);
                     RtSubAddr <= TxDataIn(9 downto 5);
                     RtLen_Mode <= TxDataIn(4 downto 0);
                     RT2RT <= TxDataIn(16);
                     if ((TxDataIn(16) = '1') and (RT2RT_Busy = '0')) then
                       RT2RT_RxRtAddr <= TxDataIn(15 downto 11);
                       RT2RT_Busy <= '1';
                     end if;
                     StatusRxedFlag_cld <= '0';
                  ELSE
                     RamWaitStates <= RamWaitStates + 1;
                  END IF;
               WHEN bcTxGap => 
                  IF (tmr_GAP = '1' and to_integer(unsigned(CmdProcLen)) = CmdCount) THEN 
                     BusActive_cld <= '0';
                     WordCount <= 0;
                     CmdCount <= 0;
                     RtSubAddr <= "00000";
                     tmr_GAP_Stop_cld <= '1';
                     tmr_GAP_Start_cld <= '0';
                     TxAvail_cld <= '1';
                  ELSIF (tmr_GAP = '1') THEN 
                     BusActive_cld <= '1';
                     RamWaitStates <= 0;
                     TxAvail_cld <= '0';
                     tmr_GAP_Stop_cld <= '1';
                     tmr_GAP_Start_cld <= '0';
                     RT2RT_Busy <= '0';
                  END IF;
               WHEN bcCheckRtAddr => 
                  if (RtAddr = "11111" and BroadcastEnable = '1') then
                    Broadcast <= '1';
                  else
                    if (RT2RT_Busy = '0') then
                    BroadCast <= '0';
                  end if;
                  end if;
                  CmdCount <= CmdCount + 1;
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '0';
                  tmr_GAP_Stop_cld <= '1';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc2SendCw => 
                  IF (Done = '1') THEN 
                     SendWord_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                     WordCount <= 0;
                     -- start the tREP to blank te decoder
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '0';
                     BlankDecoder_cld <= '1';
                  END IF;
               WHEN bc2NRP => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  RT2RT_Busy <= '0';
                  tmr_NRP_Start_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc2StatusRx => 
                  IF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                     WordCount <= 0;
                     RxDataOut_cld <= OutWord;
                     RxDataWr_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                  END IF;
               WHEN bc2DataRx => 
                  IF ((WordCount+1) = Len) THEN 
                     DataRxedFlag_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     if (RT2RT_Busy = '1') then
                       tmr_NRP_Start_cld <= '1';
                       tmr_NRP_Stop_cld <= '0';
                     end if;
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                     WordCount <= WordCount + 1;
                     RxDataOut_cld <= OutWord;
                     RxDataWr_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  END IF;
               WHEN bc2CmdDone => 
                  IF (tmr_REP = '1') THEN 
                     -- stop the tREP
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     BlankDecoder_cld <= '0';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                     StatusRxed_cld <= OutWord;
                     WordCount <= 0;
                     StatusRxedFlag_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     BlankDecoder_cld <= '0';
                  ELSIF (tmr_NRP = '1' or tmr_25us = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     BlankDecoder_cld <= '0';
                  ELSIF (CmdEdge = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '0';
                  END IF;
               WHEN bc1SendCw => 
                  IF (Done = '1' and Err_inj(3 downto 0) = "0011") THEN 
                     SendWord_cld <= '1';
                     Cmd_nData_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     WordCount <= 0;
                     Len <= to_integer(unsigned(Err_inj(15 downto 10)));
                  ELSIF (Done = '1') THEN 
                     if (Err_inj(3 downto 0 ) /= "0011") then 
                     WordCount <= WordCount + 1;
                     end if;
                     DataOut_cld <= TxDataIn(15 downto 0);
                     Cmd_nData_cld <= '0';
                     SendWord_cld <= '1';
                  END IF;
               WHEN bc1SendData => 
                  IF (WordCount = Len and Done = '1' and Broadcast = '1') THEN 
                     WordCount <= 0;
                     SendWord_cld <= '0';
                     tmr_25us_Stop_cld<= '1';
                     tmr_25us_Start_cld <= '1';
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (WordCount = Len and Done = '1') THEN 
                     SendWord_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                     -- start the tREP to blank te decoder
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '0';
                     BlankDecoder_cld <= '1';
                  ELSIF (Done = '1') THEN 
                     WordCount <= WordCount + 1;
                     DataOut_cld <= TxDataIn(15 downto 0);
                     Cmd_nData_cld <= '0';
                     SendWord_cld <= '1';
                  END IF;
               WHEN bc1WaitForStatus => 
                  IF (tmr_REP = '1') THEN 
                     -- stop the tREP
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     BlankDecoder_cld <= '0';
                  ELSIF (tmr_NRP = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '0';
                     tmr_25us_Stop_cld<= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     BlankDecoder_cld <= '0';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     BlankDecoder_cld <= '0';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                     WordCount <= 0;
                     StatusRxed_cld <= OutWord;
                     tmr_NRP_Stop_cld<= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_25us_Stop_cld<= '1';
                     tmr_25us_Start_cld <= '1';
                     StatusRxedFlag_cld <= '1';
                     tmr_REP_Start_cld <= '1';
                     tmr_REP_Stop_cld <= '1';
                     BlankDecoder_cld <= '0';
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (CmdEdge = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '0';
                     tmr_25us_Start_cld <= '1';
                  END IF;
               WHEN bc1NRP => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc1WordTimeout => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc5SendCw1 => 
                  IF (Done = '1' and Err_inj(3 downto 0) /= "0101") THEN 
                     SendWord_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     WordCount <= 0;
                  ELSIF (Done = '1' and Err_inj(3 downto 0) = "0101") THEN 
                     SendWord_cld <= '1';
                     Cmd_nData_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     WordCount <= 0;
                  END IF;
               WHEN bc5NRP => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc5StatusRx => 
                  IF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                     WordCount <= 0;
                     ModeData_cld <= OutWord;
                     NewModeCmd_cld  <= '1';
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     RxDataOut_cld <= OutWord;
                     RxDataWr_cld <= '1';
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                  END IF;
               WHEN bc5CmdDone => 
                  IF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                     StatusRxed_cld <= OutWord;
                     WordCount <= 0;
                     StatusRxedFlag_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (tmr_NRP = '1' or tmr_25us = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                  ELSIF (CmdEdge = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '0';
                  END IF;
               WHEN bc6SendCw => 
                  IF (Done = '1' and Err_inj(3 downto 0) /= "0100") THEN 
                     WordCount <= WordCount + 1;
                     DataOut_cld <= TxDataIn(15 downto 0);
                     Cmd_nData_cld <= '0';
                     SendWord_cld <= '1';
                  ELSIF (Done = '1' and Err_inj(3 downto 0) = "0100") THEN 
                     SendWord_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                  END IF;
               WHEN bc6SendData => 
                  IF ((Err_inj(3 downto 0 ) = "0011" and WordCount = Len and Done = '1' and Broadcast = '1') or 
                      (Err_inj(3 downto 0 ) /= "0011" and Done = '1' and Broadcast = '1')) THEN 
                     WordCount <= 0;
                     SendWord_cld <= '0';
                     tmr_25us_Stop_cld<= '1';
                     tmr_25us_Start_cld <= '0';
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF ((Err_inj(3 downto 0 ) = "0011" and WordCount = Len and Done = '1') or 
                         (Err_inj(3 downto 0 ) /= "0011" and Done = '1')) THEN 
                     SendWord_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                  ELSIF ((Err_inj(3 downto 0 ) = "0011" and Done = '1')) THEN 
                     WordCount <= WordCount + 1;
                     DataOut_cld <= TxDataIn(15 downto 0);
                     Cmd_nData_cld <= '0';
                     SendWord_cld <= '1';
                  END IF;
               WHEN bc6WaitForStatus => 
                  IF (tmr_NRP = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                     WordCount <= 0;
                     StatusRxed_cld <= OutWord;
                     tmr_NRP_Stop_cld<= '1';
                     tmr_NRP_Start_cld <= '0';
                     tmr_25us_Stop_cld<= '1';
                     tmr_25us_Start_cld <= '0';
                     StatusRxedFlag_cld <= '1';
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (CmdEdge = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '0';
                     tmr_25us_Start_cld <= '1';
                  END IF;
               WHEN bc6NRP => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc6WordTimeout => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc4SendCw => 
                  IF (Done = '1' and Broadcast = '1') THEN 
                     WordCount <= 0;
                     SendWord_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (Done = '1' and Err_inj(3 downto 0) /= "0101") THEN 
                     SendWord_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                  ELSIF (Done = '1' and Err_inj(3 downto 0) = "0101") THEN 
                     SendWord_cld <= '1';
                     Cmd_nData_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     WordCount <= 0;
                  END IF;
               WHEN bc4WaitForStatus => 
                  IF (tmr_NRP = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                     WordCount <= 0;
                     StatusRxed_cld <= OutWord;
                     tmr_NRP_Stop_cld<= '1';
                     tmr_NRP_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                     DBC_Accepted_cld <= not OutWord(1);
                     StatusRxedFlag_cld <= '1';
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (CmdEdge = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '0';
                  END IF;
               WHEN bc4NRP => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc4WordTimeout => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc3SendCw => 
                  IF (Done = '1') THEN 
                     SendWord_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                     WordCount <= 0;
                  END IF;
               WHEN bc3CmdDone => 
                  IF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                     StatusRxed_cld <= OutWord;
                     WordCount <= 0;
                     StatusRxedFlag_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (tmr_NRP = '1' or tmr_25us = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                  ELSIF (CmdEdge = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_25us_Stop_cld <= '0';
                  END IF;
               WHEN bc3NRP => 
                  WordCount <= CmdCount;
                  RtSubAddr <= "00000";
                  RamWaitStates <= 0;
                  TxAvail_cld <= '1';
                  tmr_NRP_Stop_cld <= '1';
                  tmr_NRP_Start_cld <= '1';
                  tmr_GAP_Stop_cld <= '0';
                  tmr_GAP_Start_cld <= '1';
               WHEN bc3StatusRx => 
                  IF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                     WordCount <= 0;
                     RxDataOut_cld <= OutWord;
                     RxDataWr_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '1';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                  END IF;
               WHEN bc3DataRx => 
                  IF ((WordCount+1) = Len) THEN 
                     DataRxedFlag_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                     WordCount <= WordCount + 1;
                     RxDataOut_cld <= OutWord;
                     RxDataWr_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                  ELSIF (tmr_25us = '1') THEN 
                     tmr_25us_Start_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                  END IF;
               WHEN bc3StatusRx2 => 
                  IF ((Broadcast = '1')) THEN 
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '1';
                     RT2RT_Busy <= '0';
                  ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                     StatusRxed_cld <= OutWord;
                     WordCount <= 0;
                     StatusRxedFlag_cld <= '1';
                     tmr_25us_Start_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '1';
                     RT2RT_Busy <= '0';
                     WordCount <= CmdCount;
                     RtSubAddr <= "00000";
                     RamWaitStates <= 0;
                     tmr_GAP_Stop_cld <= '0';
                     tmr_GAP_Start_cld <= '1';
                  ELSIF (tmr_NRP = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_25us_Stop_cld <= '1';
                  ELSIF (CmdEdge = '1') THEN 
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                  END IF;
               WHEN bc4SendWord => 
                  IF (Done = '1') THEN 
                     SendWord_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                  END IF;
               WHEN bc5SendWord => 
                  IF (Done = '1') THEN 
                     SendWord_cld <= '0';
                     tmr_NRP_Start_cld <= '1';
                     tmr_NRP_Stop_cld <= '0';
                     tmr_25us_Stop_cld <= '1';
                     tmr_25us_Start_cld <= '0';
                  END IF;
               WHEN bcPreMsgTxGap => 
                  IF (tmr_GAP = '1') THEN 
                     BusActive_cld <= '1';
                     WordCount <= to_integer(unsigned(CmdProcStart));
                     RamWaitStates <= 0;
                     CmdCount <= 0;
                     TxAvail_cld <= '0';
                     tmr_NRP_Stop_cld <= '1';
                     tmr_NRP_Start_cld <= '1';
                     RT2RT_Busy <= '0';
                  END IF;
               WHEN bc1SendWord1 => 
                  IF (NOT(Len = 0)) THEN 
                     if (Err_inj(3 downto 0 ) /= "0011") then 
                     WordCount <= WordCount + 1;
                     end if;
                     DataOut_cld <= TxDataIn(15 downto 0);
                     Cmd_nData_cld <= '0';
                     SendWord_cld <= '1';
                  END IF;
               WHEN s0 => 
                  IF (NewWord = '1' and Cmd_nDataIn = '0'  and IsRT = '1') THEN 
                     -- force the message error bit high in previous status 
                     -- due to unexpected data word, probably due to to many data word sent by BC
                     PrevStatus <= PrevStatus(15 downto 11) & '1' & PrevStatus(9 downto 0);
                  END IF;
               WHEN OTHERS =>
                  NULL;
            END CASE;
         END IF;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      Broadcast,
      BroadcastEnable,
      BusActive_cld,
      CmdCount,
      CmdEdge,
      CmdProcLen,
      Cmd_nDataIn,
      Done,
      Err_inj,
      IsRT,
      Len,
      NewWord,
      RT2RT,
      RT2RT_Busy,
      RamWaitStates,
      RtAddr,
      RtLen_Mode,
      RtSubAddr,
      SendMessage,
      Tx_nRx,
      WordCount,
      current_state,
      sWaitforStatusActive,
      tmr_25us,
      tmr_GAP,
      tmr_NRP,
      tmr_REP,
      tmr_SAF
   )
   -----------------------------------------------------------------
   BEGIN

      -- Interrupts
      IF (tmr_SAF = '1') THEN
         next_state <= sIdle;
      ELSIF (SendMessage = '1' and BusActive_cld = '1') THEN
         next_state <= bcPreMsgTxGap;
      ELSIF (newWord = '1' and Cmd_nDataIn = '1'   and IsRT = '1' and sWaitforStatusActive = '0') THEN
         next_state <= rtRxedCmd1;
      ELSE
         CASE current_state IS
            WHEN bcStartCmd => 
               IF ((RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and RT2RT = '1') THEN 
                  next_state <= bc3RTRT;
               ELSIF ((RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and Tx_nRx = '1' and RT2RT_Busy = '1') THEN 
                  next_state <= bc3SendCw;
               ELSIF ((RtSubAddr = "00000"  or  RtSubAddr = "11111") and RtLen_Mode(4) = '0') THEN 
                  next_state <= bc4SendCw;
               ELSIF ((RtSubAddr = "00000"  or  RtSubAddr = "11111") and Tx_nRx = '1' and RtLen_Mode(4) = '1') THEN 
                  next_state <= bc5SendCw1;
               ELSIF ((RtSubAddr = "00000"  or  RtSubAddr = "11111") and Tx_nRx = '0'  and RtLen_Mode(4) = '1') THEN 
                  next_state <= bc6SendCw;
               ELSIF ((RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and Tx_nRx = '0') THEN 
                  next_state <= bc1SendCw;
               ELSIF ((RtSubAddr /= "00000"  and  RtSubAddr /= "11111") and Tx_nRx = '1') THEN 
                  next_state <= bc2SendCw;
               ELSE
                  next_state <= bcStartCmd;
               END IF;
            WHEN bc3RTRT => 
               IF (Done  = '1') THEN 
                  next_state <= bcGetCmd;
               ELSE
                  next_state <= bc3RTRT;
               END IF;
            WHEN sIdle => 
               IF (NewWord = '1' and Cmd_nDataIn = '1'  and IsRT = '1') THEN 
                  next_state <= rtRxedCmd1;
               ELSIF (SendMessage = '1') THEN 
                  next_state <= bcGetCmd;
               ELSIF ((tmr_NRP = '1' or CmdEdge = '1')) THEN 
                  next_state <= sClrNRP;
               ELSE
                  next_state <= sIdle;
               END IF;
            WHEN bcGetCmd => 
               IF (RamWaitStates  = 3) THEN 
                  next_state <= bcCheckRtAddr;
               ELSE
                  next_state <= bcGetCmd;
               END IF;
            WHEN bcTxGap => 
               IF (tmr_GAP = '1' and to_integer(unsigned(CmdProcLen)) = CmdCount) THEN 
                  next_state <= sIdle;
               ELSIF (tmr_GAP = '1') THEN 
                  next_state <= bcGetCmd;
               ELSE
                  next_state <= bcTxGap;
               END IF;
            WHEN rtRxedCmd1 => 
               next_state <= rtRxedCmd1;
            WHEN bcCheckRtAddr => 
               next_state <= bcStartCmd;
            WHEN sClrNRP => 
               next_state <= sIdle;
            WHEN bc2SendCw => 
               IF (Done = '1') THEN 
                  next_state <= bc2CmdDone;
               ELSE
                  next_state <= bc2SendCw;
               END IF;
            WHEN bc2NRP => 
               next_state <= bcTxGap;
            WHEN bc2StatusRx => 
               IF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                  next_state <= bc2DataRx;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= bc2NRP;
               ELSE
                  next_state <= bc2StatusRx;
               END IF;
            WHEN bc2DataRx => 
               IF ((WordCount+1) = Len) THEN 
                  next_state <= bcTxGap;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= bc2NRP;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                  next_state <= bc2DataRx;
               ELSE
                  next_state <= bc2DataRx;
               END IF;
            WHEN bc2CmdDone => 
               IF (tmr_REP = '1') THEN 
                  next_state <= bc2CmdDone;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                  next_state <= bc2StatusRx;
               ELSIF (tmr_NRP = '1' or tmr_25us = '1') THEN 
                  next_state <= bc2NRP;
               ELSIF (CmdEdge = '1') THEN 
                  next_state <= bc2CmdDone;
               ELSE
                  next_state <= bc2CmdDone;
               END IF;
            WHEN bc1SendCw => 
               IF (Done = '1' and Err_inj(3 downto 0) = "0011") THEN 
                  next_state <= bc1SendWord1;
               ELSIF (Done = '1') THEN 
                  next_state <= bc1SendData;
               ELSE
                  next_state <= bc1SendCw;
               END IF;
            WHEN bc1SendData => 
               IF (WordCount = Len and Done = '1' and Broadcast = '1') THEN 
                  next_state <= bcTxGap;
               ELSIF (WordCount = Len and Done = '1') THEN 
                  next_state <= bc1WaitForStatus;
               ELSIF (Done = '1') THEN 
                  next_state <= bc1SendData;
               ELSE
                  next_state <= bc1SendData;
               END IF;
            WHEN bc1WaitForStatus => 
               IF (tmr_REP = '1') THEN 
                  next_state <= bc1WaitForStatus;
               ELSIF (tmr_NRP = '1') THEN 
                  next_state <= bc1NRP;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= bc1WordTimeout;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                  next_state <= bcTxGap;
               ELSIF (CmdEdge = '1') THEN 
                  next_state <= bc1WaitForStatus;
               ELSE
                  next_state <= bc1WaitForStatus;
               END IF;
            WHEN bc1NRP => 
               next_state <= bcTxGap;
            WHEN bc1WordTimeout => 
               next_state <= bcTxGap;
            WHEN bc5SendCw1 => 
               IF (Done = '1' and Err_inj(3 downto 0) /= "0101") THEN 
                  next_state <= bc5CmdDone;
               ELSIF (Done = '1' and Err_inj(3 downto 0) = "0101") THEN 
                  next_state <= bc5SendWord;
               ELSE
                  next_state <= bc5SendCw1;
               END IF;
            WHEN bc5NRP => 
               next_state <= bcTxGap;
            WHEN bc5StatusRx => 
               IF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                  next_state <= bcTxGap;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= bc5NRP;
               ELSE
                  next_state <= bc5StatusRx;
               END IF;
            WHEN bc5CmdDone => 
               IF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                  next_state <= bc5StatusRx;
               ELSIF (tmr_NRP = '1' or tmr_25us = '1') THEN 
                  next_state <= bc5NRP;
               ELSIF (CmdEdge = '1') THEN 
                  next_state <= bc5CmdDone;
               ELSE
                  next_state <= bc5CmdDone;
               END IF;
            WHEN bc6SendCw => 
               IF (Done = '1' and Err_inj(3 downto 0) /= "0100") THEN 
                  next_state <= bc6SendData;
               ELSIF (Done = '1' and Err_inj(3 downto 0) = "0100") THEN 
                  next_state <= bc6WaitForStatus;
               ELSE
                  next_state <= bc6SendCw;
               END IF;
            WHEN bc6SendData => 
               IF ((Err_inj(3 downto 0 ) = "0011" and WordCount = Len and Done = '1' and Broadcast = '1') or 
                   (Err_inj(3 downto 0 ) /= "0011" and Done = '1' and Broadcast = '1')) THEN 
                  next_state <= bcTxGap;
               ELSIF ((Err_inj(3 downto 0 ) = "0011" and WordCount = Len and Done = '1') or 
                      (Err_inj(3 downto 0 ) /= "0011" and Done = '1')) THEN 
                  next_state <= bc6WaitForStatus;
               ELSIF ((Err_inj(3 downto 0 ) = "0011" and Done = '1')) THEN 
                  next_state <= bc6SendData;
               ELSE
                  next_state <= bc6SendData;
               END IF;
            WHEN bc6WaitForStatus => 
               IF (tmr_NRP = '1') THEN 
                  next_state <= bc6NRP;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= bc6WordTimeout;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                  next_state <= bcTxGap;
               ELSIF (CmdEdge = '1') THEN 
                  next_state <= bc6WaitForStatus;
               ELSE
                  next_state <= bc6WaitForStatus;
               END IF;
            WHEN bc6NRP => 
               next_state <= bcTxGap;
            WHEN bc6WordTimeout => 
               next_state <= bcTxGap;
            WHEN bc4SendCw => 
               IF (Done = '1' and Broadcast = '1') THEN 
                  next_state <= bcTxGap;
               ELSIF (Done = '1' and Err_inj(3 downto 0) /= "0101") THEN 
                  next_state <= bc4WaitForStatus;
               ELSIF (Done = '1' and Err_inj(3 downto 0) = "0101") THEN 
                  next_state <= bc4SendWord;
               ELSE
                  next_state <= bc4SendCw;
               END IF;
            WHEN bc4WaitForStatus => 
               IF (tmr_NRP = '1') THEN 
                  next_state <= bc4NRP;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= bc4WordTimeout;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                  next_state <= bcTxGap;
               ELSIF (CmdEdge = '1') THEN 
                  next_state <= bc4WaitForStatus;
               ELSE
                  next_state <= bc4WaitForStatus;
               END IF;
            WHEN bc4NRP => 
               next_state <= bcTxGap;
            WHEN bc4WordTimeout => 
               next_state <= bcTxGap;
            WHEN bc3SendCw => 
               IF (Done = '1') THEN 
                  next_state <= bc3CmdDone;
               ELSE
                  next_state <= bc3SendCw;
               END IF;
            WHEN bc3CmdDone => 
               IF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                  next_state <= bc3StatusRx;
               ELSIF (tmr_NRP = '1' or tmr_25us = '1') THEN 
                  next_state <= bc3NRP;
               ELSIF (CmdEdge = '1') THEN 
                  next_state <= bc3CmdDone;
               ELSE
                  next_state <= bc3CmdDone;
               END IF;
            WHEN bc3NRP => 
               next_state <= bcTxGap;
            WHEN bc3StatusRx => 
               IF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                  next_state <= bc3DataRx;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= bc3NRP;
               ELSE
                  next_state <= bc3StatusRx;
               END IF;
            WHEN bc3DataRx => 
               IF ((WordCount+1) = Len) THEN 
                  next_state <= bc3StatusRx2;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '0') THEN 
                  next_state <= bc3DataRx;
               ELSIF (tmr_25us = '1') THEN 
                  next_state <= bc3NRP;
               ELSE
                  next_state <= bc3DataRx;
               END IF;
            WHEN bc3StatusRx2 => 
               IF ((Broadcast = '1')) THEN 
                  next_state <= bcTxGap;
               ELSIF (NewWord = '1' and Cmd_nDataIn = '1') THEN 
                  next_state <= bcTxGap;
               ELSIF (tmr_NRP = '1') THEN 
                  next_state <= bc3NRP;
               ELSIF (CmdEdge = '1') THEN 
                  next_state <= bc3StatusRx2;
               ELSE
                  next_state <= bc3StatusRx2;
               END IF;
            WHEN bc4SendWord => 
               IF (Done = '1') THEN 
                  next_state <= bc4WaitForStatus;
               ELSE
                  next_state <= bc4SendWord;
               END IF;
            WHEN bc5SendWord => 
               IF (Done = '1') THEN 
                  next_state <= bc5CmdDone;
               ELSE
                  next_state <= bc5SendWord;
               END IF;
            WHEN bcPreMsgTxGap => 
               IF (tmr_GAP = '1') THEN 
                  next_state <= bcGetCmd;
               ELSE
                  next_state <= bcPreMsgTxGap;
               END IF;
            WHEN bc1SendWord1 => 
               IF (Len = 0) THEN 
                  next_state <= bc1WaitForStatus;
               ELSE
                  next_state <= bc1SendData;
               END IF;
            WHEN s0 => 
               IF (NewWord = '1' and Cmd_nDataIn = '0'  and IsRT = '1') THEN 
                  next_state <= sIdle;
               ELSE
                  next_state <= s0;
               END IF;
            WHEN s1 => 
               IF (BroadCastEnable = '0' or 
                   ((RtAddr = "11111" and Tx_nRx = '1' and RtSubAddr /= "00000") and 
                   (RtAddr = "11111" and Tx_nRx = '1' and RtSubAddr /= "11111"))) THEN 
                  next_state <= sIdle;
               ELSE
                  next_state <= s1;
               END IF;
            WHEN OTHERS =>
               next_state <= sIdle;
         END CASE;
      END IF;
   END PROCESS nextstate_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   BlankDecoder <= BlankDecoder_cld;
   BusActive <= BusActive_cld;
   BusReset_Rxed <= BusReset_Rxed_cld;
   CmdRxed <= CmdRxed_cld;
   Cmd_nData <= Cmd_nData_cld;
   DBC_Accepted <= DBC_Accepted_cld;
   DataOut <= DataOut_cld;
   DataReqFlag <= DataReqFlag_cld;
   DataRxedFlag <= DataRxedFlag_cld;
   DataWrapActive <= DataWrapActive_cld;
   InitiateBIT_Rxed <= InitiateBIT_Rxed_cld;
   ModeCmd <= ModeCmd_cld;
   ModeData <= ModeData_cld;
   NewModeCmd <= NewModeCmd_cld;
   RxDataOut <= RxDataOut_cld;
   RxDataWr <= RxDataWr_cld;
   SelTxShutdown <= SelTxShutdown_cld;
   SendWord <= SendWord_cld;
   ShutdownData <= ShutdownData_cld;
   StatusRxed <= StatusRxed_cld;
   StatusRxedFlag <= StatusRxedFlag_cld;
   Sync_Rxed <= Sync_Rxed_cld;
   TxAvail <= TxAvail_cld;
   TxDataRd <= TxDataRd_cld;
   TxShutdown <= TxShutdown_cld;
   inj_ParityError <= inj_ParityError_cld;
   tmr_25us_Start <= tmr_25us_Start_cld;
   tmr_25us_Stop <= tmr_25us_Stop_cld;
   tmr_GAP_Start <= tmr_GAP_Start_cld;
   tmr_GAP_Stop <= tmr_GAP_Stop_cld;
   tmr_NRP_Start <= tmr_NRP_Start_cld;
   tmr_NRP_Stop <= tmr_NRP_Stop_cld;
   tmr_REP_Start <= tmr_REP_Start_cld;
   tmr_REP_Stop <= tmr_REP_Stop_cld;
   TxDataAddr <= RtSubAddr & RtLen_Mode when (RtSubAddr = "11111") else
                           --"11111" & RtLen_Mode when (RtSubAddr = "00000") else
                             RtSubAddr & std_logic_vector(to_unsigned(WordCount,5));
   RxDataAddr <= RtSubAddr & RtLen_Mode when  (RtSubAddr = "11111" ) else
                           "11111" & RtLen_Mode when (RtSubAddr = "00000") else
                             RtSubAddr & std_logic_vector(to_unsigned(WordCount,5));
   TerminalFlag <= TerminalFlagIn and not(InhibitTFlag_Rxed );
   Status <= MyRtAddr & (MessageError or DecoderErr) & Instrumentation & ServiceRequest & "000" & 
   Broadcast & Busy & SubsystemFlag & DBC_Accepted_cld & TerminalFlag;
END fsm;
