-- VHDL Entity mil1553_lib.mill1553_dualbus.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 13:38:40 02/ 2/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY mil1553_lib;
USE mil1553_lib.mil1553.ALL;

ENTITY mill1553_dualbus IS
   GENERIC( 
      CoreMode : core_mode_t := BCRT_MODE
   );
   PORT( 
      Addr             : IN     std_logic_vector (15 DOWNTO 0);
      BitWord          : IN     std_logic_vector (15 DOWNTO 0);
      Cs               : IN     std_logic;
      DataIn           : IN     std_logic_vector (15 DOWNTO 0);
      InN1             : IN     std_logic;
      InN2             : IN     std_logic;
      InP1             : IN     std_logic;
      InP2             : IN     std_logic;
      MyRtAddr         : IN     std_logic_vector (4 DOWNTO 0);
      MyRtAddrParity   : IN     std_logic;
      Rd               : IN     std_logic;
      ServiceReqVector : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest   : IN     std_logic;
      SubsystemFlag    : IN     std_logic;
      Wr               : IN     std_logic;
      clk              : IN     std_logic;
      nResetIn         : IN     std_logic;
      DataOut          : OUT    std_logic_vector (15 DOWNTO 0);
      DataValid        : OUT    std_logic;
      Intr             : OUT    std_logic;
      OutEn1           : OUT    std_logic;
      OutEn2           : OUT    std_logic;
      OutN1            : OUT    std_logic;
      OutN2            : OUT    std_logic;
      OutP1            : OUT    std_logic;
      OutP2            : OUT    std_logic;
      Strobe1          : OUT    std_logic;
      Strobe2          : OUT    std_logic
   );

-- Declarations

END mill1553_dualbus ;

-- VHDL Architecture mil1553_lib.mill1553_dualbus.struct
-- *********************************************************************************************************************
-- Company:         Al Tariq, Abu Dhabi
-- Created by:       jeansmith.UNKNOWN (DESKTOP2)
-- Date:                08:54:44 02/20/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
-- *********************************************************************************************************************
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY mil1553_lib;

ARCHITECTURE struct OF mill1553_dualbus IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL BIT1               : std_logic_vector(15 DOWNTO 0);
   SIGNAL BroadcastEnable    : std_logic;
   SIGNAL BusActive1         : std_logic;
   SIGNAL BusActive2         : std_logic;
   SIGNAL BusBusy            : std_logic;
   SIGNAL BusReset_Rxed1     : std_logic;
   SIGNAL BusReset_Rxed2     : std_logic;
   SIGNAL BusSwapResetBus1   : std_logic;
   SIGNAL BusSwapResetBus2   : std_logic;
   SIGNAL Clear_InitiateBIT1 : std_logic;
   SIGNAL Clear_InitiateBIT2 : std_logic;
   SIGNAL Clear_Synchronize1 : std_logic;
   SIGNAL Clear_Synchronize2 : std_logic;
   SIGNAL CmdProcLen1        : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdProcLen2        : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdProcStart1      : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdProcStart2      : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdRxed1           : std_logic_vector(15 DOWNTO 0);
   SIGNAL CmdRxed2           : std_logic_vector(15 DOWNTO 0);
   SIGNAL DBC_Accepted1      : std_logic;
   SIGNAL DBC_Accepted2      : std_logic;
   SIGNAL DBC_Enable         : std_logic;
   SIGNAL DataReqFlag1       : std_logic;
   SIGNAL DataReqFlag2       : std_logic;
   SIGNAL DataRxedFlag1      : std_logic;
   SIGNAL DataRxedFlag2      : std_logic;
   SIGNAL DataWrapActive1    : std_logic;
   SIGNAL DataWrapActive2    : std_logic;
   SIGNAL EarlyReplyRx1      : std_logic;
   SIGNAL EarlyReplyRx2      : std_logic;
   SIGNAL EnableHwDataWrap   : std_logic;
   SIGNAL InitiateBIT_Rxed1  : std_logic;
   SIGNAL InitiateBIT_Rxed2  : std_logic;
   SIGNAL IsRT               : std_logic;
   SIGNAL LegalModeBrdcst    : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalModeRx        : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalModeTx        : std_logic_vector(31 DOWNTO 0);
   SIGNAL LegalSubAddr       : std_logic_vector(31 DOWNTO 0);
   SIGNAL ModeCmd1           : std_logic_vector(15 DOWNTO 0);
   SIGNAL ModeCmd2           : std_logic_vector(15 DOWNTO 0);
   SIGNAL ModeData1          : std_logic_vector(15 DOWNTO 0);
   SIGNAL ModeData2          : std_logic_vector(15 DOWNTO 0);
   SIGNAL MyRtAddrInt        : std_logic_vector(4 DOWNTO 0);
   SIGNAL MyRtAddrParityInt  : std_logic;
   SIGNAL NewModeCmd1        : std_logic;
   SIGNAL NewModeCmd2        : std_logic;
   SIGNAL RtActiveBus        : std_logic;
   SIGNAL RtAddrParityOK     : std_logic;
   SIGNAL RtControl          : std_logic_vector(15 DOWNTO 0);
   SIGNAL RxDataAddr1        : std_logic_vector(9 DOWNTO 0);
   SIGNAL RxDataAddr2        : std_logic_vector(9 DOWNTO 0);
   SIGNAL RxDataOut1         : std_logic_vector(15 DOWNTO 0);
   SIGNAL RxDataOut2         : std_logic_vector(15 DOWNTO 0);
   SIGNAL RxDataWr1          : std_logic;
   SIGNAL RxDataWr2          : std_logic;
   SIGNAL SelTxShutdown1     : std_logic;
   SIGNAL SelTxShutdown2     : std_logic;
   SIGNAL SendMessage1       : std_logic;
   SIGNAL SendMessage2       : std_logic;
   SIGNAL ServiceReqVector1  : std_logic_vector(15 DOWNTO 0);
   SIGNAL ShutdownData1      : std_logic_vector(4 DOWNTO 0);
   SIGNAL ShutdownData2      : std_logic_vector(4 DOWNTO 0);
   SIGNAL StatusRxed1        : std_logic_vector(15 DOWNTO 0);
   SIGNAL StatusRxed1A       : std_logic_vector(15 DOWNTO 0);
   SIGNAL StatusRxed2        : std_logic_vector(15 DOWNTO 0);
   SIGNAL StatusRxed2A       : std_logic_vector(15 DOWNTO 0);
   SIGNAL StatusRxedFlag1    : std_logic;
   SIGNAL StatusRxedFlag2    : std_logic;
   SIGNAL Synchronize1       : std_logic;
   SIGNAL Synchronize2       : std_logic;
   SIGNAL TerminalFlagIn1    : std_logic;
   SIGNAL TerminalFlagIn2    : std_logic;
   SIGNAL TerminalFlag_Rxed1 : std_logic;
   SIGNAL TerminalFlag_Rxed2 : std_logic;
   SIGNAL TxAvail1           : std_logic;
   SIGNAL TxAvail2           : std_logic;
   SIGNAL TxDataAddr1        : std_logic_vector(9 DOWNTO 0);
   SIGNAL TxDataAddr2        : std_logic_vector(9 DOWNTO 0);
   SIGNAL TxDataIn1          : std_logic_vector(16 DOWNTO 0);
   SIGNAL TxDataIn2          : std_logic_vector(16 DOWNTO 0);
   SIGNAL TxOffIn1           : std_logic;
   SIGNAL TxOffIn2           : std_logic;
   SIGNAL TxOffOut1          : std_logic;
   SIGNAL TxOffOut2          : std_logic;
   SIGNAL UnexpectedEdgeCnt1 : std_logic_vector(15 DOWNTO 0);
   SIGNAL UnexpectedEdgeCnt2 : std_logic_vector(15 DOWNTO 0);
   SIGNAL datawrap_subaddr   : std_logic_vector(4 DOWNTO 0);
   SIGNAL nReset             : std_logic;
   SIGNAL nResetBus1         : std_logic;
   SIGNAL nResetBus2         : std_logic;
   SIGNAL nResetCore1        : std_logic;
   SIGNAL nResetCore2        : std_logic;
   SIGNAL reg_err_inj        : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_tmr_1us        : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_tmr_GAP        : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_tmr_NRP        : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_tmr_REP        : std_logic_vector(15 DOWNTO 0);
   SIGNAL reg_tmr_SAF        : std_logic_vector(15 DOWNTO 0);
   SIGNAL tmr_GAP1           : std_logic;
   SIGNAL tmr_GAP2           : std_logic;
   SIGNAL tmr_NRP1           : std_logic;
   SIGNAL tmr_NRP2           : std_logic;
   SIGNAL tmr_REP1           : std_logic;
   SIGNAL tmr_REP2           : std_logic;
   SIGNAL tmr_SAF1           : std_logic;
   SIGNAL tmr_SAF2           : std_logic;



   -- Component Declarations
   COMPONENT mil1553_cpu_interface
   GENERIC (
      CoreMode : core_mode_t := BCRT_Mode
   );
   PORT (
      Addr               : IN     std_logic_vector (15 DOWNTO 0);
      BitWord            : IN     std_logic_vector (15 DOWNTO 0);
      CmdRxed1           : IN     std_logic_vector (15 DOWNTO 0);
      CmdRxed2           : IN     std_logic_vector (15 DOWNTO 0);
      Cs                 : IN     std_logic ;
      DBC_Accepted1      : IN     std_logic ;
      DBC_Accepted2      : IN     std_logic ;
      DataIn             : IN     std_logic_vector (15 DOWNTO 0);
      DataReqFlag1       : IN     std_logic ;
      DataReqFlag2       : IN     std_logic ;
      DataRxedFlag1      : IN     std_logic ;
      DataRxedFlag2      : IN     std_logic ;
      DataWrapActive1    : IN     std_logic ;
      DataWrapActive2    : IN     std_logic ;
      EarlyReplyRx1      : IN     std_logic ;
      EarlyReplyRx2      : IN     std_logic ;
      InitiateBIT_Rxed1  : IN     std_logic ;
      InitiateBIT_Rxed2  : IN     std_logic ;
      ModeCmd1           : IN     std_logic_vector (15 DOWNTO 0);
      ModeCmd2           : IN     std_logic_vector (15 DOWNTO 0);
      ModeData1          : IN     std_logic_vector (15 DOWNTO 0);
      ModeData2          : IN     std_logic_vector (15 DOWNTO 0);
      MyRtAddr           : IN     std_logic_vector (4 DOWNTO 0);
      MyRtAddrParity     : IN     std_logic ;
      NewModeCmd1        : IN     std_logic ;
      NewModeCmd2        : IN     std_logic ;
      Rd                 : IN     std_logic ;
      RtActiveBus        : IN     std_logic ;
      RxDataAddr1        : IN     std_logic_vector (9 DOWNTO 0);
      RxDataAddr2        : IN     std_logic_vector (9 DOWNTO 0);
      RxDataOut1         : IN     std_logic_vector (15 DOWNTO 0);
      RxDataOut2         : IN     std_logic_vector (15 DOWNTO 0);
      RxDataWr1          : IN     std_logic ;
      RxDataWr2          : IN     std_logic ;
      ServiceReqVector   : IN     std_logic_vector (15 DOWNTO 0);
      StatusRxed1        : IN     std_logic_vector (15 DOWNTO 0);
      StatusRxed2        : IN     std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag1    : IN     std_logic ;
      StatusRxedFlag2    : IN     std_logic ;
      Synchronize1       : IN     std_logic ;
      Synchronize2       : IN     std_logic ;
      TerminalFlag_Rxed1 : IN     std_logic ;
      TerminalFlag_Rxed2 : IN     std_logic ;
      TxAvail1           : IN     std_logic ;
      TxAvail2           : IN     std_logic ;
      TxDataAddr1        : IN     std_logic_vector (9 DOWNTO 0);
      TxDataAddr2        : IN     std_logic_vector (9 DOWNTO 0);
      TxOffOut1          : IN     std_logic ;
      TxOffOut2          : IN     std_logic ;
      UnexpectedEdgeCnt1 : IN     std_logic_vector (15 DOWNTO 0);
      UnexpectedEdgeCnt2 : IN     std_logic_vector (15 DOWNTO 0);
      Wr                 : IN     std_logic ;
      clk                : IN     std_logic ;
      nReset             : IN     std_logic ;
      tmr_GAP1           : IN     std_logic ;
      tmr_GAP2           : IN     std_logic ;
      tmr_NRP1           : IN     std_logic ;
      tmr_NRP2           : IN     std_logic ;
      tmr_REP1           : IN     std_logic ;
      tmr_REP2           : IN     std_logic ;
      tmr_SAF1           : IN     std_logic ;
      tmr_SAF2           : IN     std_logic ;
      BIT1               : OUT    std_logic_vector (15 DOWNTO 0);
      BroadcastEnable    : OUT    std_logic ;
      BusBusy            : OUT    std_logic ;
      Clear_InitiateBIT1 : OUT    std_logic ;
      Clear_InitiateBIT2 : OUT    std_logic ;
      Clear_Synchronize1 : OUT    std_logic ;
      Clear_Synchronize2 : OUT    std_logic ;
      CmdProcLen1        : OUT    std_logic_vector (15 DOWNTO 0);
      CmdProcLen2        : OUT    std_logic_vector (15 DOWNTO 0);
      CmdProcStart1      : OUT    std_logic_vector (15 DOWNTO 0);
      CmdProcStart2      : OUT    std_logic_vector (15 DOWNTO 0);
      DBC_Enable         : OUT    std_logic ;
      DataOut            : OUT    std_logic_vector (15 DOWNTO 0);
      DataValid          : OUT    std_logic ;
      EnableHwDataWrap   : OUT    std_logic ;
      Intr               : OUT    std_logic ;
      LegalModeBrdcst    : OUT    std_logic_vector (31 DOWNTO 0);
      LegalModeRx        : OUT    std_logic_vector (31 DOWNTO 0);
      LegalModeTx        : OUT    std_logic_vector (31 DOWNTO 0);
      LegalSubAddr       : OUT    std_logic_vector (31 DOWNTO 0);
      RtControl          : OUT    std_logic_vector (15 DOWNTO 0);
      SendMessage1       : OUT    std_logic ;
      SendMessage2       : OUT    std_logic ;
      ServiceReqVector1  : OUT    std_logic_vector (15 DOWNTO 0);
      TerminalFlag1      : OUT    std_logic ;
      TerminalFlag2      : OUT    std_logic ;
      TxDataIn1          : OUT    std_logic_vector (16 DOWNTO 0);
      TxDataIn2          : OUT    std_logic_vector (16 DOWNTO 0);
      datawrap_subaddr   : OUT    std_logic_vector (4 DOWNTO 0);
      nResetCore1        : OUT    std_logic ;
      nResetCore2        : OUT    std_logic ;
      reg_err_inj        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_1us        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_GAP        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_NRP        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_REP        : OUT    std_logic_vector (15 DOWNTO 0);
      reg_tmr_SAF        : OUT    std_logic_vector (15 DOWNTO 0);
      IsRT               : BUFFER std_logic ;
      MyRtAddrInt        : BUFFER std_logic_vector (4 DOWNTO 0);
      MyRtAddrParityInt  : BUFFER std_logic 
   );
   END COMPONENT;
   COMPONENT mil1553_singlebus
   GENERIC (
      CoreMode : core_mode_t := BCRT_MODE
   );
   PORT (
      BIT1              : IN     std_logic_vector (15 DOWNTO 0);
      BroadcastEnable   : IN     std_logic ;
      BusBusy           : IN     std_logic ;
      Clear_InitiateBIT : IN     std_logic ;
      Clear_Synchronize : IN     std_logic ;
      CmdProcLen        : IN     std_logic_vector (15 DOWNTO 0);
      CmdProcStart      : IN     std_logic_vector (15 DOWNTO 0);
      DBC_Enable        : IN     std_logic ;
      DataWrapSubAddr   : IN     std_logic_vector (4 DOWNTO 0);
      EnableHwDataWrap  : IN     std_logic ;
      InN               : IN     std_logic ;
      InP               : IN     std_logic ;
      IsRT              : IN     std_logic ;
      LegalModeBrdcst   : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeRx       : IN     std_logic_vector (31 DOWNTO 0);
      LegalModeTx       : IN     std_logic_vector (31 DOWNTO 0);
      LegalSubAddr      : IN     std_logic_vector (31 DOWNTO 0);
      MyRtAddr          : IN     std_logic_vector (4 DOWNTO 0);
      MyRtAddrParity    : IN     std_logic ;
      SendMessage       : IN     std_logic ;
      ServiceReqVector  : IN     std_logic_vector (15 DOWNTO 0);
      ServiceRequest    : IN     std_logic ;
      SubsystemFlag     : IN     std_logic ;
      TerminalFlagIn    : IN     std_logic ;
      TxDataIn          : IN     std_logic_vector (16 DOWNTO 0);
      TxOffIn           : IN     std_logic ;
      clk               : IN     std_logic ;
      nReset            : IN     std_logic ;
      reg_err_inj       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_1us       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_GAP       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_NRP       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_REP       : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_SAF       : IN     std_logic_vector (15 DOWNTO 0);
      BusActive         : OUT    std_logic ;
      BusReset_Rxed     : OUT    std_logic ;
      CmdRxed           : OUT    std_logic_vector (15 DOWNTO 0);
      DBC_Accepted      : OUT    std_logic ;
      DataReqFlag       : OUT    std_logic ;
      DataRxedFlag      : OUT    std_logic ;
      DataWrapActive    : OUT    std_logic ;
      EarlyReplyRx      : OUT    std_logic ;
      InitiateBIT_Rxed  : OUT    std_logic ;
      ModeCmd           : OUT    std_logic_vector (15 DOWNTO 0);
      ModeData          : OUT    std_logic_vector (15 DOWNTO 0);
      NewModeCmd        : OUT    std_logic ;
      OutEn             : OUT    std_logic ;
      OutN              : OUT    std_logic ;
      OutP              : OUT    std_logic ;
      RxDataAddr        : OUT    std_logic_vector (9 DOWNTO 0);
      RxDataOut         : OUT    std_logic_vector (15 DOWNTO 0);
      RxDataWr          : OUT    std_logic ;
      SelTxShutdown     : OUT    std_logic ;
      ShutdownData      : OUT    std_logic_vector (4 DOWNTO 0);
      StatusRxed        : OUT    std_logic_vector (15 DOWNTO 0);
      StatusRxedFlag    : OUT    std_logic ;
      Strobe            : OUT    std_logic ;
      Synchronize       : OUT    std_logic ;
      TerminalFlag      : OUT    std_logic ;
      TxAvail           : OUT    std_logic ;
      TxDataAddr        : OUT    std_logic_vector (9 DOWNTO 0);
      TxOffOut          : OUT    std_logic ;
      UnexpectedEdgeCnt : OUT    std_logic_vector (15 DOWNTO 0);
      tmr_GAP           : OUT    std_logic ;
      tmr_NRP           : OUT    std_logic ;
      tmr_REP           : OUT    std_logic ;
      tmr_SAF           : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT select_active_bus
   PORT (
      BusActive1       : IN     std_logic ;
      BusActive2       : IN     std_logic ;
      clk              : IN     std_logic ;
      nReset           : IN     std_logic ;
      BusSwapResetBus1 : OUT    std_logic ;
      BusSwapResetBus2 : OUT    std_logic ;
      RtActiveBus      : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : mil1553_cpu_interface USE ENTITY mil1553_lib.mil1553_cpu_interface;
   FOR ALL : mil1553_singlebus USE ENTITY mil1553_lib.mil1553_singlebus;
   FOR ALL : select_active_bus USE ENTITY mil1553_lib.select_active_bus;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 ebReset
   -- eb1 1         
   RtAddrParityOK <=  MyRtAddrInt(4) xor MyRtAddrInt(3) xor MyRtAddrInt(2) xor MyRtAddrInt(1) xor MyRtAddrInt(0) xor MyRtAddrParityInt;
   nResetBus1 <= '0' when (RtAddrParityOK = '0' or nResetCore1 = '0') else 
                           not BusSwapResetBus1 when IsRt = '1'  else 
                          nReset when (RtAddrParityOK = '1' and nResetCore1 = '1') else 
                            '0' when BusReset_Rxed1 = '1' or BusReset_Rxed2 = '1' else
                            '0';  
   nResetBus2 <= '0' when (RtAddrParityOK = '0' or nResetCore2 = '0') else 
                           not BusSwapResetBus2 when IsRt = '1' else
                          nReset when (RtAddrParityOK = '1' and nResetCore2 = '1') else
                            '0' when BusReset_Rxed1 = '1' or BusReset_Rxed2 = '1' else
                            '0';  
   nReset <= '0' when BusReset_Rxed1 = '1' or BusReset_Rxed2 = '1' else
                            nResetIn;  
   StatusRxed1 <= StatusRxed1A(15 downto 8) & not RtAddrParityOK & StatusRxed1A(6 downto 0);
   StatusRxed2 <= StatusRxed2A(15 downto 8) & not RtAddrParityOK & StatusRxed2A(6 downto 0);     

   -- HDL Embedded Text Block 2 ebTxOff
   -- ebTxOff 2       
   TxOffIn1 <= '1' when (SelTxShutdown2= '1' and ShutdownData2 = "00001") or (TxOffOut2 = '1') else
                       '0' when (SelTxShutdown2= '0' and ShutdownData2 = "00001") and (TxOffOut2 = '0') else
                        TxOffOut2;     
   TxOffIn2 <= '1' when (SelTxShutdown1= '1' and ShutdownData1 = "00010" ) or (TxOffOut1 = '1') else
                       '0' when (SelTxShutdown1= '0' and ShutdownData1 = "00010") and (TxOffOut1 = '0') else
                        TxOffOut1;      
                                  


   -- Instance port mappings.
   cpu_interface : mil1553_cpu_interface
      GENERIC MAP (
         CoreMode => CoreMode
      )
      PORT MAP (
         Addr               => Addr,
         BitWord            => BitWord,
         CmdRxed1           => CmdRxed1,
         CmdRxed2           => CmdRxed2,
         Cs                 => Cs,
         DBC_Accepted1      => DBC_Accepted1,
         DBC_Accepted2      => DBC_Accepted2,
         DataIn             => DataIn,
         DataReqFlag1       => DataReqFlag1,
         DataReqFlag2       => DataReqFlag2,
         DataRxedFlag1      => DataRxedFlag1,
         DataRxedFlag2      => DataRxedFlag2,
         DataWrapActive1    => DataWrapActive1,
         DataWrapActive2    => DataWrapActive2,
         EarlyReplyRx1      => EarlyReplyRx1,
         EarlyReplyRx2      => EarlyReplyRx2,
         InitiateBIT_Rxed1  => InitiateBIT_Rxed1,
         InitiateBIT_Rxed2  => InitiateBIT_Rxed2,
         ModeCmd1           => ModeCmd1,
         ModeCmd2           => ModeCmd2,
         ModeData1          => ModeData1,
         ModeData2          => ModeData2,
         MyRtAddr           => MyRtAddr,
         MyRtAddrParity     => MyRtAddrParity,
         NewModeCmd1        => NewModeCmd1,
         NewModeCmd2        => NewModeCmd2,
         Rd                 => Rd,
         RtActiveBus        => RtActiveBus,
         RxDataAddr1        => RxDataAddr1,
         RxDataAddr2        => RxDataAddr2,
         RxDataOut1         => RxDataOut1,
         RxDataOut2         => RxDataOut2,
         RxDataWr1          => RxDataWr1,
         RxDataWr2          => RxDataWr2,
         ServiceReqVector   => ServiceReqVector,
         StatusRxed1        => StatusRxed1,
         StatusRxed2        => StatusRxed2,
         StatusRxedFlag1    => StatusRxedFlag1,
         StatusRxedFlag2    => StatusRxedFlag2,
         Synchronize1       => Synchronize1,
         Synchronize2       => Synchronize2,
         TerminalFlag_Rxed1 => TerminalFlag_Rxed1,
         TerminalFlag_Rxed2 => TerminalFlag_Rxed2,
         TxAvail1           => TxAvail1,
         TxAvail2           => TxAvail2,
         TxDataAddr1        => TxDataAddr1,
         TxDataAddr2        => TxDataAddr2,
         TxOffOut1          => TxOffOut1,
         TxOffOut2          => TxOffOut2,
         UnexpectedEdgeCnt1 => UnexpectedEdgeCnt1,
         UnexpectedEdgeCnt2 => UnexpectedEdgeCnt2,
         Wr                 => Wr,
         clk                => clk,
         nReset             => nReset,
         tmr_GAP1           => tmr_GAP1,
         tmr_GAP2           => tmr_GAP2,
         tmr_NRP1           => tmr_NRP1,
         tmr_NRP2           => tmr_NRP2,
         tmr_REP1           => tmr_REP1,
         tmr_REP2           => tmr_REP2,
         tmr_SAF1           => tmr_SAF1,
         tmr_SAF2           => tmr_SAF2,
         BIT1               => BIT1,
         BroadcastEnable    => BroadcastEnable,
         BusBusy            => BusBusy,
         Clear_InitiateBIT1 => Clear_InitiateBIT1,
         Clear_InitiateBIT2 => Clear_InitiateBIT2,
         Clear_Synchronize1 => Clear_Synchronize1,
         Clear_Synchronize2 => Clear_Synchronize2,
         CmdProcLen1        => CmdProcLen1,
         CmdProcLen2        => CmdProcLen2,
         CmdProcStart1      => CmdProcStart1,
         CmdProcStart2      => CmdProcStart2,
         DBC_Enable         => DBC_Enable,
         DataOut            => DataOut,
         DataValid          => DataValid,
         EnableHwDataWrap   => EnableHwDataWrap,
         Intr               => Intr,
         LegalModeBrdcst    => LegalModeBrdcst,
         LegalModeRx        => LegalModeRx,
         LegalModeTx        => LegalModeTx,
         LegalSubAddr       => LegalSubAddr,
         RtControl          => RtControl,
         SendMessage1       => SendMessage1,
         SendMessage2       => SendMessage2,
         ServiceReqVector1  => ServiceReqVector1,
         TerminalFlag1      => TerminalFlagIn1,
         TerminalFlag2      => TerminalFlagIn2,
         TxDataIn1          => TxDataIn1,
         TxDataIn2          => TxDataIn2,
         datawrap_subaddr   => datawrap_subaddr,
         nResetCore1        => nResetCore1,
         nResetCore2        => nResetCore2,
         reg_err_inj        => reg_err_inj,
         reg_tmr_1us        => reg_tmr_1us,
         reg_tmr_GAP        => reg_tmr_GAP,
         reg_tmr_NRP        => reg_tmr_NRP,
         reg_tmr_REP        => reg_tmr_REP,
         reg_tmr_SAF        => reg_tmr_SAF,
         IsRT               => IsRT,
         MyRtAddrInt        => MyRtAddrInt,
         MyRtAddrParityInt  => MyRtAddrParityInt
      );
   Bus1 : mil1553_singlebus
      GENERIC MAP (
         CoreMode => CoreMode
      )
      PORT MAP (
         BIT1              => BIT1,
         BroadcastEnable   => BroadcastEnable,
         BusBusy           => BusBusy,
         Clear_InitiateBIT => Clear_InitiateBIT1,
         Clear_Synchronize => Clear_Synchronize1,
         CmdProcLen        => CmdProcLen1,
         CmdProcStart      => CmdProcStart1,
         DBC_Enable        => DBC_Enable,
         DataWrapSubAddr   => datawrap_subaddr,
         EnableHwDataWrap  => EnableHwDataWrap,
         InN               => InN1,
         InP               => InP1,
         IsRT              => IsRT,
         LegalModeBrdcst   => LegalModeBrdcst,
         LegalModeRx       => LegalModeRx,
         LegalModeTx       => LegalModeTx,
         LegalSubAddr      => LegalSubAddr,
         MyRtAddr          => MyRtAddrInt,
         MyRtAddrParity    => MyRtAddrParityInt,
         SendMessage       => SendMessage1,
         ServiceReqVector  => ServiceReqVector1,
         ServiceRequest    => ServiceRequest,
         SubsystemFlag     => SubsystemFlag,
         TerminalFlagIn    => TerminalFlagIn1,
         TxDataIn          => TxDataIn1,
         TxOffIn           => TxOffIn1,
         clk               => clk,
         nReset            => nResetBus1,
         reg_err_inj       => reg_err_inj,
         reg_tmr_1us       => reg_tmr_1us,
         reg_tmr_GAP       => reg_tmr_GAP,
         reg_tmr_NRP       => reg_tmr_NRP,
         reg_tmr_REP       => reg_tmr_REP,
         reg_tmr_SAF       => reg_tmr_SAF,
         BusActive         => BusActive1,
         BusReset_Rxed     => BusReset_Rxed1,
         CmdRxed           => CmdRxed1,
         DBC_Accepted      => DBC_Accepted1,
         DataReqFlag       => DataReqFlag1,
         DataRxedFlag      => DataRxedFlag1,
         DataWrapActive    => DataWrapActive1,
         EarlyReplyRx      => EarlyReplyRx1,
         InitiateBIT_Rxed  => InitiateBIT_Rxed1,
         ModeCmd           => ModeCmd1,
         ModeData          => ModeData1,
         NewModeCmd        => NewModeCmd1,
         OutEn             => OutEn1,
         OutN              => OutN1,
         OutP              => OutP1,
         RxDataAddr        => RxDataAddr1,
         RxDataOut         => RxDataOut1,
         RxDataWr          => RxDataWr1,
         SelTxShutdown     => SelTxShutdown1,
         ShutdownData      => ShutdownData1,
         StatusRxed        => StatusRxed1A,
         StatusRxedFlag    => StatusRxedFlag1,
         Strobe            => Strobe1,
         Synchronize       => Synchronize1,
         TerminalFlag      => TerminalFlag_Rxed1,
         TxAvail           => TxAvail1,
         TxDataAddr        => TxDataAddr1,
         TxOffOut          => TxOffOut1,
         UnexpectedEdgeCnt => UnexpectedEdgeCnt1,
         tmr_GAP           => tmr_GAP1,
         tmr_NRP           => tmr_NRP1,
         tmr_REP           => tmr_REP1,
         tmr_SAF           => tmr_SAF1
      );
   Bus2 : mil1553_singlebus
      GENERIC MAP (
         CoreMode => CoreMode
      )
      PORT MAP (
         BIT1              => BIT1,
         BroadcastEnable   => BroadcastEnable,
         BusBusy           => BusBusy,
         Clear_InitiateBIT => Clear_InitiateBIT2,
         Clear_Synchronize => Clear_Synchronize2,
         CmdProcLen        => CmdProcLen2,
         CmdProcStart      => CmdProcStart2,
         DBC_Enable        => DBC_Enable,
         DataWrapSubAddr   => datawrap_subaddr,
         EnableHwDataWrap  => EnableHwDataWrap,
         InN               => InN2,
         InP               => InP2,
         IsRT              => IsRT,
         LegalModeBrdcst   => LegalModeBrdcst,
         LegalModeRx       => LegalModeRx,
         LegalModeTx       => LegalModeTx,
         LegalSubAddr      => LegalSubAddr,
         MyRtAddr          => MyRtAddrInt,
         MyRtAddrParity    => MyRtAddrParityInt,
         SendMessage       => SendMessage2,
         ServiceReqVector  => ServiceReqVector1,
         ServiceRequest    => ServiceRequest,
         SubsystemFlag     => SubsystemFlag,
         TerminalFlagIn    => TerminalFlagIn2,
         TxDataIn          => TxDataIn2,
         TxOffIn           => TxOffIn2,
         clk               => clk,
         nReset            => nResetBus2,
         reg_err_inj       => reg_err_inj,
         reg_tmr_1us       => reg_tmr_1us,
         reg_tmr_GAP       => reg_tmr_GAP,
         reg_tmr_NRP       => reg_tmr_NRP,
         reg_tmr_REP       => reg_tmr_REP,
         reg_tmr_SAF       => reg_tmr_SAF,
         BusActive         => BusActive2,
         BusReset_Rxed     => BusReset_Rxed2,
         CmdRxed           => CmdRxed2,
         DBC_Accepted      => DBC_Accepted2,
         DataReqFlag       => DataReqFlag2,
         DataRxedFlag      => DataRxedFlag2,
         DataWrapActive    => DataWrapActive2,
         EarlyReplyRx      => EarlyReplyRx2,
         InitiateBIT_Rxed  => InitiateBIT_Rxed2,
         ModeCmd           => ModeCmd2,
         ModeData          => ModeData2,
         NewModeCmd        => NewModeCmd2,
         OutEn             => OutEn2,
         OutN              => OutN2,
         OutP              => OutP2,
         RxDataAddr        => RxDataAddr2,
         RxDataOut         => RxDataOut2,
         RxDataWr          => RxDataWr2,
         SelTxShutdown     => SelTxShutdown2,
         ShutdownData      => ShutdownData2,
         StatusRxed        => StatusRxed2A,
         StatusRxedFlag    => StatusRxedFlag2,
         Strobe            => Strobe2,
         Synchronize       => Synchronize2,
         TerminalFlag      => TerminalFlag_Rxed2,
         TxAvail           => TxAvail2,
         TxDataAddr        => TxDataAddr2,
         TxOffOut          => TxOffOut2,
         UnexpectedEdgeCnt => UnexpectedEdgeCnt2,
         tmr_GAP           => tmr_GAP2,
         tmr_NRP           => tmr_NRP2,
         tmr_REP           => tmr_REP2,
         tmr_SAF           => tmr_SAF2
      );
   sel_act_bus : select_active_bus
      PORT MAP (
         BusActive1       => BusActive1,
         BusActive2       => BusActive2,
         clk              => clk,
         nReset           => nReset,
         BusSwapResetBus1 => BusSwapResetBus1,
         BusSwapResetBus2 => BusSwapResetBus2,
         RtActiveBus      => RtActiveBus
      );


END struct;
