-- VHDL Entity mil1553_lib.mill1553_timers.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (jeansmithE313)
--          at - 22:31:27 05/10/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY mill1553_timers IS
   PORT( 
      SyncPosEdge     : IN     std_logic;
      clk             : IN     std_logic;
      nReset          : IN     std_logic;
      reg_tmr_1us     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_ERP     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_GAP     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_NRP     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_REP     : IN     std_logic_vector (15 DOWNTO 0);
      reg_tmr_SAF     : IN     std_logic_vector (15 DOWNTO 0);
      tmr_1us_Start   : IN     std_logic;
      tmr_1us_Stop    : IN     std_logic;
      tmr_25us_Start  : IN     std_logic;
      tmr_25us_Stop   : IN     std_logic;
      tmr_Blank_Start : IN     std_logic;
      tmr_Blank_Stop  : IN     std_logic;
      tmr_ERP_Reset   : IN     std_logic;
      tmr_ERP_Stop    : IN     std_logic;
      tmr_ERP_enable  : IN     std_logic;
      tmr_GAP_Start   : IN     std_logic;
      tmr_GAP_Stop    : IN     std_logic;
      tmr_NRP_Start   : IN     std_logic;
      tmr_NRP_Stop    : IN     std_logic;
      tmr_REP_Start   : IN     std_logic;
      tmr_REP_Stop    : IN     std_logic;
      tmr_SAF_Start   : IN     std_logic;
      tmr_SAF_Stop    : IN     std_logic;
      tmr_25us        : OUT    std_logic;
      tmr_Blank       : OUT    std_logic;
      tmr_ERP         : OUT    std_logic;
      tmr_GAP         : OUT    std_logic;
      tmr_NRP         : OUT    std_logic;
      tmr_REP         : OUT    std_logic;
      tmr_SAF         : OUT    std_logic;
      tmr_1us         : BUFFER std_logic
   );

-- Declarations

END mill1553_timers ;

-- VHDL Architecture mil1553_lib.mill1553_timers.struct
-- *********************************************************************************************************************
-- Company:         Al Tariq, Abu Dhabi
-- Created by:       jeansmith.UNKNOWN (jeansmithE313)
-- Date:                22:31:27 05/10/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
-- *********************************************************************************************************************
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY at_gen_lib;

ARCHITECTURE struct OF mill1553_timers IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL NRPtmrReset   : std_logic;
   SIGNAL reg_tmr_blank : std_logic_vector(15 DOWNTO 0);
   SIGNAL tmrEnable     : std_logic;
   SIGNAL tmr_25us_load : std_logic_vector(15 DOWNTO 0);
   SIGNAL tmr_NRP_Int   : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL tmr_25us_internal : std_logic;


   -- Component Declarations
   COMPONENT timer
   GENERIC (
      cTIMER_WIDTH : integer := 16      -- Specify the load_value bus width
   );
   PORT (
      nReset     : IN     std_logic ;
      load_value : IN     std_logic_vector ((cTIMER_WIDTH - 1) DOWNTO 0);
      en         : IN     std_logic ;
      tmrReset   : IN     std_logic ;
      tmrStop    : IN     std_logic ;
      Clk        : IN     std_logic ;
      timeout    : OUT    std_logic ;
      clockout   : OUT    std_logic ;
      pulse      : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : timer USE ENTITY at_gen_lib.timer;
   -- pragma synthesis_on


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 tmrEnable
   -- tmrEnable
   tmrEnable <= '1';    
                                    

   -- HDL Embedded Text Block 2 etmr100ns
   -- etmr100ns 2  
   tmr_25us_load <= X"0018";
   reg_tmr_Blank <= X"0190";
                                    

   -- HDL Embedded Text Block 3 ebOR
   -- ebOR 3
   NRPtmrReset <= tmr_NRP_Start;                                        

   -- HDL Embedded Text Block 4 eb1
   -- eb1 4 
   tmr_NRP <= tmr_NRP_Int or tmr_25us_internal;                                       


   -- Instance port mappings.
   timer_1uS : timer
      GENERIC MAP (
         cTIMER_WIDTH => 16         -- Specify the load_value bus width
      )
      PORT MAP (
         nReset     => nReset,
         load_value => reg_tmr_1us,
         en         => tmrEnable,
         tmrReset   => tmr_1us_Start,
         tmrStop    => tmr_1us_Stop,
         Clk        => clk,
         timeout    => OPEN,
         clockout   => OPEN,
         pulse      => tmr_1us
      );
   timer_25us : timer
      GENERIC MAP (
         cTIMER_WIDTH => 16         -- Specify the load_value bus width
      )
      PORT MAP (
         nReset     => nReset,
         load_value => tmr_25us_load,
         en         => tmr_1us,
         tmrReset   => tmr_25us_Start,
         tmrStop    => tmr_25us_Stop,
         Clk        => clk,
         timeout    => OPEN,
         clockout   => OPEN,
         pulse      => tmr_25us_internal
      );
   timer_Blank : timer
      GENERIC MAP (
         cTIMER_WIDTH => 16         -- Specify the load_value bus width
      )
      PORT MAP (
         nReset     => nReset,
         load_value => reg_tmr_blank,
         en         => tmrEnable,
         tmrReset   => tmr_Blank_Start,
         tmrStop    => tmr_Blank_Stop,
         Clk        => clk,
         timeout    => OPEN,
         clockout   => OPEN,
         pulse      => tmr_Blank
      );
   timer_ERP : timer
      GENERIC MAP (
         cTIMER_WIDTH => 16         -- Specify the load_value bus width
      )
      PORT MAP (
         nReset     => nReset,
         load_value => reg_tmr_ERP,
         en         => tmr_ERP_enable,
         tmrReset   => tmr_ERP_Reset,
         tmrStop    => tmr_ERP_Stop,
         Clk        => clk,
         timeout    => tmr_ERP,
         clockout   => OPEN,
         pulse      => OPEN
      );
   timer_GAP : timer
      GENERIC MAP (
         cTIMER_WIDTH => 16         -- Specify the load_value bus width
      )
      PORT MAP (
         nReset     => nReset,
         load_value => reg_tmr_GAP,
         en         => tmrEnable,
         tmrReset   => tmr_GAP_Start,
         tmrStop    => tmr_GAP_Stop,
         Clk        => clk,
         timeout    => tmr_GAP,
         clockout   => OPEN,
         pulse      => OPEN
      );
   timer_NRP : timer
      GENERIC MAP (
         cTIMER_WIDTH => 16         -- Specify the load_value bus width
      )
      PORT MAP (
         nReset     => nReset,
         load_value => reg_tmr_NRP,
         en         => tmrEnable,
         tmrReset   => NRPtmrReset,
         tmrStop    => tmr_NRP_Stop,
         Clk        => clk,
         timeout    => tmr_NRP_Int,
         clockout   => OPEN,
         pulse      => OPEN
      );
   timer_REP : timer
      GENERIC MAP (
         cTIMER_WIDTH => 16         -- Specify the load_value bus width
      )
      PORT MAP (
         nReset     => nReset,
         load_value => reg_tmr_REP,
         en         => tmrEnable,
         tmrReset   => tmr_REP_Start,
         tmrStop    => tmr_REP_Stop,
         Clk        => clk,
         timeout    => tmr_REP,
         clockout   => OPEN,
         pulse      => OPEN
      );
   timer_SAF : timer
      GENERIC MAP (
         cTIMER_WIDTH => 16         -- Specify the load_value bus width
      )
      PORT MAP (
         nReset     => nReset,
         load_value => reg_tmr_SAF,
         en         => tmr_1us,
         tmrReset   => tmr_SAF_Start,
         tmrStop    => tmr_SAF_Stop,
         Clk        => clk,
         timeout    => tmr_SAF,
         clockout   => OPEN,
         pulse      => OPEN
      );

   -- Implicit buffered output assignments
   tmr_25us <= tmr_25us_internal;

END struct;
