-- VHDL Entity mil1553_lib.repeat_timer.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (DESKTOP2)
--          at - 08:39:48 02/20/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
LIBRARY mil1553_lib;
USE mil1553_lib.mil1553.ALL;

ENTITY repeat_timer IS
   GENERIC( 
      CoreMode : core_mode_t := BCRT_MODE
   );
   PORT( 
      clk             : IN     std_logic;
      clk_en          : IN     std_logic;
      nReset          : IN     std_logic;
      reset           : IN     std_logic;
      stop            : IN     std_logic;
      timer1_config   : IN     std_logic_vector (15 DOWNTO 0);
      timer2_config   : IN     std_logic_vector (15 DOWNTO 0);
      clockout        : OUT    std_logic;
      pulse           : OUT    std_logic;
      timeout         : OUT    std_logic;
      timer1_clockout : BUFFER std_logic;
      timer1_pulse    : BUFFER std_logic;
      timer1_timeout  : BUFFER std_logic
   );

-- Declarations

END repeat_timer ;

-- VHDL Architecture mil1553_lib.repeat_timer.struct
-- *********************************************************************************************************************
-- Company:         Al Tariq, Abu Dhabi
-- Created by:       jeansmith.UNKNOWN (DESKTOP2)
-- Date:                08:40:33 02/20/2026
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
-- *********************************************************************************************************************
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY at_gen_lib;

ARCHITECTURE struct OF repeat_timer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clockout1        : std_logic;
   SIGNAL pulse1           : std_logic;
   SIGNAL timeout1         : std_logic;
   SIGNAL timer1_clockout1 : std_logic;
   SIGNAL timer1_pulse1    : std_logic;
   SIGNAL timer1_timeout1  : std_logic;


   -- Component Declarations
   COMPONENT timer_double
   PORT (
      clk             : IN     std_logic ;
      clk_en          : IN     std_logic ;
      nReset          : IN     std_logic ;
      reset           : IN     std_logic ;
      stop            : IN     std_logic ;
      timer1_config   : IN     std_logic_vector (15 DOWNTO 0);
      timer2_config   : IN     std_logic_vector (15 DOWNTO 0);
      clockout        : OUT    std_logic ;
      pulse           : OUT    std_logic ;
      timeout         : OUT    std_logic ;
      timer1_clockout : BUFFER std_logic ;
      timer1_pulse    : BUFFER std_logic ;
      timer1_timeout  : BUFFER std_logic 
   );
   END COMPONENT;


BEGIN
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 ebPortSelection
   -- ebPortSelection 1     
      -- Output port selection based on CoreMode generic
      -- If RT_MODE: set outputs constant low
      -- If BC_MODE: use timer outputs
      -- If BCRT_MODE: use IsRT signal low, use timer outputs otherwise set outputs low
      clockout <= '0' when (CoreMode = RT_MODE)  else clockout1;
      timeout <= '0' when (CoreMode = RT_MODE) else timeout1;
      pulse <= '0' when (CoreMode = RT_MODE) else pulse1;
      timer1_clockout <= '0' when (CoreMode = RT_MODE) else timer1_clockout1;
      timer1_timeout <= '0' when (CoreMode = RT_MODE) else timer1_timeout1;
      timer1_pulse <= '0' when (CoreMode = RT_MODE) else timer1_pulse1;
                                      


   -- Instance port mappings.

   gRepeatTimer: IF (CoreMode = BC_MODE or CoreMode = BCRT_MODE) GENERATE
   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : timer_double USE ENTITY at_gen_lib.timer_double;
   -- pragma synthesis_on

   BEGIN
      U_0 : timer_double
         PORT MAP (
            clk             => clk,
            clk_en          => clk_en,
            nReset          => nReset,
            reset           => reset,
            stop            => stop,
            timer1_config   => timer1_config,
            timer2_config   => timer2_config,
            clockout        => clockout1,
            pulse           => pulse1,
            timeout         => timeout1,
            timer1_clockout => timer1_clockout1,
            timer1_pulse    => timer1_pulse1,
            timer1_timeout  => timer1_timeout1
         );
   END;
   END GENERATE gRepeatTimer;

END struct;
