-- VHDL Entity mil1553_lib.select_active_bus.symbol
--
-- Created:
--          by - jeansmith.UNKNOWN (jeansmithE313)
--          at - 07:58:02 11/10/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY select_active_bus IS
   PORT( 
      BusActive1       : IN     std_logic;
      BusActive2       : IN     std_logic;
      clk              : IN     std_logic;
      nReset           : IN     std_logic;
      BusSwapResetBus1 : OUT    std_logic;
      BusSwapResetBus2 : OUT    std_logic;
      RtActiveBus      : OUT    std_logic
   );

-- Declarations

END select_active_bus ;

--
-- VHDL Architecture mil1553_lib.select_active_bus.fsm
--
-- Created:
--          by - jeansmith.UNKNOWN (jeansmithE313)
--          at - 08:04:26 11/10/2025
--
-- Generated by Siemens HDL Designer(TM) 2024.1 Built on 24 Jan 2024 at 17:42:50
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
 
ARCHITECTURE fsm OF select_active_bus IS

   TYPE STATE_TYPE IS (
      sIdle,
      sBus1Active,
      sBus2Active
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare any pre-registered internal signals
   SIGNAL BusSwapResetBus1_cld : std_logic ;
   SIGNAL BusSwapResetBus2_cld : std_logic ;
   SIGNAL RtActiveBus_cld : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      nReset
   )
   -----------------------------------------------------------------
   BEGIN
      IF (nReset = '0') THEN
         current_state <= sIdle;
         -- Default Reset Values
         BusSwapResetBus1_cld <= '0';
         BusSwapResetBus2_cld <= '0';
         RtActiveBus_cld <= '0';
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         -- Default Assignment To Internals
         BusSwapResetBus1_cld <= '0';
         BusSwapResetBus2_cld <= '0';

         -- Combined Actions
         CASE current_state IS
            WHEN sIdle => 
               IF (BusActive1 = '1') THEN 
                  BusSwapResetBus2_cld <= BusActive2;
                  RtActiveBus_cld <= '0';
               ELSIF (BusActive2 = '1') THEN 
                  BusSwapResetBus1_cld <= BusActive1;
                  RtActiveBus_cld <= '1';
               END IF;
            WHEN sBus1Active => 
               IF (BusActive2 = '1') THEN 
                  BusSwapResetBus1_cld <= BusActive1;
                  RtActiveBus_cld <= '1';
               END IF;
            WHEN sBus2Active => 
               IF (BusActive1 = '1') THEN 
                  BusSwapResetBus2_cld <= BusActive2;
                  RtActiveBus_cld <= '0';
               END IF;
            WHEN OTHERS =>
               NULL;
         END CASE;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      BusActive1,
      BusActive2,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      CASE current_state IS
         WHEN sIdle => 
            IF (BusActive1 = '1') THEN 
               next_state <= sBus1Active;
            ELSIF (BusActive2 = '1') THEN 
               next_state <= sBus2Active;
            ELSE
               next_state <= sIdle;
            END IF;
         WHEN sBus1Active => 
            IF (BusActive2 = '1') THEN 
               next_state <= sBus2Active;
            ELSIF (BusActive1 = '0') THEN 
               next_state <= sIdle;
            ELSE
               next_state <= sBus1Active;
            END IF;
         WHEN sBus2Active => 
            IF (BusActive1 = '1') THEN 
               next_state <= sBus1Active;
            ELSIF (BusActive2 = '0') THEN 
               next_state <= sIdle;
            ELSE
               next_state <= sBus2Active;
            END IF;
         WHEN OTHERS =>
            next_state <= sIdle;
      END CASE;
   END PROCESS nextstate_proc;
 
   -- Concurrent Statements
   -- Clocked output assignments
   BusSwapResetBus1 <= BusSwapResetBus1_cld;
   BusSwapResetBus2 <= BusSwapResetBus2_cld;
   RtActiveBus <= RtActiveBus_cld;
END fsm;
