// nios_conv_usb_1553.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module nios_conv_usb_1553 (
		input  wire        clk_clk,                      //              clk.clk
		input  wire        clk_50_clk,                   //           clk_50.clk
		input  wire        conv_registers_waitrequest,   //   conv_registers.waitrequest
		input  wire [15:0] conv_registers_readdata,      //                 .readdata
		input  wire        conv_registers_readdatavalid, //                 .readdatavalid
		output wire [0:0]  conv_registers_burstcount,    //                 .burstcount
		output wire [15:0] conv_registers_writedata,     //                 .writedata
		output wire [8:0]  conv_registers_address,       //                 .address
		output wire        conv_registers_write,         //                 .write
		output wire        conv_registers_read,          //                 .read
		output wire [1:0]  conv_registers_byteenable,    //                 .byteenable
		output wire        conv_registers_debugaccess,   //                 .debugaccess
		input  wire [15:0] discrete_inputs_export,       //  discrete_inputs.export
		output wire [15:0] discrete_outputs_export,      // discrete_outputs.export
		input  wire        mil1553_waitrequest,          //          mil1553.waitrequest
		input  wire [15:0] mil1553_readdata,             //                 .readdata
		input  wire        mil1553_readdatavalid,        //                 .readdatavalid
		output wire [0:0]  mil1553_burstcount,           //                 .burstcount
		output wire [15:0] mil1553_writedata,            //                 .writedata
		output wire [11:0] mil1553_address,              //                 .address
		output wire        mil1553_write,                //                 .write
		output wire        mil1553_read,                 //                 .read
		output wire [1:0]  mil1553_byteenable,           //                 .byteenable
		output wire        mil1553_debugaccess,          //                 .debugaccess
		input  wire        reset_reset_n,                //            reset.reset_n
		input  wire        reset_50_reset_n,             //         reset_50.reset_n
		input  wire        uart1_waitrequest,            //            uart1.waitrequest
		input  wire [15:0] uart1_readdata,               //                 .readdata
		input  wire        uart1_readdatavalid,          //                 .readdatavalid
		output wire [0:0]  uart1_burstcount,             //                 .burstcount
		output wire [15:0] uart1_writedata,              //                 .writedata
		output wire [8:0]  uart1_address,                //                 .address
		output wire        uart1_write,                  //                 .write
		output wire        uart1_read,                   //                 .read
		output wire [1:0]  uart1_byteenable,             //                 .byteenable
		output wire        uart1_debugaccess,            //                 .debugaccess
		input  wire        uart2_waitrequest,            //            uart2.waitrequest
		input  wire [15:0] uart2_readdata,               //                 .readdata
		input  wire        uart2_readdatavalid,          //                 .readdatavalid
		output wire [0:0]  uart2_burstcount,             //                 .burstcount
		output wire [15:0] uart2_writedata,              //                 .writedata
		output wire [8:0]  uart2_address,                //                 .address
		output wire        uart2_write,                  //                 .write
		output wire        uart2_read,                   //                 .read
		output wire [1:0]  uart2_byteenable,             //                 .byteenable
		output wire        uart2_debugaccess             //                 .debugaccess
	);

	wire  [31:0] nios2_gen2_data_master_readdata;                          // mm_interconnect_0:NIOS2_GEN2_data_master_readdata -> NIOS2_GEN2:d_readdata
	wire         nios2_gen2_data_master_waitrequest;                       // mm_interconnect_0:NIOS2_GEN2_data_master_waitrequest -> NIOS2_GEN2:d_waitrequest
	wire         nios2_gen2_data_master_debugaccess;                       // NIOS2_GEN2:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:NIOS2_GEN2_data_master_debugaccess
	wire  [21:0] nios2_gen2_data_master_address;                           // NIOS2_GEN2:d_address -> mm_interconnect_0:NIOS2_GEN2_data_master_address
	wire   [3:0] nios2_gen2_data_master_byteenable;                        // NIOS2_GEN2:d_byteenable -> mm_interconnect_0:NIOS2_GEN2_data_master_byteenable
	wire         nios2_gen2_data_master_read;                              // NIOS2_GEN2:d_read -> mm_interconnect_0:NIOS2_GEN2_data_master_read
	wire         nios2_gen2_data_master_write;                             // NIOS2_GEN2:d_write -> mm_interconnect_0:NIOS2_GEN2_data_master_write
	wire  [31:0] nios2_gen2_data_master_writedata;                         // NIOS2_GEN2:d_writedata -> mm_interconnect_0:NIOS2_GEN2_data_master_writedata
	wire  [31:0] nios2_gen2_instruction_master_readdata;                   // mm_interconnect_0:NIOS2_GEN2_instruction_master_readdata -> NIOS2_GEN2:i_readdata
	wire         nios2_gen2_instruction_master_waitrequest;                // mm_interconnect_0:NIOS2_GEN2_instruction_master_waitrequest -> NIOS2_GEN2:i_waitrequest
	wire  [21:0] nios2_gen2_instruction_master_address;                    // NIOS2_GEN2:i_address -> mm_interconnect_0:NIOS2_GEN2_instruction_master_address
	wire         nios2_gen2_instruction_master_read;                       // NIOS2_GEN2:i_read -> mm_interconnect_0:NIOS2_GEN2_instruction_master_read
	wire  [31:0] mm_interconnect_0_dual_boot_avalon_readdata;              // dual_boot:avmm_rcv_readdata -> mm_interconnect_0:dual_boot_avalon_readdata
	wire   [2:0] mm_interconnect_0_dual_boot_avalon_address;               // mm_interconnect_0:dual_boot_avalon_address -> dual_boot:avmm_rcv_address
	wire         mm_interconnect_0_dual_boot_avalon_read;                  // mm_interconnect_0:dual_boot_avalon_read -> dual_boot:avmm_rcv_read
	wire         mm_interconnect_0_dual_boot_avalon_write;                 // mm_interconnect_0:dual_boot_avalon_write -> dual_boot:avmm_rcv_write
	wire  [31:0] mm_interconnect_0_dual_boot_avalon_writedata;             // mm_interconnect_0:dual_boot_avalon_writedata -> dual_boot:avmm_rcv_writedata
	wire         mm_interconnect_0_jtaguart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:JTagUart_avalon_jtag_slave_chipselect -> JTagUart:av_chipselect
	wire  [31:0] mm_interconnect_0_jtaguart_avalon_jtag_slave_readdata;    // JTagUart:av_readdata -> mm_interconnect_0:JTagUart_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_jtaguart_avalon_jtag_slave_waitrequest; // JTagUart:av_waitrequest -> mm_interconnect_0:JTagUart_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_jtaguart_avalon_jtag_slave_address;     // mm_interconnect_0:JTagUart_avalon_jtag_slave_address -> JTagUart:av_address
	wire         mm_interconnect_0_jtaguart_avalon_jtag_slave_read;        // mm_interconnect_0:JTagUart_avalon_jtag_slave_read -> JTagUart:av_read_n
	wire         mm_interconnect_0_jtaguart_avalon_jtag_slave_write;       // mm_interconnect_0:JTagUart_avalon_jtag_slave_write -> JTagUart:av_write_n
	wire  [31:0] mm_interconnect_0_jtaguart_avalon_jtag_slave_writedata;   // mm_interconnect_0:JTagUart_avalon_jtag_slave_writedata -> JTagUart:av_writedata
	wire  [31:0] mm_interconnect_0_max10_flash_csr_readdata;               // MAX10_FLASH:avmm_csr_readdata -> mm_interconnect_0:MAX10_FLASH_csr_readdata
	wire   [0:0] mm_interconnect_0_max10_flash_csr_address;                // mm_interconnect_0:MAX10_FLASH_csr_address -> MAX10_FLASH:avmm_csr_addr
	wire         mm_interconnect_0_max10_flash_csr_read;                   // mm_interconnect_0:MAX10_FLASH_csr_read -> MAX10_FLASH:avmm_csr_read
	wire         mm_interconnect_0_max10_flash_csr_write;                  // mm_interconnect_0:MAX10_FLASH_csr_write -> MAX10_FLASH:avmm_csr_write
	wire  [31:0] mm_interconnect_0_max10_flash_csr_writedata;              // mm_interconnect_0:MAX10_FLASH_csr_writedata -> MAX10_FLASH:avmm_csr_writedata
	wire  [31:0] mm_interconnect_0_max10_flash_data_readdata;              // MAX10_FLASH:avmm_data_readdata -> mm_interconnect_0:MAX10_FLASH_data_readdata
	wire         mm_interconnect_0_max10_flash_data_waitrequest;           // MAX10_FLASH:avmm_data_waitrequest -> mm_interconnect_0:MAX10_FLASH_data_waitrequest
	wire  [17:0] mm_interconnect_0_max10_flash_data_address;               // mm_interconnect_0:MAX10_FLASH_data_address -> MAX10_FLASH:avmm_data_addr
	wire         mm_interconnect_0_max10_flash_data_read;                  // mm_interconnect_0:MAX10_FLASH_data_read -> MAX10_FLASH:avmm_data_read
	wire         mm_interconnect_0_max10_flash_data_readdatavalid;         // MAX10_FLASH:avmm_data_readdatavalid -> mm_interconnect_0:MAX10_FLASH_data_readdatavalid
	wire         mm_interconnect_0_max10_flash_data_write;                 // mm_interconnect_0:MAX10_FLASH_data_write -> MAX10_FLASH:avmm_data_write
	wire  [31:0] mm_interconnect_0_max10_flash_data_writedata;             // mm_interconnect_0:MAX10_FLASH_data_writedata -> MAX10_FLASH:avmm_data_writedata
	wire   [3:0] mm_interconnect_0_max10_flash_data_burstcount;            // mm_interconnect_0:MAX10_FLASH_data_burstcount -> MAX10_FLASH:avmm_data_burstcount
	wire  [31:0] mm_interconnect_0_nios2_gen2_debug_mem_slave_readdata;    // NIOS2_GEN2:debug_mem_slave_readdata -> mm_interconnect_0:NIOS2_GEN2_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios2_gen2_debug_mem_slave_waitrequest; // NIOS2_GEN2:debug_mem_slave_waitrequest -> mm_interconnect_0:NIOS2_GEN2_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios2_gen2_debug_mem_slave_debugaccess; // mm_interconnect_0:NIOS2_GEN2_debug_mem_slave_debugaccess -> NIOS2_GEN2:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios2_gen2_debug_mem_slave_address;     // mm_interconnect_0:NIOS2_GEN2_debug_mem_slave_address -> NIOS2_GEN2:debug_mem_slave_address
	wire         mm_interconnect_0_nios2_gen2_debug_mem_slave_read;        // mm_interconnect_0:NIOS2_GEN2_debug_mem_slave_read -> NIOS2_GEN2:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios2_gen2_debug_mem_slave_byteenable;  // mm_interconnect_0:NIOS2_GEN2_debug_mem_slave_byteenable -> NIOS2_GEN2:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios2_gen2_debug_mem_slave_write;       // mm_interconnect_0:NIOS2_GEN2_debug_mem_slave_write -> NIOS2_GEN2:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios2_gen2_debug_mem_slave_writedata;   // mm_interconnect_0:NIOS2_GEN2_debug_mem_slave_writedata -> NIOS2_GEN2:debug_mem_slave_writedata
	wire  [15:0] mm_interconnect_0_registers_s0_readdata;                  // Registers:s0_readdata -> mm_interconnect_0:Registers_s0_readdata
	wire         mm_interconnect_0_registers_s0_waitrequest;               // Registers:s0_waitrequest -> mm_interconnect_0:Registers_s0_waitrequest
	wire         mm_interconnect_0_registers_s0_debugaccess;               // mm_interconnect_0:Registers_s0_debugaccess -> Registers:s0_debugaccess
	wire   [8:0] mm_interconnect_0_registers_s0_address;                   // mm_interconnect_0:Registers_s0_address -> Registers:s0_address
	wire         mm_interconnect_0_registers_s0_read;                      // mm_interconnect_0:Registers_s0_read -> Registers:s0_read
	wire   [1:0] mm_interconnect_0_registers_s0_byteenable;                // mm_interconnect_0:Registers_s0_byteenable -> Registers:s0_byteenable
	wire         mm_interconnect_0_registers_s0_readdatavalid;             // Registers:s0_readdatavalid -> mm_interconnect_0:Registers_s0_readdatavalid
	wire         mm_interconnect_0_registers_s0_write;                     // mm_interconnect_0:Registers_s0_write -> Registers:s0_write
	wire  [15:0] mm_interconnect_0_registers_s0_writedata;                 // mm_interconnect_0:Registers_s0_writedata -> Registers:s0_writedata
	wire   [0:0] mm_interconnect_0_registers_s0_burstcount;                // mm_interconnect_0:Registers_s0_burstcount -> Registers:s0_burstcount
	wire  [15:0] mm_interconnect_0_uart1_s0_readdata;                      // Uart1:s0_readdata -> mm_interconnect_0:Uart1_s0_readdata
	wire         mm_interconnect_0_uart1_s0_waitrequest;                   // Uart1:s0_waitrequest -> mm_interconnect_0:Uart1_s0_waitrequest
	wire         mm_interconnect_0_uart1_s0_debugaccess;                   // mm_interconnect_0:Uart1_s0_debugaccess -> Uart1:s0_debugaccess
	wire   [8:0] mm_interconnect_0_uart1_s0_address;                       // mm_interconnect_0:Uart1_s0_address -> Uart1:s0_address
	wire         mm_interconnect_0_uart1_s0_read;                          // mm_interconnect_0:Uart1_s0_read -> Uart1:s0_read
	wire   [1:0] mm_interconnect_0_uart1_s0_byteenable;                    // mm_interconnect_0:Uart1_s0_byteenable -> Uart1:s0_byteenable
	wire         mm_interconnect_0_uart1_s0_readdatavalid;                 // Uart1:s0_readdatavalid -> mm_interconnect_0:Uart1_s0_readdatavalid
	wire         mm_interconnect_0_uart1_s0_write;                         // mm_interconnect_0:Uart1_s0_write -> Uart1:s0_write
	wire  [15:0] mm_interconnect_0_uart1_s0_writedata;                     // mm_interconnect_0:Uart1_s0_writedata -> Uart1:s0_writedata
	wire   [0:0] mm_interconnect_0_uart1_s0_burstcount;                    // mm_interconnect_0:Uart1_s0_burstcount -> Uart1:s0_burstcount
	wire  [15:0] mm_interconnect_0_uart2_s0_readdata;                      // Uart2:s0_readdata -> mm_interconnect_0:Uart2_s0_readdata
	wire         mm_interconnect_0_uart2_s0_waitrequest;                   // Uart2:s0_waitrequest -> mm_interconnect_0:Uart2_s0_waitrequest
	wire         mm_interconnect_0_uart2_s0_debugaccess;                   // mm_interconnect_0:Uart2_s0_debugaccess -> Uart2:s0_debugaccess
	wire   [8:0] mm_interconnect_0_uart2_s0_address;                       // mm_interconnect_0:Uart2_s0_address -> Uart2:s0_address
	wire         mm_interconnect_0_uart2_s0_read;                          // mm_interconnect_0:Uart2_s0_read -> Uart2:s0_read
	wire   [1:0] mm_interconnect_0_uart2_s0_byteenable;                    // mm_interconnect_0:Uart2_s0_byteenable -> Uart2:s0_byteenable
	wire         mm_interconnect_0_uart2_s0_readdatavalid;                 // Uart2:s0_readdatavalid -> mm_interconnect_0:Uart2_s0_readdatavalid
	wire         mm_interconnect_0_uart2_s0_write;                         // mm_interconnect_0:Uart2_s0_write -> Uart2:s0_write
	wire  [15:0] mm_interconnect_0_uart2_s0_writedata;                     // mm_interconnect_0:Uart2_s0_writedata -> Uart2:s0_writedata
	wire   [0:0] mm_interconnect_0_uart2_s0_burstcount;                    // mm_interconnect_0:Uart2_s0_burstcount -> Uart2:s0_burstcount
	wire  [15:0] mm_interconnect_0_mil1553_s0_readdata;                    // Mil1553:s0_readdata -> mm_interconnect_0:Mil1553_s0_readdata
	wire         mm_interconnect_0_mil1553_s0_waitrequest;                 // Mil1553:s0_waitrequest -> mm_interconnect_0:Mil1553_s0_waitrequest
	wire         mm_interconnect_0_mil1553_s0_debugaccess;                 // mm_interconnect_0:Mil1553_s0_debugaccess -> Mil1553:s0_debugaccess
	wire  [11:0] mm_interconnect_0_mil1553_s0_address;                     // mm_interconnect_0:Mil1553_s0_address -> Mil1553:s0_address
	wire         mm_interconnect_0_mil1553_s0_read;                        // mm_interconnect_0:Mil1553_s0_read -> Mil1553:s0_read
	wire   [1:0] mm_interconnect_0_mil1553_s0_byteenable;                  // mm_interconnect_0:Mil1553_s0_byteenable -> Mil1553:s0_byteenable
	wire         mm_interconnect_0_mil1553_s0_readdatavalid;               // Mil1553:s0_readdatavalid -> mm_interconnect_0:Mil1553_s0_readdatavalid
	wire         mm_interconnect_0_mil1553_s0_write;                       // mm_interconnect_0:Mil1553_s0_write -> Mil1553:s0_write
	wire  [15:0] mm_interconnect_0_mil1553_s0_writedata;                   // mm_interconnect_0:Mil1553_s0_writedata -> Mil1553:s0_writedata
	wire   [0:0] mm_interconnect_0_mil1553_s0_burstcount;                  // mm_interconnect_0:Mil1553_s0_burstcount -> Mil1553:s0_burstcount
	wire         mm_interconnect_0_onchip_ram_32k_s1_chipselect;           // mm_interconnect_0:ONCHIP_RAM_32k_s1_chipselect -> ONCHIP_RAM_32k:chipselect
	wire  [31:0] mm_interconnect_0_onchip_ram_32k_s1_readdata;             // ONCHIP_RAM_32k:readdata -> mm_interconnect_0:ONCHIP_RAM_32k_s1_readdata
	wire  [13:0] mm_interconnect_0_onchip_ram_32k_s1_address;              // mm_interconnect_0:ONCHIP_RAM_32k_s1_address -> ONCHIP_RAM_32k:address
	wire   [3:0] mm_interconnect_0_onchip_ram_32k_s1_byteenable;           // mm_interconnect_0:ONCHIP_RAM_32k_s1_byteenable -> ONCHIP_RAM_32k:byteenable
	wire         mm_interconnect_0_onchip_ram_32k_s1_write;                // mm_interconnect_0:ONCHIP_RAM_32k_s1_write -> ONCHIP_RAM_32k:write
	wire  [31:0] mm_interconnect_0_onchip_ram_32k_s1_writedata;            // mm_interconnect_0:ONCHIP_RAM_32k_s1_writedata -> ONCHIP_RAM_32k:writedata
	wire         mm_interconnect_0_onchip_ram_32k_s1_clken;                // mm_interconnect_0:ONCHIP_RAM_32k_s1_clken -> ONCHIP_RAM_32k:clken
	wire         mm_interconnect_0_output_signals_s1_chipselect;           // mm_interconnect_0:Output_Signals_s1_chipselect -> Output_Signals:chipselect
	wire  [31:0] mm_interconnect_0_output_signals_s1_readdata;             // Output_Signals:readdata -> mm_interconnect_0:Output_Signals_s1_readdata
	wire   [2:0] mm_interconnect_0_output_signals_s1_address;              // mm_interconnect_0:Output_Signals_s1_address -> Output_Signals:address
	wire         mm_interconnect_0_output_signals_s1_write;                // mm_interconnect_0:Output_Signals_s1_write -> Output_Signals:write_n
	wire  [31:0] mm_interconnect_0_output_signals_s1_writedata;            // mm_interconnect_0:Output_Signals_s1_writedata -> Output_Signals:writedata
	wire         mm_interconnect_0_input_signals_s1_chipselect;            // mm_interconnect_0:Input_Signals_s1_chipselect -> Input_Signals:chipselect
	wire  [31:0] mm_interconnect_0_input_signals_s1_readdata;              // Input_Signals:readdata -> mm_interconnect_0:Input_Signals_s1_readdata
	wire   [1:0] mm_interconnect_0_input_signals_s1_address;               // mm_interconnect_0:Input_Signals_s1_address -> Input_Signals:address
	wire         mm_interconnect_0_input_signals_s1_write;                 // mm_interconnect_0:Input_Signals_s1_write -> Input_Signals:write_n
	wire  [31:0] mm_interconnect_0_input_signals_s1_writedata;             // mm_interconnect_0:Input_Signals_s1_writedata -> Input_Signals:writedata
	wire         irq_mapper_receiver0_irq;                                 // JTagUart:av_irq -> irq_mapper:receiver0_irq
	wire         irq_mapper_receiver1_irq;                                 // Input_Signals:irq -> irq_mapper:receiver1_irq
	wire  [31:0] nios2_gen2_irq_irq;                                       // irq_mapper:sender_irq -> NIOS2_GEN2:irq
	wire         rst_controller_reset_out_reset;                           // rst_controller:reset_out -> [Input_Signals:reset_n, MAX10_FLASH:reset_n, Mil1553:reset, NIOS2_GEN2:reset_n, ONCHIP_RAM_32k:reset, Output_Signals:reset_n, Registers:reset, Uart1:reset, Uart2:reset, irq_mapper:reset, mm_interconnect_0:NIOS2_GEN2_reset_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                       // rst_controller:reset_req -> [NIOS2_GEN2:reset_req, ONCHIP_RAM_32k:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                       // rst_controller_001:reset_out -> [JTagUart:rst_n, mm_interconnect_0:JTagUart_reset_reset_bridge_in_reset_reset]
	wire         nios2_gen2_debug_reset_request_reset;                     // NIOS2_GEN2:debug_reset_request -> rst_controller_001:reset_in1
	wire         rst_controller_002_reset_out_reset;                       // rst_controller_002:reset_out -> [dual_boot:nreset, mm_interconnect_0:dual_boot_nreset_reset_bridge_in_reset_reset]

	nios_conv_usb_1553_Input_Signals input_signals (
		.clk        (clk_clk),                                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),               //               reset.reset_n
		.address    (mm_interconnect_0_input_signals_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_input_signals_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_input_signals_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_input_signals_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_input_signals_s1_readdata),   //                    .readdata
		.in_port    (discrete_inputs_export),                        // external_connection.export
		.irq        (irq_mapper_receiver1_irq)                       //                 irq.irq
	);

	nios_conv_usb_1553_JTagUart jtaguart (
		.clk            (clk_clk),                                                  //               clk.clk
		.rst_n          (~rst_controller_001_reset_out_reset),                      //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtaguart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtaguart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtaguart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtaguart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtaguart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtaguart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtaguart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                                  //               irq.irq
	);

	altera_onchip_flash #(
		.INIT_FILENAME                       (""),
		.INIT_FILENAME_SIM                   (""),
		.DEVICE_FAMILY                       ("MAX 10"),
		.PART_NAME                           ("10M16SAE144I7G"),
		.DEVICE_ID                           ("16"),
		.SECTOR1_START_ADDR                  (0),
		.SECTOR1_END_ADDR                    (4095),
		.SECTOR2_START_ADDR                  (4096),
		.SECTOR2_END_ADDR                    (8191),
		.SECTOR3_START_ADDR                  (8192),
		.SECTOR3_END_ADDR                    (47103),
		.SECTOR4_START_ADDR                  (47104),
		.SECTOR4_END_ADDR                    (75775),
		.SECTOR5_START_ADDR                  (75776),
		.SECTOR5_END_ADDR                    (143359),
		.MIN_VALID_ADDR                      (0),
		.MAX_VALID_ADDR                      (143359),
		.MIN_UFM_VALID_ADDR                  (0),
		.MAX_UFM_VALID_ADDR                  (8191),
		.SECTOR1_MAP                         (1),
		.SECTOR2_MAP                         (2),
		.SECTOR3_MAP                         (3),
		.SECTOR4_MAP                         (4),
		.SECTOR5_MAP                         (5),
		.ADDR_RANGE1_END_ADDR                (143359),
		.ADDR_RANGE2_END_ADDR                (143359),
		.ADDR_RANGE1_OFFSET                  (1024),
		.ADDR_RANGE2_OFFSET                  (0),
		.ADDR_RANGE3_OFFSET                  (0),
		.AVMM_DATA_ADDR_WIDTH                (18),
		.AVMM_DATA_DATA_WIDTH                (32),
		.AVMM_DATA_BURSTCOUNT_WIDTH          (4),
		.SECTOR_READ_PROTECTION_MODE         (0),
		.FLASH_SEQ_READ_DATA_COUNT           (4),
		.FLASH_ADDR_ALIGNMENT_BITS           (2),
		.FLASH_READ_CYCLE_MAX_INDEX          (4),
		.FLASH_RESET_CYCLE_MAX_INDEX         (25),
		.FLASH_BUSY_TIMEOUT_CYCLE_MAX_INDEX  (120),
		.FLASH_ERASE_TIMEOUT_CYCLE_MAX_INDEX (35000000),
		.FLASH_WRITE_TIMEOUT_CYCLE_MAX_INDEX (30500),
		.PARALLEL_MODE                       (1),
		.READ_AND_WRITE_MODE                 (1),
		.WRAPPING_BURST_MODE                 (0),
		.IS_DUAL_BOOT                        ("True"),
		.IS_ERAM_SKIP                        ("True"),
		.IS_COMPRESSED_IMAGE                 ("True")
	) max10_flash (
		.clock                   (clk_clk),                                          //    clk.clk
		.reset_n                 (~rst_controller_reset_out_reset),                  // nreset.reset_n
		.avmm_data_addr          (mm_interconnect_0_max10_flash_data_address),       //   data.address
		.avmm_data_read          (mm_interconnect_0_max10_flash_data_read),          //       .read
		.avmm_data_writedata     (mm_interconnect_0_max10_flash_data_writedata),     //       .writedata
		.avmm_data_write         (mm_interconnect_0_max10_flash_data_write),         //       .write
		.avmm_data_readdata      (mm_interconnect_0_max10_flash_data_readdata),      //       .readdata
		.avmm_data_waitrequest   (mm_interconnect_0_max10_flash_data_waitrequest),   //       .waitrequest
		.avmm_data_readdatavalid (mm_interconnect_0_max10_flash_data_readdatavalid), //       .readdatavalid
		.avmm_data_burstcount    (mm_interconnect_0_max10_flash_data_burstcount),    //       .burstcount
		.avmm_csr_addr           (mm_interconnect_0_max10_flash_csr_address),        //    csr.address
		.avmm_csr_read           (mm_interconnect_0_max10_flash_csr_read),           //       .read
		.avmm_csr_writedata      (mm_interconnect_0_max10_flash_csr_writedata),      //       .writedata
		.avmm_csr_write          (mm_interconnect_0_max10_flash_csr_write),          //       .write
		.avmm_csr_readdata       (mm_interconnect_0_max10_flash_csr_readdata)        //       .readdata
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (12),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) mil1553 (
		.clk              (clk_clk),                                    //   clk.clk
		.reset            (rst_controller_reset_out_reset),             // reset.reset
		.s0_waitrequest   (mm_interconnect_0_mil1553_s0_waitrequest),   //    s0.waitrequest
		.s0_readdata      (mm_interconnect_0_mil1553_s0_readdata),      //      .readdata
		.s0_readdatavalid (mm_interconnect_0_mil1553_s0_readdatavalid), //      .readdatavalid
		.s0_burstcount    (mm_interconnect_0_mil1553_s0_burstcount),    //      .burstcount
		.s0_writedata     (mm_interconnect_0_mil1553_s0_writedata),     //      .writedata
		.s0_address       (mm_interconnect_0_mil1553_s0_address),       //      .address
		.s0_write         (mm_interconnect_0_mil1553_s0_write),         //      .write
		.s0_read          (mm_interconnect_0_mil1553_s0_read),          //      .read
		.s0_byteenable    (mm_interconnect_0_mil1553_s0_byteenable),    //      .byteenable
		.s0_debugaccess   (mm_interconnect_0_mil1553_s0_debugaccess),   //      .debugaccess
		.m0_waitrequest   (mil1553_waitrequest),                        //    m0.waitrequest
		.m0_readdata      (mil1553_readdata),                           //      .readdata
		.m0_readdatavalid (mil1553_readdatavalid),                      //      .readdatavalid
		.m0_burstcount    (mil1553_burstcount),                         //      .burstcount
		.m0_writedata     (mil1553_writedata),                          //      .writedata
		.m0_address       (mil1553_address),                            //      .address
		.m0_write         (mil1553_write),                              //      .write
		.m0_read          (mil1553_read),                               //      .read
		.m0_byteenable    (mil1553_byteenable),                         //      .byteenable
		.m0_debugaccess   (mil1553_debugaccess),                        //      .debugaccess
		.s0_response      (),                                           // (terminated)
		.m0_response      (2'b00)                                       // (terminated)
	);

	nios_conv_usb_1553_NIOS2_GEN2 nios2_gen2 (
		.clk                                 (clk_clk),                                                  //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                          //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                       //                          .reset_req
		.d_address                           (nios2_gen2_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios2_gen2_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios2_gen2_data_master_read),                              //                          .read
		.d_readdata                          (nios2_gen2_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios2_gen2_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios2_gen2_data_master_write),                             //                          .write
		.d_writedata                         (nios2_gen2_data_master_writedata),                         //                          .writedata
		.debug_mem_slave_debugaccess_to_roms (nios2_gen2_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios2_gen2_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios2_gen2_instruction_master_read),                       //                          .read
		.i_readdata                          (nios2_gen2_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios2_gen2_instruction_master_waitrequest),                //                          .waitrequest
		.irq                                 (nios2_gen2_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios2_gen2_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios2_gen2_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios2_gen2_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios2_gen2_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios2_gen2_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios2_gen2_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios2_gen2_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios2_gen2_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios2_gen2_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                          // custom_instruction_master.readra
	);

	nios_conv_usb_1553_ONCHIP_RAM_32k onchip_ram_32k (
		.clk        (clk_clk),                                        //   clk1.clk
		.address    (mm_interconnect_0_onchip_ram_32k_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_onchip_ram_32k_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_onchip_ram_32k_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_onchip_ram_32k_s1_write),      //       .write
		.readdata   (mm_interconnect_0_onchip_ram_32k_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_onchip_ram_32k_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_onchip_ram_32k_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                 // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),             //       .reset_req
		.freeze     (1'b0)                                            // (terminated)
	);

	nios_conv_usb_1553_Output_Signals output_signals (
		.clk        (clk_clk),                                        //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),                //               reset.reset_n
		.address    (mm_interconnect_0_output_signals_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_output_signals_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_output_signals_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_output_signals_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_output_signals_s1_readdata),   //                    .readdata
		.out_port   (discrete_outputs_export)                         // external_connection.export
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (9),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) registers (
		.clk              (clk_clk),                                      //   clk.clk
		.reset            (rst_controller_reset_out_reset),               // reset.reset
		.s0_waitrequest   (mm_interconnect_0_registers_s0_waitrequest),   //    s0.waitrequest
		.s0_readdata      (mm_interconnect_0_registers_s0_readdata),      //      .readdata
		.s0_readdatavalid (mm_interconnect_0_registers_s0_readdatavalid), //      .readdatavalid
		.s0_burstcount    (mm_interconnect_0_registers_s0_burstcount),    //      .burstcount
		.s0_writedata     (mm_interconnect_0_registers_s0_writedata),     //      .writedata
		.s0_address       (mm_interconnect_0_registers_s0_address),       //      .address
		.s0_write         (mm_interconnect_0_registers_s0_write),         //      .write
		.s0_read          (mm_interconnect_0_registers_s0_read),          //      .read
		.s0_byteenable    (mm_interconnect_0_registers_s0_byteenable),    //      .byteenable
		.s0_debugaccess   (mm_interconnect_0_registers_s0_debugaccess),   //      .debugaccess
		.m0_waitrequest   (conv_registers_waitrequest),                   //    m0.waitrequest
		.m0_readdata      (conv_registers_readdata),                      //      .readdata
		.m0_readdatavalid (conv_registers_readdatavalid),                 //      .readdatavalid
		.m0_burstcount    (conv_registers_burstcount),                    //      .burstcount
		.m0_writedata     (conv_registers_writedata),                     //      .writedata
		.m0_address       (conv_registers_address),                       //      .address
		.m0_write         (conv_registers_write),                         //      .write
		.m0_read          (conv_registers_read),                          //      .read
		.m0_byteenable    (conv_registers_byteenable),                    //      .byteenable
		.m0_debugaccess   (conv_registers_debugaccess),                   //      .debugaccess
		.s0_response      (),                                             // (terminated)
		.m0_response      (2'b00)                                         // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (9),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) uart1 (
		.clk              (clk_clk),                                  //   clk.clk
		.reset            (rst_controller_reset_out_reset),           // reset.reset
		.s0_waitrequest   (mm_interconnect_0_uart1_s0_waitrequest),   //    s0.waitrequest
		.s0_readdata      (mm_interconnect_0_uart1_s0_readdata),      //      .readdata
		.s0_readdatavalid (mm_interconnect_0_uart1_s0_readdatavalid), //      .readdatavalid
		.s0_burstcount    (mm_interconnect_0_uart1_s0_burstcount),    //      .burstcount
		.s0_writedata     (mm_interconnect_0_uart1_s0_writedata),     //      .writedata
		.s0_address       (mm_interconnect_0_uart1_s0_address),       //      .address
		.s0_write         (mm_interconnect_0_uart1_s0_write),         //      .write
		.s0_read          (mm_interconnect_0_uart1_s0_read),          //      .read
		.s0_byteenable    (mm_interconnect_0_uart1_s0_byteenable),    //      .byteenable
		.s0_debugaccess   (mm_interconnect_0_uart1_s0_debugaccess),   //      .debugaccess
		.m0_waitrequest   (uart1_waitrequest),                        //    m0.waitrequest
		.m0_readdata      (uart1_readdata),                           //      .readdata
		.m0_readdatavalid (uart1_readdatavalid),                      //      .readdatavalid
		.m0_burstcount    (uart1_burstcount),                         //      .burstcount
		.m0_writedata     (uart1_writedata),                          //      .writedata
		.m0_address       (uart1_address),                            //      .address
		.m0_write         (uart1_write),                              //      .write
		.m0_read          (uart1_read),                               //      .read
		.m0_byteenable    (uart1_byteenable),                         //      .byteenable
		.m0_debugaccess   (uart1_debugaccess),                        //      .debugaccess
		.s0_response      (),                                         // (terminated)
		.m0_response      (2'b00)                                     // (terminated)
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (16),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (9),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) uart2 (
		.clk              (clk_clk),                                  //   clk.clk
		.reset            (rst_controller_reset_out_reset),           // reset.reset
		.s0_waitrequest   (mm_interconnect_0_uart2_s0_waitrequest),   //    s0.waitrequest
		.s0_readdata      (mm_interconnect_0_uart2_s0_readdata),      //      .readdata
		.s0_readdatavalid (mm_interconnect_0_uart2_s0_readdatavalid), //      .readdatavalid
		.s0_burstcount    (mm_interconnect_0_uart2_s0_burstcount),    //      .burstcount
		.s0_writedata     (mm_interconnect_0_uart2_s0_writedata),     //      .writedata
		.s0_address       (mm_interconnect_0_uart2_s0_address),       //      .address
		.s0_write         (mm_interconnect_0_uart2_s0_write),         //      .write
		.s0_read          (mm_interconnect_0_uart2_s0_read),          //      .read
		.s0_byteenable    (mm_interconnect_0_uart2_s0_byteenable),    //      .byteenable
		.s0_debugaccess   (mm_interconnect_0_uart2_s0_debugaccess),   //      .debugaccess
		.m0_waitrequest   (uart2_waitrequest),                        //    m0.waitrequest
		.m0_readdata      (uart2_readdata),                           //      .readdata
		.m0_readdatavalid (uart2_readdatavalid),                      //      .readdatavalid
		.m0_burstcount    (uart2_burstcount),                         //      .burstcount
		.m0_writedata     (uart2_writedata),                          //      .writedata
		.m0_address       (uart2_address),                            //      .address
		.m0_write         (uart2_write),                              //      .write
		.m0_read          (uart2_read),                               //      .read
		.m0_byteenable    (uart2_byteenable),                         //      .byteenable
		.m0_debugaccess   (uart2_debugaccess),                        //      .debugaccess
		.s0_response      (),                                         // (terminated)
		.m0_response      (2'b00)                                     // (terminated)
	);

	altera_dual_boot #(
		.INTENDED_DEVICE_FAMILY ("MAX 10"),
		.CONFIG_CYCLE           (18),
		.RESET_TIMER_CYCLE      (26)
	) dual_boot (
		.clk                (clk_50_clk),                                   //    clk.clk
		.nreset             (~rst_controller_002_reset_out_reset),          // nreset.reset_n
		.avmm_rcv_address   (mm_interconnect_0_dual_boot_avalon_address),   // avalon.address
		.avmm_rcv_read      (mm_interconnect_0_dual_boot_avalon_read),      //       .read
		.avmm_rcv_writedata (mm_interconnect_0_dual_boot_avalon_writedata), //       .writedata
		.avmm_rcv_write     (mm_interconnect_0_dual_boot_avalon_write),     //       .write
		.avmm_rcv_readdata  (mm_interconnect_0_dual_boot_avalon_readdata)   //       .readdata
	);

	nios_conv_usb_1553_mm_interconnect_0 mm_interconnect_0 (
		.clk_100M_clk_clk                             (clk_clk),                                                  //                           clk_100M_clk.clk
		.dualboot_clk_clk_clk                         (clk_50_clk),                                               //                       dualboot_clk_clk.clk
		.dual_boot_nreset_reset_bridge_in_reset_reset (rst_controller_002_reset_out_reset),                       // dual_boot_nreset_reset_bridge_in_reset.reset
		.JTagUart_reset_reset_bridge_in_reset_reset   (rst_controller_001_reset_out_reset),                       //   JTagUart_reset_reset_bridge_in_reset.reset
		.NIOS2_GEN2_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                           // NIOS2_GEN2_reset_reset_bridge_in_reset.reset
		.NIOS2_GEN2_data_master_address               (nios2_gen2_data_master_address),                           //                 NIOS2_GEN2_data_master.address
		.NIOS2_GEN2_data_master_waitrequest           (nios2_gen2_data_master_waitrequest),                       //                                       .waitrequest
		.NIOS2_GEN2_data_master_byteenable            (nios2_gen2_data_master_byteenable),                        //                                       .byteenable
		.NIOS2_GEN2_data_master_read                  (nios2_gen2_data_master_read),                              //                                       .read
		.NIOS2_GEN2_data_master_readdata              (nios2_gen2_data_master_readdata),                          //                                       .readdata
		.NIOS2_GEN2_data_master_write                 (nios2_gen2_data_master_write),                             //                                       .write
		.NIOS2_GEN2_data_master_writedata             (nios2_gen2_data_master_writedata),                         //                                       .writedata
		.NIOS2_GEN2_data_master_debugaccess           (nios2_gen2_data_master_debugaccess),                       //                                       .debugaccess
		.NIOS2_GEN2_instruction_master_address        (nios2_gen2_instruction_master_address),                    //          NIOS2_GEN2_instruction_master.address
		.NIOS2_GEN2_instruction_master_waitrequest    (nios2_gen2_instruction_master_waitrequest),                //                                       .waitrequest
		.NIOS2_GEN2_instruction_master_read           (nios2_gen2_instruction_master_read),                       //                                       .read
		.NIOS2_GEN2_instruction_master_readdata       (nios2_gen2_instruction_master_readdata),                   //                                       .readdata
		.dual_boot_avalon_address                     (mm_interconnect_0_dual_boot_avalon_address),               //                       dual_boot_avalon.address
		.dual_boot_avalon_write                       (mm_interconnect_0_dual_boot_avalon_write),                 //                                       .write
		.dual_boot_avalon_read                        (mm_interconnect_0_dual_boot_avalon_read),                  //                                       .read
		.dual_boot_avalon_readdata                    (mm_interconnect_0_dual_boot_avalon_readdata),              //                                       .readdata
		.dual_boot_avalon_writedata                   (mm_interconnect_0_dual_boot_avalon_writedata),             //                                       .writedata
		.Input_Signals_s1_address                     (mm_interconnect_0_input_signals_s1_address),               //                       Input_Signals_s1.address
		.Input_Signals_s1_write                       (mm_interconnect_0_input_signals_s1_write),                 //                                       .write
		.Input_Signals_s1_readdata                    (mm_interconnect_0_input_signals_s1_readdata),              //                                       .readdata
		.Input_Signals_s1_writedata                   (mm_interconnect_0_input_signals_s1_writedata),             //                                       .writedata
		.Input_Signals_s1_chipselect                  (mm_interconnect_0_input_signals_s1_chipselect),            //                                       .chipselect
		.JTagUart_avalon_jtag_slave_address           (mm_interconnect_0_jtaguart_avalon_jtag_slave_address),     //             JTagUart_avalon_jtag_slave.address
		.JTagUart_avalon_jtag_slave_write             (mm_interconnect_0_jtaguart_avalon_jtag_slave_write),       //                                       .write
		.JTagUart_avalon_jtag_slave_read              (mm_interconnect_0_jtaguart_avalon_jtag_slave_read),        //                                       .read
		.JTagUart_avalon_jtag_slave_readdata          (mm_interconnect_0_jtaguart_avalon_jtag_slave_readdata),    //                                       .readdata
		.JTagUart_avalon_jtag_slave_writedata         (mm_interconnect_0_jtaguart_avalon_jtag_slave_writedata),   //                                       .writedata
		.JTagUart_avalon_jtag_slave_waitrequest       (mm_interconnect_0_jtaguart_avalon_jtag_slave_waitrequest), //                                       .waitrequest
		.JTagUart_avalon_jtag_slave_chipselect        (mm_interconnect_0_jtaguart_avalon_jtag_slave_chipselect),  //                                       .chipselect
		.MAX10_FLASH_csr_address                      (mm_interconnect_0_max10_flash_csr_address),                //                        MAX10_FLASH_csr.address
		.MAX10_FLASH_csr_write                        (mm_interconnect_0_max10_flash_csr_write),                  //                                       .write
		.MAX10_FLASH_csr_read                         (mm_interconnect_0_max10_flash_csr_read),                   //                                       .read
		.MAX10_FLASH_csr_readdata                     (mm_interconnect_0_max10_flash_csr_readdata),               //                                       .readdata
		.MAX10_FLASH_csr_writedata                    (mm_interconnect_0_max10_flash_csr_writedata),              //                                       .writedata
		.MAX10_FLASH_data_address                     (mm_interconnect_0_max10_flash_data_address),               //                       MAX10_FLASH_data.address
		.MAX10_FLASH_data_write                       (mm_interconnect_0_max10_flash_data_write),                 //                                       .write
		.MAX10_FLASH_data_read                        (mm_interconnect_0_max10_flash_data_read),                  //                                       .read
		.MAX10_FLASH_data_readdata                    (mm_interconnect_0_max10_flash_data_readdata),              //                                       .readdata
		.MAX10_FLASH_data_writedata                   (mm_interconnect_0_max10_flash_data_writedata),             //                                       .writedata
		.MAX10_FLASH_data_burstcount                  (mm_interconnect_0_max10_flash_data_burstcount),            //                                       .burstcount
		.MAX10_FLASH_data_readdatavalid               (mm_interconnect_0_max10_flash_data_readdatavalid),         //                                       .readdatavalid
		.MAX10_FLASH_data_waitrequest                 (mm_interconnect_0_max10_flash_data_waitrequest),           //                                       .waitrequest
		.Mil1553_s0_address                           (mm_interconnect_0_mil1553_s0_address),                     //                             Mil1553_s0.address
		.Mil1553_s0_write                             (mm_interconnect_0_mil1553_s0_write),                       //                                       .write
		.Mil1553_s0_read                              (mm_interconnect_0_mil1553_s0_read),                        //                                       .read
		.Mil1553_s0_readdata                          (mm_interconnect_0_mil1553_s0_readdata),                    //                                       .readdata
		.Mil1553_s0_writedata                         (mm_interconnect_0_mil1553_s0_writedata),                   //                                       .writedata
		.Mil1553_s0_burstcount                        (mm_interconnect_0_mil1553_s0_burstcount),                  //                                       .burstcount
		.Mil1553_s0_byteenable                        (mm_interconnect_0_mil1553_s0_byteenable),                  //                                       .byteenable
		.Mil1553_s0_readdatavalid                     (mm_interconnect_0_mil1553_s0_readdatavalid),               //                                       .readdatavalid
		.Mil1553_s0_waitrequest                       (mm_interconnect_0_mil1553_s0_waitrequest),                 //                                       .waitrequest
		.Mil1553_s0_debugaccess                       (mm_interconnect_0_mil1553_s0_debugaccess),                 //                                       .debugaccess
		.NIOS2_GEN2_debug_mem_slave_address           (mm_interconnect_0_nios2_gen2_debug_mem_slave_address),     //             NIOS2_GEN2_debug_mem_slave.address
		.NIOS2_GEN2_debug_mem_slave_write             (mm_interconnect_0_nios2_gen2_debug_mem_slave_write),       //                                       .write
		.NIOS2_GEN2_debug_mem_slave_read              (mm_interconnect_0_nios2_gen2_debug_mem_slave_read),        //                                       .read
		.NIOS2_GEN2_debug_mem_slave_readdata          (mm_interconnect_0_nios2_gen2_debug_mem_slave_readdata),    //                                       .readdata
		.NIOS2_GEN2_debug_mem_slave_writedata         (mm_interconnect_0_nios2_gen2_debug_mem_slave_writedata),   //                                       .writedata
		.NIOS2_GEN2_debug_mem_slave_byteenable        (mm_interconnect_0_nios2_gen2_debug_mem_slave_byteenable),  //                                       .byteenable
		.NIOS2_GEN2_debug_mem_slave_waitrequest       (mm_interconnect_0_nios2_gen2_debug_mem_slave_waitrequest), //                                       .waitrequest
		.NIOS2_GEN2_debug_mem_slave_debugaccess       (mm_interconnect_0_nios2_gen2_debug_mem_slave_debugaccess), //                                       .debugaccess
		.ONCHIP_RAM_32k_s1_address                    (mm_interconnect_0_onchip_ram_32k_s1_address),              //                      ONCHIP_RAM_32k_s1.address
		.ONCHIP_RAM_32k_s1_write                      (mm_interconnect_0_onchip_ram_32k_s1_write),                //                                       .write
		.ONCHIP_RAM_32k_s1_readdata                   (mm_interconnect_0_onchip_ram_32k_s1_readdata),             //                                       .readdata
		.ONCHIP_RAM_32k_s1_writedata                  (mm_interconnect_0_onchip_ram_32k_s1_writedata),            //                                       .writedata
		.ONCHIP_RAM_32k_s1_byteenable                 (mm_interconnect_0_onchip_ram_32k_s1_byteenable),           //                                       .byteenable
		.ONCHIP_RAM_32k_s1_chipselect                 (mm_interconnect_0_onchip_ram_32k_s1_chipselect),           //                                       .chipselect
		.ONCHIP_RAM_32k_s1_clken                      (mm_interconnect_0_onchip_ram_32k_s1_clken),                //                                       .clken
		.Output_Signals_s1_address                    (mm_interconnect_0_output_signals_s1_address),              //                      Output_Signals_s1.address
		.Output_Signals_s1_write                      (mm_interconnect_0_output_signals_s1_write),                //                                       .write
		.Output_Signals_s1_readdata                   (mm_interconnect_0_output_signals_s1_readdata),             //                                       .readdata
		.Output_Signals_s1_writedata                  (mm_interconnect_0_output_signals_s1_writedata),            //                                       .writedata
		.Output_Signals_s1_chipselect                 (mm_interconnect_0_output_signals_s1_chipselect),           //                                       .chipselect
		.Registers_s0_address                         (mm_interconnect_0_registers_s0_address),                   //                           Registers_s0.address
		.Registers_s0_write                           (mm_interconnect_0_registers_s0_write),                     //                                       .write
		.Registers_s0_read                            (mm_interconnect_0_registers_s0_read),                      //                                       .read
		.Registers_s0_readdata                        (mm_interconnect_0_registers_s0_readdata),                  //                                       .readdata
		.Registers_s0_writedata                       (mm_interconnect_0_registers_s0_writedata),                 //                                       .writedata
		.Registers_s0_burstcount                      (mm_interconnect_0_registers_s0_burstcount),                //                                       .burstcount
		.Registers_s0_byteenable                      (mm_interconnect_0_registers_s0_byteenable),                //                                       .byteenable
		.Registers_s0_readdatavalid                   (mm_interconnect_0_registers_s0_readdatavalid),             //                                       .readdatavalid
		.Registers_s0_waitrequest                     (mm_interconnect_0_registers_s0_waitrequest),               //                                       .waitrequest
		.Registers_s0_debugaccess                     (mm_interconnect_0_registers_s0_debugaccess),               //                                       .debugaccess
		.Uart1_s0_address                             (mm_interconnect_0_uart1_s0_address),                       //                               Uart1_s0.address
		.Uart1_s0_write                               (mm_interconnect_0_uart1_s0_write),                         //                                       .write
		.Uart1_s0_read                                (mm_interconnect_0_uart1_s0_read),                          //                                       .read
		.Uart1_s0_readdata                            (mm_interconnect_0_uart1_s0_readdata),                      //                                       .readdata
		.Uart1_s0_writedata                           (mm_interconnect_0_uart1_s0_writedata),                     //                                       .writedata
		.Uart1_s0_burstcount                          (mm_interconnect_0_uart1_s0_burstcount),                    //                                       .burstcount
		.Uart1_s0_byteenable                          (mm_interconnect_0_uart1_s0_byteenable),                    //                                       .byteenable
		.Uart1_s0_readdatavalid                       (mm_interconnect_0_uart1_s0_readdatavalid),                 //                                       .readdatavalid
		.Uart1_s0_waitrequest                         (mm_interconnect_0_uart1_s0_waitrequest),                   //                                       .waitrequest
		.Uart1_s0_debugaccess                         (mm_interconnect_0_uart1_s0_debugaccess),                   //                                       .debugaccess
		.Uart2_s0_address                             (mm_interconnect_0_uart2_s0_address),                       //                               Uart2_s0.address
		.Uart2_s0_write                               (mm_interconnect_0_uart2_s0_write),                         //                                       .write
		.Uart2_s0_read                                (mm_interconnect_0_uart2_s0_read),                          //                                       .read
		.Uart2_s0_readdata                            (mm_interconnect_0_uart2_s0_readdata),                      //                                       .readdata
		.Uart2_s0_writedata                           (mm_interconnect_0_uart2_s0_writedata),                     //                                       .writedata
		.Uart2_s0_burstcount                          (mm_interconnect_0_uart2_s0_burstcount),                    //                                       .burstcount
		.Uart2_s0_byteenable                          (mm_interconnect_0_uart2_s0_byteenable),                    //                                       .byteenable
		.Uart2_s0_readdatavalid                       (mm_interconnect_0_uart2_s0_readdatavalid),                 //                                       .readdatavalid
		.Uart2_s0_waitrequest                         (mm_interconnect_0_uart2_s0_waitrequest),                   //                                       .waitrequest
		.Uart2_s0_debugaccess                         (mm_interconnect_0_uart2_s0_debugaccess)                    //                                       .debugaccess
	);

	nios_conv_usb_1553_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),       // receiver1.irq
		.sender_irq    (nios2_gen2_irq_irq)              //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                       // reset_in0.reset
		.reset_in1      (nios2_gen2_debug_reset_request_reset), // reset_in1.reset
		.clk            (clk_clk),                              //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),   // reset_out.reset
		.reset_req      (),                                     // (terminated)
		.reset_req_in0  (1'b0),                                 // (terminated)
		.reset_req_in1  (1'b0),                                 // (terminated)
		.reset_in2      (1'b0),                                 // (terminated)
		.reset_req_in2  (1'b0),                                 // (terminated)
		.reset_in3      (1'b0),                                 // (terminated)
		.reset_req_in3  (1'b0),                                 // (terminated)
		.reset_in4      (1'b0),                                 // (terminated)
		.reset_req_in4  (1'b0),                                 // (terminated)
		.reset_in5      (1'b0),                                 // (terminated)
		.reset_req_in5  (1'b0),                                 // (terminated)
		.reset_in6      (1'b0),                                 // (terminated)
		.reset_req_in6  (1'b0),                                 // (terminated)
		.reset_in7      (1'b0),                                 // (terminated)
		.reset_req_in7  (1'b0),                                 // (terminated)
		.reset_in8      (1'b0),                                 // (terminated)
		.reset_req_in8  (1'b0),                                 // (terminated)
		.reset_in9      (1'b0),                                 // (terminated)
		.reset_req_in9  (1'b0),                                 // (terminated)
		.reset_in10     (1'b0),                                 // (terminated)
		.reset_req_in10 (1'b0),                                 // (terminated)
		.reset_in11     (1'b0),                                 // (terminated)
		.reset_req_in11 (1'b0),                                 // (terminated)
		.reset_in12     (1'b0),                                 // (terminated)
		.reset_req_in12 (1'b0),                                 // (terminated)
		.reset_in13     (1'b0),                                 // (terminated)
		.reset_req_in13 (1'b0),                                 // (terminated)
		.reset_in14     (1'b0),                                 // (terminated)
		.reset_req_in14 (1'b0),                                 // (terminated)
		.reset_in15     (1'b0),                                 // (terminated)
		.reset_req_in15 (1'b0)                                  // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (~reset_50_reset_n),                  // reset_in0.reset
		.clk            (clk_50_clk),                         //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
